### ISSUE TITLE
CSS Update

### ISSUE THREAD

**Issue by renebrain** [troolee/gridstack.js#103]
Hi, i tried to update my css code (which is from Nov. 2014) to the new css structure, but when i use the new css guys then my whole application gets disformed. Actually, all css classes that are applied to elements within the gridstack are just removed. Why is this happening when i add the new css?

old css:
.grid-stack {
position: relative;

}
.grid-stack-item {
position: absolute;
border: 1px #2d6ca2 solid;
padding: 0;

}
.grid-stack-item .grid-stack-item-content,
.grid-stack-item .placeholder-content {
margin: 0;
position: absolute;
top: 0;
left: 10px;
right: 10px;
bottom: 0;
width: auto;
z-index: 0 !important;
cursor: pointer; cursor: hand;
}
.grid-stack-placeholder .placeholder-content {
border: 1px dashed lightgray;
}
.grid-stack-item.ui-draggable-dragging,
.grid-stack-item.ui-resizable-resizing {
z-index: 100;
}
.grid-stack-item.ui-draggable-dragging .grid-stack-item-content,
.grid-stack-item.ui-resizable-resizing .grid-stack-item-content {
box-shadow: 1px 4px 6px rgba(0, 0, 0, 0.2);
opacity: 0.8;
}
.grid-stack-item .ui-resizable-handle {
padding: 3px;
margin: 3px 0;
cursor: nwse-resize;
color: gray;
position: absolute;
bottom: 0;
right: 7px;
font: normal normal normal 14px/1 FontAwesome;
text-rendering: auto;
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1);
-webkit-transform: rotate(90deg);
-ms-transform: rotate(90deg);
transform: rotate(90deg);
font-size: 24px;
}
.grid-stack-item .ui-resizable-handle::before {
content: "\f065";
}

.grid-stack-item[data-gs-width="12"] { width: 100% }
.grid-stack-item[data-gs-width="11"] { width: 91.66666667% }
.grid-stack-item[data-gs-width="10"] { width: 83.33333333% }
.grid-stack-item[data-gs-width="9"] { width: 75% }
.grid-stack-item[data-gs-width="8"] { width: 66.66666667% }
.grid-stack-item[data-gs-width="7"] { width: 58.33333333% }
.grid-stack-item[data-gs-width="6"] { width: 50% }
.grid-stack-item[data-gs-width="5"] { width: 41.66666667% }
.grid-stack-item[data-gs-width="4"] { width: 33.33333333% }
.grid-stack-item[data-gs-width="3"] { width: 25% }
.grid-stack-item[data-gs-width="2"] { width: 16.66666667% }
.grid-stack-item[data-gs-width="1"] { width: 8.33333333% }
.grid-stack-item[data-gs-x="12"] { left: 100% }
.grid-stack-item[data-gs-x="11"] { left: 91.66666667% }
.grid-stack-item[data-gs-x="10"] { left: 83.33333333% }
.grid-stack-item[data-gs-x="9"] { left: 75% }
.grid-stack-item[data-gs-x="8"] { left: 66.66666667% }
.grid-stack-item[data-gs-x="7"] { left: 58.33333333% }
.grid-stack-item[data-gs-x="6"] { left: 50% }
.grid-stack-item[data-gs-x="5"] { left: 41.66666667% }
.grid-stack-item[data-gs-x="4"] { left: 33.33333333% }
.grid-stack-item[data-gs-x="3"] { left: 25% }
.grid-stack-item[data-gs-x="2"] { left: 16.66666667% }
.grid-stack-item[data-gs-x="1"] { left: 8.33333333% }

The new css is from this repository. What do i have to do to enable all the styles for elements within the gridstack?

**Comment by troolee** [comment]
Did you update js file as well?

**Comment by renebrain** [comment]
I guess...i will check out which .js Version i run and write it here (in round about 2 hours)...i think i updated the .js code last week to the latest version. With the original .css everything works fine. But with that, i cannot really use the new features.

**Comment by renebrain** [comment]
I use the following Version
//gridstack.js 0.2.3-dev

i think it is the latest one.

Any ideas why this happens? Is it maybe a css issue? because there are no styles for all the children elements in the gridstack.

**Comment by troolee** [comment]
It's hard to say without seeing the code... Gridstack shouldn't affect something else, but everything could be. So you can try to make a copy of gridstack's CSS, comment all rules and start to uncomment them one by one to find which rule breaks your layout and why.

**Comment by renebrain** [comment]
This topic can be closed...all out of the sudden, he takes all the styles now...i don't know how. Thanks for your help, though ;)
