### ISSUE TITLE
Can't get GS working for some reason

### ISSUE THREAD

**Issue by dschueler** [troolee/gridstack.js#104]
I have been using gridster and all well, somehow I can't get gridstack going..it just ends up blank div. 
It's probably something obvious but it's not jumping out at me. 

Here is a fiddle. 

https://jsfiddle.net/dschueler/vutut21k/

**Comment by ascendantofrain** [comment]
You need to load underscore.js as well.

**Comment by ascendantofrain** [comment]
Also, your gridstack is getting a height of 0px on load.  Maybe investigate
why that is happening.

**Comment by dschueler** [comment]
I loaded underscore and still no output. Does this fiddle look correct?

**Comment by ascendantofrain** [comment]
Also remove the script tags from your js area.  Familiarize yourself with
how jsfiddle works and make sure youre loading all of your components
correclty first.

**Comment by dschueler** [comment]
Adam, I  have loaded underscore and still no output. 

If you want to take a look at my fiddle check this out.

https://jsfiddle.net/dschueler/vutut21k/#&togetherjs=PCvoLFgRpi


> On Mar 25, 2015, at 10:22 AM, Adam Verheyen <notifications@github.com> wrote:
> 
> You need to load underscore.js as well.
> 
> On Wed, Mar 25, 2015 at 10:20 AM, dschueler <notifications@github.com>
> wrote:
> 
> > I have been using gridster and all well, somehow I can't get gridstack
> > going..it just ends up blank div.
> > It's probably something obvious but it's not jumping out at me.
> >
> > Here is a fiddle.
> >
> > https://jsfiddle.net/dschueler/vutut21k/
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/troolee/gridstack.js/issues/104>.
> >
> —
> Reply to this email directly or view it on GitHub <https://github.com/troolee/gridstack.js/issues/104#issuecomment-86047859>.
> 

Don Schueler
don.schueler@gmail.com
Mobile: (240) 844-2425

**Comment by dschueler** [comment]
Adam, I admit I am new to fiddle and getting used to it’s way.

I removed script tags and loading resources from the External Resources section and Frameworks and Extensions section

I appreciate your help. 

Thanks..Don


> On Mar 25, 2015, at 10:34 AM, Adam Verheyen <notifications@github.com> wrote:
> 
> Also remove the script tags from your js area. Familiarize yourself with
> how jsfiddle works and make sure youre loading all of your components
> correclty first.
> 
> On Wed, Mar 25, 2015 at 10:33 AM, dschueler <notifications@github.com>
> wrote:
> 
> > I loaded underscore and still no output. Does this fiddle look correct?
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/troolee/gridstack.js/issues/104#issuecomment-86051725>
> > .
> >
> —
> Reply to this email directly or view it on GitHub <https://github.com/troolee/gridstack.js/issues/104#issuecomment-86052407>.
> 

Don Schueler
don.schueler@gmail.com
Mobile: (240) 844-2425

**Comment by dschueler** [comment]
This still didn't work for me no matter what I did...EXCEPT one thing. I took the source from the source folder and embedded it into my page and VOILA! It all works as I would expect. If I include the minified version directly in source OR from https://cdnjs.cloudflare.com/ajax/libs/gridstack.js/0.2.2/gridstack.min.js
it does NOT work. I wonder if there is some issue with the minified versions????

**Comment by troolee** [comment]
Hi,

Please check it out: https://jsfiddle.net/ssfk1kfa/1/

Note, that lodash support announced in 0.2.3 only. Please also note the order of js files... gridstack.js must be included after jquery, jquery ui and underscore.
