### ISSUE TITLE
Angular version

### ISSUE THREAD

**Issue by Tropicalista** [troolee/gridstack.js#105]
Any chance to have an angular version?

**Comment by troolee** [comment]
It is in TODO list

**Comment by Petah** [comment]
+1

**Comment by sasivarnan** [comment]
+1 (y)

**Comment by Tropicalista** [comment]
I have used https://github.com/JimLiu/angular-ui-gridster with success but is using gridster. Do you have any advice on how to start developing an angularjs directive?

Thanks

**Comment by d0coat01** [comment]
+1

**Comment by abologna-r7** [comment]
btw I have a backbone+marionette version :) will push my changes later on.

**Comment by tonjack** [comment]
Any idea when the Angular support will be out?

**Comment by ivan206** [comment]
+1

**Comment by Tropicalista** [comment]
I've made  afirst attempt to create an angular directive: https://github.com/Tropicalista/gridstack.js/blob/feature/angular/src/angular/gridstack.js

The problem is to fire a serialization of widget, that is poor performance if I use the code provided in the example. I will try some different approach as soon as possible...

**Comment by mgwidmann** [comment]
:+1:

**Comment by mtyeh411** [comment]
:+1:

**Comment by americos** [comment]
:+1:

**Comment by andreibondarev** [comment]
:+1:

**Comment by katesanford22** [comment]
:+1:

**Comment by Tropicalista** [comment]
I've built a really simple angular directive for angular. It's really basic, but it suits my needs.

[angular gridstack](http://github.com/tropicalista/angular-gridstack)

The only problem I'm facing is with widget auto position. If someone could help is really appreciated.

**Comment by RobertoJBM** [comment]
+1

**Comment by kdietrich** [comment]
:+1: I fixed your auto positioning problem by the way @Tropicalista. See my PR.

**Comment by palpatine1991** [comment]
+1

**Comment by kdietrich** [comment]
I've created an Angular.js directive for gridstack.js. Feel free to install, ask questions and extend it with your PR. https://github.com/kdietrich/gridstack-angular

**Comment by pankajparkar** [comment]
+1 

@kdietrich Do check your Repository. I made one [small PR](https://github.com/kdietrich/gridstack-angular/pull/3) but that is important to get merged ASAP.

**Comment by Luchillo** [comment]
This post seems rather old, however @pankajparkar do you know if there's any chance to get an example to get gridstack working with angular 2?

**Comment by fergusg** [comment]
I have it working, at least at a basic level of functionality - will post code later.

**Comment by kdietrich** [comment]
I'll look into an Angular.js 2 version too.

**Comment by Luchillo** [comment]
@fergusg i have it working too, however issues arise when it comes to `ngFor`, i can make it work with predefined html but when using `ngFor` i can't make it work, do you have it working with dynamic data?

**Comment by Luchillo** [comment]
Ok i kind of found a hack to fix my issue, i just use `$(window).trigger('resize');` to trigger the plugin's update after items are added as widget, it's a hacky fix, but at least it works.

**Comment by Luchillo** [comment]
Ok now it messes with the angular model detection.

**Comment by pankajparkar** [comment]
@Luchillo the asynchronous event occurs outside angular2 context(ngZone), at time angular2 doesn't run Change Detection. you need to run CD manually, you refer [this answer](http://stackoverflow.com/a/34829089/2435473) by he has mentioned all possible way to run CD cycle.

**Comment by Luchillo** [comment]
Why does it occur outside angular 2? i just take data from an api and put it in the variable that i render with `{{ widget.title }}: {{ widget.data[0].value }}`, it just sinks when i started using the plugin?

**Comment by Luchillo** [comment]
Nope, tried the 3 ways and doesn't work, the plugin just won't play nicely with A2.

**Comment by krilllind** [comment]
I have written a directive for Angular.IO  generating a grid with specified options and resize event working. Hope to see this implemented in gridstack soon so I don't have to write everything myself.

**Comment by AllenConway** [comment]
> @fergusg i have it working too, however issues arise when it comes to `ngFor`, i can make it work with predefined html but when using `ngFor` i can't make it work, do you have it working with dynamic data?

This is an older post, but in order to make gridstack work with `*ngfor`, the `$('.grid-stack').gridstack();` command must be called in `ngAfterViewInit`

```
    ngAfterViewInit() {
        setTimeout(() => {
            $('.grid-stack').gridstack();
            this.gridStack = $('.grid-stack').data('gridstack');
        }, 300); //This MUST finish after dynamic data is retrieved for ngfor, and calling these statements in another area just doesn't work
    }
```

**Comment by adumesny** [comment]
might be worth revisiting this thread as I've been using my own Angular (now 8)/Typescript based wrapper for gridstack for over 2.5 years now... I wold think a lot more adoption if it came out of the box with angular support (might need separate npm image due to dependencies). But then again there are now native angular versions which look decent that didn't exist back when I adopted this...

**Comment by antonjstu** [comment]
Any updates on this?

**Comment by adumesny** [comment]
no time I'm afraid... there are posted angular examples though...
