### ISSUE TITLE
events for add & removing widgets

### ISSUE THREAD

**Issue by xLink** [troolee/gridstack.js#106]
any chance you could add events for when a widget gets added, and one for removal of a widget too

**Comment by troolee** [comment]
Sure, I can do this.

**Comment by FredFaust** [comment]
While playing with the code for add and remove, could you check [this issue](https://github.com/troolee/gridstack.js/issues/167).

Thanks !

**Comment by radiolips** [comment]
Duplicate of #54. Emitting events for adding and removing widgets will be completed for v0.2.5 and the original ticket will be updated when the feature has been completed.
