### ISSUE TITLE
Outside of columns limit

### ISSUE THREAD

**Issue by ClementNoiville** [troolee/gridstack.js#107]
Hi,

I discovered that if you resize an item by the left corner of bottom, and move to right, you can plot the item in an extra column.

Somes screens : 
http://screen.x3n.fr/2015-03-28_09.53.34.png
http://screen.x3n.fr/2015-03-28_09.54.27.png
http://screen.x3n.fr/2015-03-28_09.55.00.png

How fix that ?

Thanks

**Comment by radiolips** [comment]
I'm unable to resize by the sw corner and move beyond the point of 1x1.
