### ISSUE TITLE
Drag drop anywhere within grid

### ISSUE THREAD

**Issue by franciskim** [troolee/gridstack.js#109]
All libraries I've come across (gridstack, gridly, gridster) do not allow a widget to be dropped with some vertical spacing - it always snaps upwards to the nearest widget. Seeking some help here with customising gridstack to allow this behaviour.

**Comment by Petah** [comment]
Set the `float` option to true:

```
$(container).gridstack({
    float: true
})
```

**Comment by franciskim** [comment]
so easy, thanks!
