### ISSUE TITLE
Drag & drop to add

### ISSUE THREAD

**Issue by franciskim** [troolee/gridstack.js#110]
Is it possible to drag & drop to add a widget?

**Comment by cjgordon** [comment]
I have been able to achieve this using standard jQuery draggable and droppable.

Basically you apply draggable to the elements you wan't to drag into the grid with the drop target set as the grid wrapper element. Then bind dropable to the grids wrapper and use the drop event to call grid stacks add widget function.

In my case I'm using div's which hold images of what a widget will look like to drag out of a side bar, and then in the drop event load the correct widget based on the data attributes on the draggable element.

On the weekend I'll put together a simplified example and submit.

Cheers
Chris

**Comment by franciskim** [comment]
@cjgordon Hey Chris - great news. Have you been able to get the example ready at all?

**Comment by franciskim** [comment]
Your comments make enough sense though, I might give it a shot now.

**Comment by sgruhier** [comment]
any chance to have an example?
Thanks a lot

**Comment by h-nazzal** [comment]
take a look at "add_widget(el, x, y, width, height, auto_position)"
something like this would do the trick 

```javascript
$('element_to_be_added_on_drop').draggable({
drop : function(event){
       my_grid = add_widget($('element_to_be_added_on_drop'), x, y, width, height, auto_position)
}
})
```

something similar to the pseudo code above would do the trick
