### ISSUE TITLE
multiple instances of gridster

### ISSUE THREAD

**Issue by kozilla** [troolee/gridstack.js#111]
Hi Troolee,

I am trying to create 2 separate  instances of gridster on one page how ever i have found some difficulties as they are using the same naming conventions. I have tried to initialize gridster with options  (item_class ,placeholder_class) how ever I couldnt see any differences. Could you advise pls if gridster support multiple instances on one project and if yes ;) how correctly initialize each instance. I am trying :
for second instance I am trying : 

<div class="grid-stack test">

</div>
    var options = {
        cell_height: 10,
        vertical_margin: 10,
		item_class: "my_iteam_class",
		placeholder_class: "my_placeholder_class"
		
    };
    $('.grid-stack.test').gridstack(options);

Thanks for advance...

**Comment by jpsfs** [comment]
I'm also having problems with this.
@kozilla did you managed to put this to work?

@troolee Any suggestion?

**Comment by troolee** [comment]
Please check 2 grids demo http://troolee.github.io/gridstack.js/demo/two.html
