### ISSUE TITLE
Basic usage structure not working

### ISSUE THREAD

**Issue by nWidart** [troolee/gridstack.js#112]
Hello,

I used the 'Basic Structure' code from the repo, but it doesn't work.
You can check out the 'demo' here: https://github.com/nWidart/gridstack-test

Did I miss something ?

Thanks

**Comment by nWidart** [comment]
Could you please tag version 0.2.3 ? 

I just tried with the manuel download, which gets v0.2.3 and it works with that.

**Comment by troolee** [comment]
Does it show any js errors? Please check out the basic sample: https://jsfiddle.net/ssfk1kfa/1/

Gridstack 0.2.3 is currently under development. So I will tag it as soon as it will be released.

**Comment by nWidart** [comment]
No errors. As you can see on the github repo, I have the same resources as the basic demo.

Oh, that's too bad, since v0.2.2 is broken for me here. Hopefully version 0.2.3 gets tagged soon. I'd much prefer have the dependency installed via bower that hardcoded.

**Comment by erayerdin** [comment]
I strangely have the same problem, too.
