### ISSUE TITLE
Animation deactivate during runtime

### ISSUE THREAD

**Issue by renebrain** [troolee/gridstack.js#114]
Is it possible to set the animation of the gridstack to false when the gridstack is already built up?

I tried just to set the options this way but it doesn't work.

$('.grid-stack').gridstack({animate:false});

**Comment by troolee** [comment]
I will add corresponding API method

**Comment by renebrain** [comment]
Awesome ;)

**Comment by radiolips** [comment]
This functionality was already present. The API docs have been updated with such info. Please use the `setAnimate` function and pass `false` to disable animation after the grid has been initialized. If using 0.2.4 (stable) use `set_animate` instead.
