### ISSUE TITLE
And min-width and min-height when resize a widget.

### ISSUE THREAD

**Issue by Sophia-nguyen** [troolee/gridstack.js#115]
Hello, please could you tell me how to add min-width and min-height when I resize  a widget.

**Comment by troolee** [comment]
https://github.com/troolee/gridstack.js#item-attributes

**Comment by Sophia-nguyen** [comment]
Thank you very much :)

**Comment by martinduparc** [comment]
FYI - Link is now https://github.com/troolee/gridstack.js/tree/master/doc#item-attributes

**Comment by git-harshIIIT** [comment]
@martinduparc Thankyou :)
