### ISSUE TITLE
How to destroy gridstack before create new.

### ISSUE THREAD

**Issue by Sophia-nguyen** [troolee/gridstack.js#116]
Hello, please help me.
I am using Gridstack for widget layout. But the resize widget funtion works slowly when create Gridstack in many pages and don't reload page. I want to destroy Gridstack before creating new.

**Comment by troolee** [comment]
What do you mean by "in many pages and don't reload page"? Can you describe your use case?

**Comment by Sophia-nguyen** [comment]
Yes,
I use single page app, I create 3 Gridstack  in 3 pages.
If I open page one by one, the speed for resizing widget becomes slower for each page.
But, if I reload the page it works ok.

**Comment by illuminaut** [comment]
Rather than creating three grids you could re-use the same one with remove_all() to remove the widgets and then adding the new ones one by one in your onShow function.

**Comment by asquet** [comment]
+1 for transparent way to destroy gridstack instance. My app is based on ember.js, so component creation and destruction is controlled by framework. Every time user navigates to route with gridstack a new instance is created, when user leaves it is destroyed. I think I get a memory leak this way. 
Using same instance of gridstack seems to be pretty complex comparing to just recreating it.

**Comment by zspitzer** [comment]
+1 most developers consider a destroy method is considered a mandatory feature, you can see the GridStackEngines leaking if you profile in Chrome with a SPA
