### ISSUE TITLE
SW Resize Handler lets widgets move

### ISSUE THREAD

**Issue by renebrain** [troolee/gridstack.js#117]
When i use the SW resize handler to make the widget smaller in width, the widget starts to be pushed to the right side when the min width of the widget is reached. for the SE Handler it works all fine. Something similar happens also on the online Demo of gridstack. Is this on purpose or a bug?

I just think, that both resize handler should behave the same way ;)

**Comment by troolee** [comment]
Yep, it's definitely a bug. Thanks :)

**Comment by troolee** [comment]
It's fixed now
