### ISSUE TITLE
Composite Widgets??

### ISSUE THREAD

**Issue by foo123** [troolee/gridstack.js#120]
Looking for an interactive grid builder (sth like [gridster.js](https://github.com/ducksboard/gridster.js/issues/503))

The problem is how can i create composite widgets (meaning using the Composite design-pattern) where each widget can have sub-widgets which are also resizable/draggable (inside their own container widget)?

(have already forked the repository because i was just looking to make something similar for design application i am building, so if i can add this feature myself i could do it and create a PULL-Request)

Thanks

**Comment by troolee** [comment]
Can you give a use case? 

I'm open for contribution to gridstack. In case the changes have sense.

**Comment by foo123** [comment]
Yes sure, as mentioned there is an application creating prototype responsive web pages.

In this application i already have the responsive.css grid in place and various otgher tools. All i need now is a drag-n-drop widget lib (which i was about to make, until i found gridster and gridstack, very nice btw)

However all widgets are singular and are not composite imagine a layout where lets say the top left widget is composite (meaning it can have another layout inside this container)

This is known as composite design pattern (each widget is or can be a container as well)

This is useful for example because in various complex screens, the sidebar (with its own sub-content) can re-arrange responsively independantly of the rest page.

i definately need this and i must implement this if not already there
Hope this is useful to understand

**Comment by KrishnaPG** [comment]
I was also looking for a way of making composable widgets work, but couldn't get far (my js /css skills are not that great). Issues like https://github.com/troolee/gridstack.js/issues/102 popped and looking for a decent way out. IMO, it would be great to make this work with other UI components such as w2ui layout, grid controls etc.

**Comment by svdb** [comment]
@foo123 You have a basic page design problem that has nothing to do with gridstack (or any other grid layout system). Think out of the box.

**Comment by foo123** [comment]
@svdb  what do you mean by "*basic page design problem*"?

**Comment by radiolips** [comment]
@foo123 Could you provide some screenshots and/or a screencast? I'm unclear on your exact problem but would like to be able to be more helpful.

**Comment by foo123** [comment]
@radiolips , nevermind i have another solution without gridstack.js library (but similar functionality)

The use case is an interactive web-page-design system, where components may be composite (nested). For example a "sidebar" component which itself can contain other components which can be re-aranged indepednantly inside the container component
