### ISSUE TITLE
Tables not draggable

### ISSUE THREAD

**Issue by nWidart** [troolee/gridstack.js#122]
Hello,

I just created a new 'widget', which contains a table. 
The problem is I can't drag&drop it when selecting the table, but I can when selecting the size below it.

Better explained in video: http://quick.as/9rwspoax

Any idea why ?

Thanks

**Comment by nnikolay** [comment]
Hi, maybe the z-index?

**Comment by alangunning** [comment]
Do you have the table also inside the Div with class ".grid-stack-item-content" ?

**Comment by nWidart** [comment]
@alangunning Yes, it's in that wrapper div.

@nnikolay I tried upping the z-index, same issue.

**Comment by HMubaireek** [comment]
I'm having the same issue, any ideas?

This is my element html:

    <div class="box box-success">
      <div class="box-header with-border">
        <h3 class="box-title"> Title </h3>
        <div class="box-tools pull-right"></div>
      </div>
      <div class="box-body">
        <div id="myid1234" class="grid-stack-item-content"></div>
      </div>
    </div>

I can drag the div with this class: grid-stack-item-content, however, I can't drag from the title for example. Also, when I add another widget, they will overlap.

I tried to set handle (as:  handle: '.box' ) in gridoptions but it didn't work.

**Comment by nWidart** [comment]
I did not manage to make it work sadly. I've played with the z-index and other stuff, still no go.

**Comment by radiolips** [comment]
@nWidart Would you be able to provide a jsfiddle? I'd like to be able to see the code you're using. I have not had such a problem, but if you're still having it, I'd like to try to fix it.
