### ISSUE TITLE
Automatic height

### ISSUE THREAD

**Issue by nWidart** [troolee/gridstack.js#123]
Hello,

Is there a way to give widgets automatic heights? 
Meaning the height its content has. Instead of giving it a fixed height.

Thanks

**Comment by troolee** [comment]
Hi,

No, widgets are aligned by grid. You can make cell height smaller and update widget heights when content changes.

**Comment by nWidart** [comment]
Why not make it an option ?
You say yourself in the documentation that calculating the css multiple times will reduce page speed. So I'm not willing to use that option.

A simple option on the gridstack object would suffice... `auto_height: true`, and make it `false` by default...

**Comment by troolee** [comment]
Gridstack doesn't know about content and when it changes. But you do. You don't need to re-calculate widget all the time, just when the content changes.

**Comment by ensemblebd** [comment]
I too was looking for this, but for a different reason.

If I use an image that is wider than it is tall, I can guesstimate the height using the grid unit size. However when resizing the window down to mobile, it eventually becomes incorrect. 
The mobile size of the unit system doesn't match in this scenario, causing an overflow scroll vertically. 

Overflow visible doesn't fix this, as the items are absolutely positioned and are clipped visually anyway.

Love this plugin, but am going to have to implement a workaround no matter which grid system I choose it would seem.

**Comment by Cyantix** [comment]
I found a working solution for this:

first, you need a jQuery plugin that detects if an element has a scrollbar:
`jQuery.fn.hasScrollBar = function() {
	return this.get(0) ? this.get(0).scrollHeight > this.innerHeight() : false;
}`

now you can loop through your grid-stack-items and increase the height until the overflow:auto item has no scrollbar anymore:

`jQuery('.grid-stack-item').each(function(idx) {
			$widget = jQuery(this);
			var stop = 50;
			while ($widget.find('.grid-stack-item-content').hasScrollBar() && stop > 0) {
				grid.resize($widget, parseInt($widget.attr('data-gs-width')),  parseInt($widget.attr('data-gs-height')) + 1);
				stop = stop - 1;
			}
});`

This only works with animated: false option in gridstack.
