### ISSUE TITLE
Knockout component binding to multiple templates

### ISSUE THREAD

**Issue by DavidDury** [troolee/gridstack.js#124]
Based on the knockout example you have provided, how can I make it dynamic so that I can provide for each widget a different template to use?

If we have the array of widgets:

var widgets = [
        {x: 0, y: 0, width: 2, height: 2},
        {x: 2, y: 0, width: 4, height: 2},
        {x: 6, y: 0, width: 2, height: 4},
        {x: 1, y: 2, width: 4, height: 2}
    ];

I want to make it so that I provide the template I want the widget to use

var widgets = [
        {x: 0, y: 0, width: 2, height: 2, template: 'template-1'},
        {x: 2, y: 0, width: 4, height: 2, template: 'template-2'},
        {x: 6, y: 0, width: 2, height: 4, template: 'template-3'},
        {x: 1, y: 2, width: 4, height: 2, template: 'template-4'}
    ];

where template-1 ... template-4 are html templates.

**Comment by troolee** [comment]
You can use `template` binding for `.grid-stack-item-content` nodes
