### ISSUE TITLE
Widget resize unit - pixel by pixel

### ISSUE THREAD

**Issue by DavidDury** [troolee/gridstack.js#125]
If we have a widegt let's say width=200px and height=100px and I resize the height or width, the next available size is for example width=280px and height = 180px.

On the other hand if I shrink it the next sizes will be width=120px and height = 20px.

Is it possible to make the resize at 1 pixel? For the same sizes above it means after the resize will be width=201px and height=101px?

**Comment by troolee** [comment]
gridstack is a grid of cells. So minimum dimension is 1 cell. You can setup height of one cell in pixels https://github.com/troolee/gridstack.js#options and you can change amount of columns.

But it could cause performance issues with big grids.
