### ISSUE TITLE
Changing Column padding and resize width

### ISSUE THREAD

**Issue by qbert65536** [troolee/gridstack.js#126]
When I try to resize a cell within a row, it only allows me to resize by big jumps.

I'm looking for a config that does what cell_height does, is there a cell_width option ?

Thanks for such a great plugin!

**Comment by cfleck** [comment]
Did you find a solution for that? Cause iam running into the exact same problem.

**Comment by qbert65536** [comment]
No I haven't , I'll start digging into the code though

**Comment by qbert65536** [comment]
@cfleck ok I got it working.  Upgrade to the latest version and replace all the CSS that deals with data-gs-width percentages to the new one created by the script in the readme, and add width and 'data-gs-width' properties to your constructor.

**Comment by yulisys** [comment]
@qbert65536 Can you please provide your code snippet?

**Comment by cfleck** [comment]
i will look into that. Thanks in advance :-)

**Comment by qbert65536** [comment]
@yulisys take the SASS code from here https://github.com/troolee/gridstack.js, change to your number of columns, then remove all the mentions in gridstack.css about columns and width ( just overriding it didn't seem to work I had to actually cut out the old CSS ).

Then change your constructor to something like :

var gridOptions = {
        ...,
        width: 36,
        'data-gs-animate': true,
        'data-gs-width': 36
    };
    $('.grid-stack').gridstack(gridOptions);

That worked for me.  When I changed it to 36, I had to set the minimum width for 2 , other size one sized columns would drag around weird, I should probably file a ticket

**Comment by radiolips** [comment]
Closing because the CSS allows for this, as mentioned. Please reopen if you consider your issue not resolved. Thanks!
