### ISSUE TITLE
Gridstack with html2canvas

### ISSUE THREAD

**Issue by renebrain** [troolee/gridstack.js#127]
Hi, i am using html2canvas (0.5 alpha) for making a screenshot of my gridstack. html2canvas makes the picture in a hidden iframe. The problem with this is that, although i initialize the Gridstack in the iframe, it still looks scrambled as if it is not initialiazed. I debbuged this state, and the whole gridstack worked, moving and resizing worked (as possible it was with those 1px high elements). But it looked very scrambeled as if this thing wasn't initialized, all widget were 1px high. Is it a problem with hidden elements with gridstack or is it a problem with html2canvas?

Thank you ;)

**Comment by qbert65536** [comment]
I have this exact same problem, I thought it was something I might be doing wrong.   html2canvas doesn't always work it seems.

**Comment by derekm** [comment]
I have html2canvas with gridstack and it is working fine. I'm not using any iframes, though. Maybe you can find a way to avoid iframes.

**Comment by pySilver** [comment]
Iframe is not a problem at all. Just apply an inner div with 100% widthxheight and place your iframe inside. So while dragging or resizing you want have any problems.



Dnia 7 sie 2015 o godz. 23:28 Derek P. Moore <notifications@github.com> napisał(a):
