### ISSUE TITLE
Compatability with IE 9, IE 10 & IE11

### ISSUE THREAD

**Issue by AnshulU9** [troolee/gridstack.js#129]
Hi Troolee,

I am implementing Gridstack.js on a dashboard I am working on. It really neat. I wanted to make sure if IE 9+ is compatible with it. As of now the application doesn't work on IE 9 and above. 

Thanks 
Anshul

**Comment by renebrain** [comment]
What is your exact problem, i am also using gridstack and it works perfectly fine with IE9, IE10 and IE11?

**Comment by AnshulU9** [comment]
When i open the application (here is the link http://patient.somee.com/patient/index) in IE:
1. Application is not opening completely.
2. Drag and drop doesn't work.
3. I can't take any action on the application.

**Comment by renebrain** [comment]
I don't think it is a gridstack issue...the gridstack in your application works fine...you can still drag & drop all the items. I assume the code which is responsible to put in the content into your widgets does not work in IE...debug you code and check out whats wrong with it. I don't see any gristack related issue here.
