### ISSUE TITLE
Hide and show widget

### ISSUE THREAD

**Issue by Sophia-nguyen** [troolee/gridstack.js#130]
Hi,

I used bower to install gridstack, it just  dowload v0.2.2 not v0.2.4, and it don't support hide widget.
Could you please update to I can dowload new version with bower install?

And, I have a question, how to show widget after hide.

Thanks.

**Comment by radiolips** [comment]
The updated version is now in bower. Showing and hiding can be done using standard DOM manipulation and does not require support from gridstack. If you're having a specific problem, I'd be happy to try to help work through it with you. If that's the case, reopen, provide some code or a jsfiddle, and we'll see what we can do.
