### ISSUE TITLE
Move items between two or more grid-stack containers

### ISSUE THREAD

**Issue by nnikolay** [troolee/gridstack.js#133]
Hi, I would like to have two or more grid-stack containers and move the items (portlets) between them. How to register this containers, so the portlets can be moved from one to another container? And after that, how can I become the serialized positions for each container?

Example:
[div class="grid-stack" id="grid-nav-left"][/div]
[div class="grid-stack" id="grid-body"][/div]
[div class="grid-stack" id="grid-nav-right"][/div]

Thanks!
Nik

**Comment by nnikolay** [comment]
Hi guys, no one knows about this issue? @troolee do you know how to use it or maybe give me a tipp what to do for this feature?

Thanks
Nik

**Comment by ronvanpol** [comment]
I'm interested in thuis too. My scenario is that i want to have a toolbar from which users can drag items onto multiple gridstack. Any printers in the right direction would be appreciated.

**Comment by cmwwebfx** [comment]
Hi guys, just found this thread thanks to me ol' friend Mr.Google.
I am looking for the same thing to have 2 containers. The left container will be inactive items, the right side will be an empty container for active. I will like to drag items from the left to the right container to make the item active, and also have an option to simply drag around in that container and re-size each in the active container.

**Comment by enriquecaballero** [comment]
+1

**Comment by abologna-r7** [comment]
:+1:

**Comment by alangunning** [comment]
I just initialized two grids, rather than the random class name for
example '.grid-stack-22113'  generated by grid stack I made the class name
an option then initialized each grid with active and inactive class name....

**Comment by enriquecaballero** [comment]
Could you please elaborate, sir.

**Comment by nnikolay** [comment]
@alangunning I have trying your solution, but doesn't work for me. Do you have some sample code?

**Comment by enriquecaballero** [comment]
@alangunning Did you actually get it to work? Or were you just writing off the top of your head? Cause your solution doesn't seem to work. However, I'd love to be proved incorrect. So please, it would appreciated if you were to share with us the code you wrote that actually got it to work.

**Comment by alangunning** [comment]
Apologies, I have been very busy in work. I will try code up a demo to
share later today

**Comment by alangunning** [comment]
@enriquecaballero @nnikolay 
I have provided a rough demo of the concept for now.To save time I made my changes in Dev branch of my own fork of this repo. Will contribute back asap or feel free to re-use any of the code.
Demo can be viewed at: http://alangunning.github.io/gridstack.js/demo/multiple-grids.html

**Comment by enriquecaballero** [comment]
@alangunning Looks good! Is there a way to actually have it animate while I drag from one container to another? With placeholder, etc.

**Comment by nnikolay** [comment]
@alangunning this is great! Many thanks! Can you please take a look at the resizing of an item. For example it is not possible for me to resize the item 2, because it overlaps item 3 and item 3 don't move.

**Comment by alangunning** [comment]
@enriquecaballero I did not implement this functionality as it would require a lot of re-calculations that I did not require for my workflow. I simply allow to drag and drop a widget in order to add to another grid. You can see in my sample code that I set auto_position = true in add widget function so that will use existing gridstack core library to place the widget in any available position.

@nnikolay All active widgets are re-sizing fine in all desktop browsers I've tested. Do you mean that when you extend widget 2 that widget 3 does not move down to next row ? In my example I have limited my grids to 6 rows which is preventing this as the grid is full. If you want it to do that, you will need to remove gridstack option 'height' to remove row limit and also adjust the appropriate css accordingly.

**Comment by nnikolay** [comment]
@alangunning thanks a lot. Your suggestion fixes the issue I mean with the resizing. I have played a bit with your example, but I can not set 2-3 active grids and move items between them. Can you please make an example with 2 or more active grids, where I can move widgets between them? In my case I don't need any inactive grid, only active grids. For example I am trying to build an page builder with elements like: header, body, left and right grid. Is it possible you make a small example?
Thanks a lot!
Nik

**Comment by tnmdo** [comment]
@troolee thank you for the great plugin

@alangunning thanks for the demo, I tried a bit around based on your solution but I always got into trouble when moving an item between the grid-stacks. the item to move became invisible outside the gid-stack origin. Did I miss something?

And just in case: does anyone have a solution (or hint) for correctly auto-positioning the item automatically when moving around the item in the target grid-stack, before dropping?

**Comment by derekm** [comment]
I've moving widgets in and out of nested grids as a way of grouping widgets. We were originally going to use drag-and-drop to move widgets from parent grid to nested grids, but you end up having to chase down your nested grid's widget as it slides out of the way assuming a move. We're opting instead for a global "group widgets" mode as an alternative and distinguished UI apart from drag-and-drop move. Basically: add a group (aka, a nested grid), activate the group for adding/removing widgets, clicking widgets in the group evicts them from the group, clicking widgets outside the group moves them into group, lastly deactivate the "add/remove widgets" mode on the group.

**Comment by marshmeloo** [comment]
Hi all,
I 'm new user of the Gridstack, I have the same problem as drag and drop a widget to another grid-stack . Is there a new fix of this issue ?

**Comment by Alchnemesis** [comment]
@marshmeloo I don't think this library is maintained anymore... I would also love this functionality but, looks like it's not going to happen.

**Comment by ghominejad** [comment]
+1

**Comment by kdietrich** [comment]
This issue is currently in development. We'll try to find a solution for `v0.2.5`.

**Comment by radiolips** [comment]
This functionality will most definitely be available in v1.0. v0.2.5 is going to be smaller features and bug fixes, tightening up the library.

**Comment by troolee** [comment]
Ok folks, I've finally done this. It has *experimental* status right now and gonna be it up to 1.0.0 so use it with caution and let me know it you see any issues (with behaviour, events, etc).

It probably has issues with knockout/angular/etc so it needs to be checked.

I'm closing this issue so feel free to open new ones in case of bugs.

Next, we likely to release 0.2.5 as it is right now and all issues you find will be fixed in 0.3.0.

Cheers.

**Comment by marshmeloo** [comment]
+1

**Comment by Coopyrightdmin** [comment]
Hi, 
Could you please let us know how to enable this experimental option?
I have tested with the following option without any success: `acceptWidgets: 'grid-stack-item'`.

Actually, I cannot drag out from the grid-stack container.

By the way, thanks for your incredible work!

Cheers.

**Comment by troolee** [comment]
It should be selector `.grid-stack-item`. Please check out a demo http://troolee.github.io/gridstack.js/demo/two.html

**Comment by gjavi1** [comment]
@derekm I currently have the same issu, were you able work it out?

**Comment by griphi** [comment]
@alangunning 
I have a question about your posted demo with active and inactive widget grids.
How do you get the ID of a single widget?
I want to add content to the widgets, but the <div class"content">  tag adding the content to all widgets.

How can i manage only one widget?

Thanks

**Comment by griphi** [comment]
Is anyone here?

**Comment by dharmeshkotadiya** [comment]
Can you please any one help me on this? 
![image](https://cloud.githubusercontent.com/assets/22542405/18990080/4b7a4832-872d-11e6-9b48-18ecd6ced8f4.png)

Thanks in advance!!

**Comment by ronvanpol** [comment]
Could you possibly support drag and drop WITHOUT removing the dragged element from its original parent? In my case I want to have a sidebar that contains element that have to be cloned when dragged onto a grid. Looking at the code, the draggable is simply removed after a clone is made:

var el = $(ui.draggable).clone(false);
el.data('_gridstack_node', node);
$(ui.draggable).remove();

The call to remove the draggable should not occur in my specific case. It should only occur when dragging and dropping from one gridstack to another gridstack but not from my sidebar.

**Comment by mandys** [comment]
Did anyone find an update to this ? For layout designs once a widget is dragged, it would be helpful if it's not removed from sidebar.

**Comment by radiolips** [comment]
@mandys That feature doesn't exist yet, but I'd be happy to add it to our plans for the future.

So that I'm sure that we'll be satisfying your need - you want the ability to clone a widget rather than move a widget in particular instances. Is this correct?

**Comment by mandys** [comment]
That is correct @radiolips. I think I found that to be one of the most requested features (across some GitHub tickets). Has anyone written a patch for it yet ? Even if it's not available in the core and there is a patch it would be helpful.

**Comment by radiolips** [comment]
No one has yet written a _conditional_ patch, though a few people have made attempts at alterations.

You can see the near-term plan for gridstack [here](https://dylandreams.com/2017/04/26/gridstack-10-coming-soon/). It doesn't include this feature and I'm unsure if it'll be available for version 1.0. The changes for 1.0 are necessary for the library to mature, but I agree that there have been many requests for this cloning capability as well.

I'll take a look at reprioritizing some enhancements to see what I can do about getting this readied for you sooner.

**Comment by huangzh123** [comment]
{draggable:{ revert: true, helper: "clone" }}

JqueryUI has this function, but it doesn't work here
