### ISSUE TITLE
Add Widget

### ISSUE THREAD

**Issue by c3vo** [troolee/gridstack.js#134]
I'm trying to use the add_widget method. I noticed it says that width, height, x and y are all optional, but it seems that I have to define them in order to use the auto_position parameter. I'm defining x and y on the actual element, so there's no actual need to define it when adding the element through the method parameter. Is there any way around this?

Also, is there a way to add an animation with jQuery when adding a widget?

**Comment by KrishnaPG** [comment]
For the animation part, I was also interested (something like a flashing border around the widget for couple of seconds), but didn't get far. Here is what I did. The key is "handing the on change" event - but unfortunately on change event is raised for all widgets and not just new ones.
````
    // add onChange event listener
    $('.grid-stack').on('change', function (event, items) {
        _.each(items, function (item) {
            var attributes = item.el.data();
            // add some animation to highlight the new object
            item.el.addClass("animated swing");
            item.el.one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function () {
                item.el.removeClass("animated swing");
            });
        });
    });
````
If some one can make this work only for new objects and not all - it would be great.

**Comment by c3vo** [comment]
Thanks for the reply!

I actually found a way to do it. While it's not exactly the greatest way, it does work. The only method I've tried so far is using jQuery fadeIn.

```
var grid = $(".grid-stack").data("gridstack");
grid.add_widget(data.element, 0, 0, data.width, data.height, true)
    .hide()
    .fadeIn();
```

I had to hide the element first, in order for the animation to actually begin. Since add_widget just places it into the DOM, and is already shown. I'm assuming this could also work for adding a class that has some keyframe animation in it.

Still no answer on the optionals, though. I've put in a work around, but I'd like to know how to correctly use it, in order to achieve something a little more correct.

**Comment by abologna-r7** [comment]
I wanted to share this since I'm currently using a blur effect (JQuery UI .animate) whenever I remove a widget. Change it based on your needs:

```javascript
$({blurRadius: 0}).animate({blurRadius: 10}, {
    duration: 500,
    easing: 'swing',

    step: function() {
        $(el).css({
            "-webkit-filter": "blur("+this.blurRadius+"px)",
            "filter": "blur("+this.blurRadius+"px)"
        });
    },

    complete: function() {
        this.remove_widget(el);
        //... do more stuff
    }
});
```

**Comment by KrishnaPG** [comment]
Thanks much @abologna-r7 - it is very helpful.

**Comment by abologna-r7** [comment]
You're welcome ;)
