### ISSUE TITLE
More than 12 columns

### ISSUE THREAD

**Issue by renebrain** [troolee/gridstack.js#135]
Hey, is it somehow possible to have more than the 12 Columns for the gridstack?

**Comment by Dimosthenis** [comment]
Instructions are here: https://github.com/troolee/gridstack.js#change-grid-width

I've been trying to do the same thing, creating 20 column grid while keeping cells as absolute squares 1x1 by updating cell_height() = cell_width() on window resize and load events
Everything works if I use cells 2x2 or larger. For some reason, when I make cells smaller, they appear with width > height.

**Comment by kasikn77** [comment]
Hey, i use sass example from that link, but when I use 20 cols, there is problem with dragging. When you hold item, its farer thanit should be. Sorry for my english :)

**Comment by hiveww** [comment]
any updates here ?

**Comment by hiveww** [comment]
@troolee can we reopen this one, as this seems to be still an issue, or can you point how to make more than 12 columns 

thanks in advance

**Comment by minghz** [comment]
@hiveww  I resolved the issue a while back. You need to set your column number in both CSS and JS. Here are a few snippets of what I did

In CSS:

```
.grid-stack-item {
    $gridstack-columns: YOUR_COLUMN_WIDTH;

    @for $i from 1 through $gridstack-columns {
        &[data-gs-width='#{$i}'] { width: (100% / $gridstack-columns) * $i; }
        &[data-gs-x='#{$i}'] { left: (100% / $gridstack-columns) * $i; }
        &.grid-stack-item[data-gs-min-width='#{$i}'] { min-width: (100% / $gridstack-columns) * $i; }
        &.grid-stack-item[data-gs-max-width='#{$i}'] { max-width: (100% / $gridstack-columns) * $i; }
    }
}
```

In JS:
```
//grid definition
  var options = {
      cellHeight: 500,
      cellWidth: 500,
      verticalMargin: 0,
      height: 0,
      width: YOUR_COLUMN_WIDTH,
      staticGrid: true,
      disableResize: true
  };
  $('.grid-stack').gridstack(options);
```

I hope that makes sense

**Comment by kasikn77** [comment]
@minghz I also use sass in my project but it doesnt work. The 'shadow' while you dragging tile is above the real place. That doesnt solve problem.

**Comment by kasikn77** [comment]
Hello there. Problem is also when we set up columns to 12 but height is defined also. My gridstack options:
`var options = {
            width: 12,
            height: 8,
            float: false,
            acceptWidgets: '.grid-stack-item',
            disableResize: true,
            animate: true,
            draggable:{
                enabled: true
            }
        };`

**Comment by randellhodges** [comment]
I have the same issue with widths larger than 12. If I use 24 in both the sass and inside the javascript, I have to drag things approximately 50% more to see the dotted outline move to the correct spot.

**Comment by dfenerski** [comment]
this is still an issue.

**Comment by adumesny** [comment]
make sure to read https://github.com/gridstack/gridstack.js#change-grid-columns and next section.
I have a 30 column demo (https://github.com/gridstack/gridstack.js/blob/develop/spec/e2e/html/810-many-columns.html) which last time I checked was fine

see #810 (which apparently might still brake ~100 columns ?

**Comment by dfenerski** [comment]
you're right, i was just reading the documentation.

**Comment by xresch** [comment]
Here a SASS code for 64 columns, sorted by CSS class and rounded percentage numbers to 2 decimal places.
Might be useful for someone else as well.

```sass
.grid-stack > .grid-stack-item {

    $gridstack-columns: 64;

    @for $i from 1 through $gridstack-columns {
        &[data-gs-width='#{$i}'] { width: round((100% / $gridstack-columns)*100)/100 * $i; }
    }
    
    @for $i from 1 through $gridstack-columns {
      &[data-gs-x='#{$i}'] { left: round((100% / $gridstack-columns)*100)/100 * $i; }
    }
    
    @for $i from 1 through $gridstack-columns {
      &[data-gs-min-width='#{$i}'] { min-width: round((100% / $gridstack-columns)*100)/100 * $i; }
    }
    
    @for $i from 1 through $gridstack-columns {
      &[data-gs-max-width='#{$i}'] { max-width: round((100% / $gridstack-columns)*100)/100 * $i; }
    }
    
}
```

**Comment by adumesny** [comment]
fixed in 2.x with #1299

**Comment by xresch** [comment]
@adumesny yeah I didn't find a 100% perfect solution with pure Sass limiting the digits without using some command line params(I only use some online sass tools). The result works fine with me and the permille deviations are not visible on the UI.

I updated my comment to include a version with full precision.

**Comment by adumesny** [comment]
@xresch just round after you multiply by $i so the error isn't compounded...

**Comment by xresch** [comment]
@adumesny ah now I got you, thank you, fixed and updated in the comment.
