### ISSUE TITLE
rtl languages issue

### ISSUE THREAD

**Issue by amreissa** [troolee/gridstack.js#138]
i want to use this widget with rtl direction.. can i find the solution

**Comment by troolee** [comment]
What problem with rtl direction? Do you mean that you need to have (0, 0) coordinate to be at top right corner?

**Comment by amreissa** [comment]
when i change the page direction to rtl
i found 2 problems 
- when i drag an item, it appears in another place "solved"
- when i resize item, the placeholder appears in far place

**Comment by svdb** [comment]
Letting the grid use RTL is irrelevant. Only the content of your widgets need to be RTL.
On the gridstack DIV set CSS to be direction: ltr; while the rest of you page may be rtl.
Then on each widget content box set the CSS to be  direction: rtl;

**Comment by troolee** [comment]
It's fixed now
