### ISSUE TITLE
Disable ediable mode and without jQuery UI

### ISSUE THREAD

**Issue by l2aelba** [troolee/gridstack.js#144]
If we have 2 modes like **admin mode** and **user mode**

**Admin mode** would be edaitable, but **user mode** is not.

**I do like :**
```javascript
// Run
.gridstack();

// Disable
.batch_update();
.commit();
.disable();
```

**Ask :**

- How can I run `gridstack` without ***editable mode*** from start ?
- Prevent using jQuery U (because that file size is 100kb+) ?

That I want just "disable" first, then "enable" it

Any idea ? Thanks so much

**Comment by troolee** [comment]
I've added an option `static_grid`. Please check the latest development version.
