### ISSUE TITLE
Can I set width of grids accrding device portrait and landscape 

### ISSUE THREAD

**Issue by vikujangid** [troolee/gridstack.js#145]
Gridstack.js is great. I want to customize it.

I set width to 4 instead of 12 (number of columns) 
So in my iPod
Currently it showing 1 column in portrait and 4 column in landscape mode

But I want 2 column in portrait and 3 column in landscape mode and in PC ( more than 1080px) width always 4 columns.

Please help me 
Thank you

**Comment by papalaza** [comment]
You can achieve this via the changes I made here:
https://github.com/troolee/gridstack.js/pull/140/files

**Comment by vikujangid** [comment]
@papalaza  thanks for reply. Could you please explain me here because there are lot of scripts i am new in gridstack so I don't know how to I made changes

**Comment by radiolips** [comment]
@vikujangid you can! gridstack does not handle responsiveness automatically, however it does allow for a different number of columns, and you can simply check width and set number of columns based on width. If you need it to update on-the-fly, please try the `setGridSize` method.
