### ISSUE TITLE
Gridstack on Maps background

### ISSUE THREAD

**Issue by ubinam** [troolee/gridstack.js#146]
We are developing a project for which we would like to place the gridstack layout on top of a map background based on Leaflet keeping both functionalities. 
This is not possible right now. Would you help us making it real?

**Comment by troolee** [comment]
Can you please provide a sample page to see what do you mean?

**Comment by ubinam** [comment]
Please find below a view simulation of what I would like to achieve. The background would be a leaflet based map UI plus some menu bars and other controls. 
In the foreground i would like to open up a responsive grid depending on the menu selections. The map should keep its zooming/panning/touch functionalities and the grid should be oriented around the visible screen, not any map points. I hope that makes it a bit clearer.
![gridstackleaflet](https://cloud.githubusercontent.com/assets/12475826/7902612/2d7bbe7c-07bf-11e5-9cfe-e131b6178208.png)

**Comment by troolee** [comment]
What problems do you have with gridstack? Do you have a sample I can try?
