### ISSUE TITLE
Issue in resizing widgets

### ISSUE THREAD

**Issue by PhilipAnthonyMurray** [troolee/gridstack.js#153]
I have a grid where widgets are already specified in the HTML and when I run the project the resizing does not work, the resize handle does appear when hovering over the element but will not resize.  The drag and drop of the widget does work though.

Any idea why this is happening?

Here is the HTML within the page

    <div id="Y2415496486890" class="grid-stack grid-root grid-stack-1" ondragover="event.preventDefault()" data-gs-width="4"
            data-section-conditional="True" data-section-tablename="SR01" style="height:80px;">
        <div id="W5965753102947" class="grid-stack-placeholder grid-stack-item" style="display:none;">
            <div class="placeholder-content" style="display:none;"></div>
        </div>
        <div class="separator" style="width:25%;"></div>
        <div class="separator" style="width:25%;"></div>
        <div class="separator" style="width:25%;"></div>
        <div class="separator" style="width:25%;"></div>
        <div class="title grid-stack-item ui-draggable ui-resizable ui-resizable-autohide ui-draggable-disabled ui-resizable-disabled"
                data-gs-no-resize="true" data-gs-no-move="true" data-gs-locked="yes" data-gs-x="0" data-gs-y="0" data-gs-width="4"
                data-gs-height="1">
            <h4>Request</h4>
            <input id="A6159667670779" class="settings modalPopup-trigger" type="image" alt="" data-modal="modalPopup-section" />
            <div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index:90;display:none;">
            </div>
        </div>
        <div id="M5908074112739"
                class="ui-draggable ui-draggable-handle grid-stack-four-item grid-stack-item ui-resizable ui-resizable-autohide"
                data-gs-width="1" data-gs-locked="yes" data-gs-x="0" data-gs-y="1" data-gs-height="1" data-gs-max-height="10">

            <div id="B8417678337690" class="grid-stack-item-content element-wrapper ui-draggable-handle">

                <div id="T3722486096114" class="element-setting modalPopup-trigger" data-modal="modalPopup-prompt"></div>

                <label id="J5253020243820_Label" class="inputElement" data-field-conditional="" data-field-defaultvalue=""
                        data-field-displaysize="" data-field-fieldname="" data-field-fieldsize="" data-field-fieldtype="" data-field-iskey=""
                        data-field-isreadonly="" data-field-isrequired="" data-field-listdisplayvalue="" data-field-listfilter=""
                        data-field-listtable="" data-field-listvaluefield="" data-field-rangelowervalue="" data-field-rangeuppervalue="">
                    Report
                    Key
                </label>

            </div>

            <div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="display:none;z-index:90;">

            </div>
        </div>

    </div>

And this javascript is fired when the document loads

$( document ).ready(function() {   
	$('.grid-stack').each(function() {
	
		var options = {
			cell_height: 60,
			vertical_margin: 10,
			always_show_resize_handle: false
		};
		$(this).gridstack(options);
	});
});

If I create another widget in the same grid the resize works. Here is the HTML for that widget.

    <div class="ui-draggable ui-draggable-handle grid-stack-four-item grid-stack-item ui-resizable ui-resizable-autohide"
    id="F1433242509691" data-gs-width="1" data-gs-x="1" data-gs-height="1" data-gs-y="2" data-gs-locked="yes"
    data-gs-max-height="10">
	
      <div class="grid-stack-item-content element-wrapper ui-draggable-handle" id="N1433242509691">
	  
        <div class="element-setting modalPopup-trigger" id="M1433242509691" data-modal="modalPopup-prompt"></div>
		
        <label class="inputElement" id="M1433242509690" data-field-rangeuppervalue="0" data-field-rangelowervalue="0"
        data-field-listvaluefield="" data-field-listtable="" data-field-listfilter="" data-field-listdisplayvalue=""
        data-field-isrequired="false" data-field-isreadonly="false" data-field-iskey="false" data-field-fieldtype=""
        data-field-fieldsize="0" data-field-fieldname="" data-field-displaysize="0" data-field-defaultvalue=""
        data-field-conditional="">New label</label>
		
      </div>
	  
      <div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="display: none; z-index: 90;">
	  
      </div>
	  
    </div>

**Comment by alangunning** [comment]
You have explicitly specified in the HTML to lock the widgets....data-gs-no-resize="true" data-gs-no-move="true" data-gs-locked="yes"

Set them to false or omit them from the HTML

**Comment by PhilipAnthonyMurray** [comment]
Hi Alan,

That's on one of the elements only. The title class element is used as a label widget at the top of the gridstack which I don't want the user to move or resize.

The sibling elements do not have those attributes. Look at the sibling element with an ID of M5908074112739

Thanks

Phil

**Comment by PhilipAnthonyMurray** [comment]
OK, I have just figured it out. I was explicity adding the div with the ui-resizable-handle class in the HTML and when the widget gets registered in gridstack it creates another instance. Looking at the developer tools in the browser I could see the two instances. I removed my explict instance from the HTML and reran to page and the resize is now working.

                            <div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="display:none;z-index:90;" />
                            <div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="display:none;z-index:90;" />

**Comment by sophanox** [comment]
Ah that has worked! Thanks a lot :)
