### ISSUE TITLE
'change' event fires when nothing changes, items is empty

### ISSUE THREAD

**Issue by piwi91** [troolee/gridstack.js#157]
When dragging a widget a bit (without moving the position), the 'change' event is fired without the `items` variable set.
When dragging a widget to another position, the `items` variable is set.

My implementation:

```javascript
this._on('.grid-stack', {
    'change': function (event, items) {
        $(document).ajaxProtocol("call", {
            url: Routing.generate('my_route'),
            data: {'items': this._convertItems(items)},
            type: 'POST',
            beforeSendCallback: null,
            readyCallback: null
        });
    }
})
```

**Comment by FredFaust** [comment]
I get this behavior too. The `change` event is fired even if the widget is being dragged around (not pushing any other widgets) and finally stop dragging it at its original position.

**Comment by troolee** [comment]
It's fixed now. Please check it out.
