### ISSUE TITLE
Issue moving widgets to positions not besides already created widgets

### ISSUE THREAD

**Issue by Nyrris** [troolee/gridstack.js#160]
The issue is when I am trying to move a widget to an other row, lets say on row below which contains widget(s) on the left side. The widget can only be placed between or beside widgets on the grid, what it should be is that the widget can be placed on any location on the grid, not depending on other widgets. Hope my explanation is a bit clear, but maybe an image can explain it better:

I have attached a screenshot of the demo page where I am trying to move "widget 4" to right corner of the second row, which is not possible.

![gridstack](https://cloud.githubusercontent.com/assets/6594063/8057402/449da2ca-0eb1-11e5-9780-d07e6d60f26e.png)

**Comment by jamessanderlin** [comment]
If you set the "float" property to true when initializing the grid, you will be able to do what you want to do.

**Comment by Nyrris** [comment]
Thanks that did it, now its working how I would like it to be.
