### ISSUE TITLE
Return changed widgets instead of all widgets after a 'change' event

### ISSUE THREAD

**Issue by FredFaust** [troolee/gridstack.js#164]
I'm talking about this : https://github.com/troolee/gridstack.js#onchangeitems

Why would we need the information about items that didn't change position or size ?

Wouldn't it be more practical to return the items that changed and not all of the items?

**Comment by troolee** [comment]
Hi,

Right now `onchange` event contains a list of items that were probably changed during the movement. I think I could change this in future and return only those items that were actually change their parameters.

**Comment by FredFaust** [comment]
Hello @troolee , what do you mean by 'probably changed' ?

I think it would be great to have only the items that their parameters changed. I checked the code a bit and I saw some code about nodes being `dirty` or something like that. What is the purpose of that ?

**Comment by troolee** [comment]
During a movement of a node other items could be affected (change their position). I mark these nodes as `dirty` and pass them to `onchange`.

**Comment by FredFaust** [comment]
The logic of `dirty` nodes seems good. The only thing left to do would be to make nodes `dirty` only if they actually changed position or size.

Good job on the awesome library by the way!

**Comment by troolee** [comment]
I will.

Thank you!

**Comment by cvillemure** [comment]
The `dirty` concept seems a bit hard to implement / use.  

If I have a one column layout with two widget of the same size and swap them.  Without an ID (which the library does not support) how would you represent that in the resulting `items` ?

Also, are new and removed nodes also considered `dirty`?  I would assume that the `onchange` event does not only trigger for `resize` / `move` but also for `add` and `remove` (#167).

I would suggest to continue sending all of the grid's items and let the user handle the changes as he needs.

Unless I'm wrong in my understanding of the library ... correct me if I'm wrong.

**Comment by radiolips** [comment]
In the case that you mention, if both widgets have changed position, then *both* will be returned as changed. As @troolee fixed this in #167, I'm closing the ticket. It does return only changed items, but that's how it is designed to work.
