### ISSUE TITLE
onchange(items) event not fired

### ISSUE THREAD

**Issue by FredFaust** [troolee/gridstack.js#167]
The event is not fired when calling remove_widget with floating disabled. Let's say I have multiple widgets all in one column and I call remove_widget for the top widget. Since floating is disabled, all the widgets are pushed to the top, their attributes are changed (data-gs-x and data-gs-y) but the event about widgets changing position isn't called.

I think it shouldn't be hard/long to fix but I don't understand the code well enough to do the change myself.

Thank you

**Comment by mgwidmann** [comment]
:+1: I'm not seeing the `change` event fired on add or remove. Either it should do a `self.container.trigger('change', [self.grid.get_dirty_nodes()]);` or trigger an add/remove specific event.

**Comment by piwi91** [comment]
:+1: I miss this too

**Comment by piwi91** [comment]
@troolee  is there a workaround for this issue?
