### ISSUE TITLE
max-height/width leaves reserved place around

### ISSUE THREAD

**Issue by Spajt** [troolee/gridstack.js#168]
Hi,
I wish to work with this plugin, but I cannot allow it to make "transparent holes".
Look at this screenshot
![floating-grid-demo](https://cloud.githubusercontent.com/assets/7771793/8183842/07ec9b08-143b-11e5-9c89-a952b43a4c13.PNG)
the coloured container have height of one box, but it reseves as much as I wish. It shouldn't. 
Do you have some tricky solution?

**Comment by troolee** [comment]
HI,

I'm not sure I've understood you properly. Could you explain?

**Comment by Spajt** [comment]
Look. Even if I set data-gs-max-height to 1, user is able to set it as high as he wish. It blocks only coloured part, but doesn't prevent locking grid fields. So you cannot set other element under that high one and you cannot see why the block is moved nearby

**Comment by radiolips** [comment]
Please provide a jsfiddle and reopen if your'e still having an issue.
