### ISSUE TITLE
$gridstackItem.data('gs-x') doesn't have the same values as $gridstackItem.attr('data-gs-x') after change event

### ISSUE THREAD

**Issue by FredFaust** [troolee/gridstack.js#169]
I used the change event and bind it to a function for updating my Backbone.Model's position. I didn't use the given items parameters returned by the change event but directly selected through $('.grid-stack-item'). I get all the items and I want to take the new updated values (that are the correct values when I look inside the DOM).
I was using the jQuery function .data() to get the values for gs-x and gs-y but those weren't updated. I needed to use the .attr() function to have the values with the new position.

I'm not sure this is bug but it might have to do with how gridstack changes the data attributes of all the grid-stack-item.

**Comment by pySilver** [comment]
@FredFaust from what I remember, jQuery.data() has some internal cache while attr not.

**Comment by derekm** [comment]
This is a jQuery issue. jQuery.data() is older than HTML5 datasets. And jQuery.data() only loads initial values from the HTML5 dataset, it does not keep in sync with changes to the dataset. You need to use the underlying wrapped DOM object's dataset or use jQuery.attr() to access 'data-gs-x' and friends.

As such, this is not a bug in gridstack.js.
