### ISSUE TITLE
Default view

### ISSUE THREAD

**Issue by nousacademy** [troolee/gridstack.js#171]
I'm loading a bunch of objects from my database, is there a way to get a default view for everything thats loaded?
I get this error : 
                            Cannot set property '_id' of undefined
This is the code I was testing out:
                                           
               var serialization = [];
                serialization = GridStackUI.Utils.sort(serialization);
                var grid = $('.grid-stack').data('gridstack');
                grid.remove_all();

               
                    grid.add_widget($('<div class="dynamic"><div class="grid-stack-item-content">'+ itemInMyForLoop +'<div/>'));

**Comment by luckylooke** [comment]
@nousacademy how did you solve the issue? I came to same error calling `gridstack.destroy(false)` which inside calls removeAll() method.. getting the error on android tablet Huawei M2-801W android 5.1.1, it is the oldest device I am using for tests. All newer devices are OK
