### ISSUE TITLE
Closure compiler complains about reserved word float

### ISSUE THREAD

**Issue by bardware** [troolee/gridstack.js#172]
Hi,
I wanted to include `gridstack.js` into my build process using google's closure compiler.
`gridstack.js` does not compile because it uses a variable called `float` as an argument to a function. 
```
    var GridStackEngine = function (width, onchange, float, height, items) {
        this.width = width;
        this.float = float || false;
```
'float' for whatever reasons is regarded a reserved word in JavaScript.
Closure compiler allows to switch to a strict mode that does not stumble upon supposed reserved words but comes up with ther issues.

Thanks for your efforts, keep up the good work.

**Comment by troolee** [comment]
Fixed.
