### ISSUE TITLE
Static widget without jQuery UI

### ISSUE THREAD

**Issue by pySilver** [troolee/gridstack.js#173]
Hello,

Thanks for the great lib! I have a question regarging static mode. My case is the following:
User creates widgets in "admin" mode where he is able to move things around, configure content etc. afterwards we want to give him ability to export short code to include created widget to his website.

And here is the question – do we need a gridstack to display such static widget or we can just use it's CSS & serialized data attributes?

**Comment by troolee** [comment]
It's done now.

**Comment by pySilver** [comment]
good job!
