### ISSUE TITLE
Massive slowdown for larger grids: _fix_collisions and move_node executed too many times

### ISSUE THREAD

**Issue by jamessanderlin** [troolee/gridstack.js#177]
I'm working with grids that could potentially have 50+ widgets in them. When I tested with large grids, my page got really slow and started getting really heavy on my CPU. The problem is that the _fix_collisions and move_node functions get executed a LOT of times. It seems to increase exponentially as the number of items in the grid increases (I'm testing a grid with 125 widgets, and _fix_collisions is being called 700,000 times just to load the page).
I wanted to make sure it wasn't an issue with something I was doing, so I counted the number of times it is executed in the gridstack demo here: http://troolee.github.io/gridstack.js/, and it was still executing _fix_collisions a lot more than I would expect. After moving widget "1" from the top left to the bottom right of the grid, _fix_collisions had been executed 3125 times.
Do you have any thoughts on how the algorithm could be changed so that _fix_collisions is executed a whole lot less, and doesn't increase so dramatically as the number of widgets increases? Or is there no  way around executing it so many times?

**Comment by troolee** [comment]
This is one of priority issues to fix.

**Comment by jamessanderlin** [comment]
Great! Thanks for all the work you do on this plugin!

**Comment by mtyeh411** [comment]
:+1:

**Comment by mgwidmann** [comment]
:+1: need this fixed asap

**Comment by andreibondarev** [comment]
:thum
