### ISSUE TITLE
Invalid property values in gridstack.min.css 

### ISSUE THREAD

**Issue by lorenzobenvenuti** [troolee/gridstack.js#179]
Hi,

I'm not familiar with javascript "build" methods so I don't know how the gridstack.min.css file is generated (and if it's a good practice to commit in the "dist" folder); anyway there are some invalid property values for the selector:

.grid-stack.grid-stack-animate .grid-stack-item.ui-draggable-dragging, .grid-stack.grid-stack-animate .grid-stack-item.ui-resizable-resizing, .grid-stack.grid-stack-animate .grid-stack-item.grid-stack-placeholder

Transition values are set to "0", not "0s", and this brings to a really slow dragging performance because transitions are applied also to "ui-draggable-dragging" elements. 

Thank you,

lorenzo

**Comment by troolee** [comment]
Hi,

Which browser do you use? I don't really see any differences in Safari when using minified and source CSS files.

P.S. I need `dist` directory to be in the repo for cdnjs CDN.

**Comment by lorenzobenvenuti** [comment]
I'm using the latest version Chrome.
About the "dist" folder: I didn't mean to criticize how you organized the code! I just wanted to point out that I didn't open a pull request because I guess the minified css is generated automatically; in other words, I guess the problem is not in the source code but in the "minification" process. Sorry if I sounded rude.

Thank you,

lorenzo

**Comment by troolee** [comment]
Hi Lorenzo,

Don't be sorry, it's ok. The question was totally fine...

**Comment by radiolips** [comment]
@lorenzobenvenuti Please provide more info and reopen this ticket if you're still having an issue. I'm also able to run this properly on safari (many versions, computers, iOS->iPad and iPhone).
