### ISSUE TITLE
Gridstack undefined when calling $(".grid-stack").data("gridstack") in global context

### ISSUE THREAD

**Issue by applecrusher** [troolee/gridstack.js#182]
Hello, 

I don't know whether I need to define grid within the original function it was created, but I can't seem to add stuff dynamically because when I try to call gridstack, the variable is undefined. How do I call gridstack in the context I want to below? Thank you for your help in advance.

    $("#button").click(function(){
  
     //var el ='<div class="grid-stack-item-content" />Test<div/>';
     var grid = $(".grid-stack").data("gridstack");
     alert(grid); //This is undefined
  
     });

      $(function () {
       var options = {
           cell_height: 80,
           vertical_margin: 10
       };
     
       $('.grid-stack').gridstack(options);

      });

**Comment by troolee** [comment]
You need to check your code. It's working fine. Check this demo http://troolee.github.io/gridstack.js/demo/serialization.html
