### ISSUE TITLE
Possible to add more than 1 breakpoint?

### ISSUE THREAD

**Issue by JohnBlazek** [troolee/gridstack.js#183]
Gridstack is great and is a valuable library first off...

That said would love to know if there is a way to recalculate the grid to break at specific (bootstrap) breakpoints, but maintain order.  Currently at 768+ I have a 3 column grid, but would ideally like to have a  2 column grid from 768 to 992, then at 992, it breaks to 3 columns.

Is there an API method, or hack that I can do to achieve this functionality?

**Comment by pySilver** [comment]
@troolee correct me if I'm wrong but this is something planned in the upcoming release?

@JohnBlazek for now I think the only way is to edit generated css file so you can define your own breakpoint (well single one that says when it's time to go single column mode)

**Comment by JohnBlazek** [comment]
Great, thanks for the info @pySilver. Any insight into the next release date, love to recommend this library for future use...

**Comment by palpatine1991** [comment]
It would be also great to be able to specify the order of widgets in 1-column view.

**Comment by pepf** [comment]
+1

**Comment by radiolips** [comment]
I don't believe there are plans for this to be part of gridstack's core, but as @pySilver mentioned (thanks!), it's perfectly acceptable to modify the CSS to attain this result.
