### ISSUE TITLE
Size priority, smaller widgets always above smaller widgets

### ISSUE THREAD

**Issue by jovanni-hernandez** [troolee/gridstack.js#185]
Hi, I'd like to request a new feature/enhacement to the add_widget method. Specificaly, the enhancement is to the auto selection of columns/widths for new widgets. If new widgets are added to a grid that has a larger, full spanning widget already added, the smaller widgets should be added above the full spanning widget to enhance the aesthetics of the grid, regardless of the order to which they were added to the grid.

For example, if on a 3-width grid I add the following widgets
add_widget(el, 0, 0, 3, 1, true)
add_widget(el, 0, 0, 1, 1, true)
add_widget(el, 0, 0, 2, 1, true)

The layout would be the two smaller 1x1 and 2x1 widgets on row 1. The 3x1 widget would be on row 2. Instead, the current implementation puts the 3x1 widget on row 1, since it was added to the grid first. Row 2, would have the 1x1 and 2x1 widgets on row 2, since they were called after.

**Comment by radiolips** [comment]
I'm closing this issue because proper usage should enable this sort of functionality if you'd like. If you need to, please reopen this ticket - but in that case, provide a jsfiddle providing some more information.
