### ISSUE TITLE
Collision Response Enhancement

### ISSUE THREAD

**Issue by jovanni-hernandez** [troolee/gridstack.js#186]
When two widgets are added to the same location on the grid and create a collision, the widget that was originally in that location is bumped down one row, with the new widget taking that spot. The old widget is bumped down to the next row, even if there is a space large enough for the new widget on the same row, next to the original row.

Instead, it would be more aesthetically pleasing if the new widget was added to next available location. Thus, if a collision is created, the widget being added is added to the next available location, whether that be next to the original widget, or on the next row. Since I can see use-cases for the existing collision handling, it may be best to add this as an option during grid initialisation.

**Comment by ryanshawty** [comment]
```add_widget(el, x, y, width, height, auto_position)``` If you set ```auto_position=true``` I'm believe that will do what you are looking for.

**Comment by radiolips** [comment]
@ryanshawty is correct. The updated method is `addWidget`, but passing `autoPosition`=true will, in fact, place the widget in the next available location.
