### ISSUE TITLE
Grid width not respected

### ISSUE THREAD

**Issue by rlambrechts** [troolee/gridstack.js#196]
The grid width isn't respected. It defaults to 12.

Example at: https://storage.googleapis.com/translucid-bucket/data/demo/two.html

**Comment by h-nazzal** [comment]
well your problem is that you have not edited the css (sass) files and made the changes you want 

in order for you to obtain the results your looking for you have to edit the sass varaible `@gridstack-columns` to be 20 ... 

try that and tell us what happens ... i believe that spreading the columns structure over css and javascript is another problem that needs to be addressed ...

**Comment by rlambrechts** [comment]
I've added:
```
<style type="text/css">
        #grid1 {
            background: lightgoldenrodyellow;
			width: 600px;
			height:400px;
        }

        .grid-stack-item-content {
            color: #2c3e50;
            text-align: center;
            background-color: #18bc9c;
        }
		
		.grid-stack-item {
			$gridstack-columns: 20;
			@for $i from 1 through $gridstack-columns {
				&[data-gs-width='#{$i}'] { width: (100% / $gridstack-columns) * $i; }
				&[data-gs-x='#{$i}'] { left: (100% / $gridstack-columns) * $i; }
				&.grid-stack-item[data-gs-min-width='#{$i}'] { min-width: (100% / $gridstack-columns) * $i; }
				&.grid-stack-item[data-gs-max-width='#{$i}'] { max-width: (100% / $gridstack-columns) * $i; }
			}
		}

    </style>
```

however no result.

**Comment by h-nazzal** [comment]
i tested it out and it is working .. 
it seems that you're doing it wrong ... 
where do you have that peace of code above .. you know that sass has to be compiled ?!

**Comment by rlambrechts** [comment]
Thanks for the help, I think I'll just stick with the gridster then.

**Comment by troolee** [comment]
Please check this section https://github.com/troolee/gridstack.js#extra-css

You can include pre-made CSS with different columns setup.

Here is a sample http://troolee.github.io/gridstack.js/demo/two.html
