### ISSUE TITLE
could you please allow us to hook on some of the events? 

### ISSUE THREAD

**Issue by r4ccoon** [troolee/gridstack.js#199]
hi, could you please allow us to hook on some of the events?

the events that I need to hook on are:
onStartMove,  onFinishDrop and onMove

After initializing, I want to be able to assign a callback function to these events.
because you are using jquery.ui for the dragging function, I think the assigning code should look similar with how jquery.ui assigning callback to its events.

for example:
`$gs.gridstack(options);`
```
$gs.on('onMove', function (e, node) {
  console.log(node.x + " ++ " + node.y);
});
```

**Comment by h-nazzal** [comment]
+1 nice idea ...

**Comment by derekm** [comment]
You need to use the Draggable and Resizable events. They are dragstart, dragstop, drag, resizestart, resizestop, and resize.

You may encounter order-of-execution problems with these events, due to how they are currently employed gridstack. I have a pull-request pending where I've fixed the order-of-execution problems.

**Comment by derekm** [comment]
Also, you will need to attach your event listeners to the `grid-stack-item`s in your grid, probably as delegated listeners on your parent `grid-stack` div.

**Comment by radiolips** [comment]
There is access to the equivalent of these functions, as @derekm mentioned. If you're having continued issue, please reopen, but this appears resolved.

**Comment by r4ccoon** [comment]
Hi, it's me again, 
sorry to comment on a closed issue.
within this new version, I was trying to attach a listener for a drag stop event but couldn't manage to do it. the event doesn't get executed. It's the syntax that i need to know. I tried to do it like the one in jq-ui example but couldn't work either.  

```
var options = {
            cellHeight: 340,
            verticalMargin: 10,
            resizable: false,
            draggable: {
                start: function (e, node) {
                    var curNode = {};
                    curNode.x = node.x;
                    curNode.y = node.y;
                },
                stop: function (e, node) {
                    var o = $(node.el);
                    //do stuff
                }
            }
        };

        var $gs = $('#gs-element');
        $gs.gridstack(options);
```
maybe someone can give us a snippet on how to attach listener on these events? particularly the drag stop event.  and maybe later we can put this snippet into README.MD.
