### ISSUE TITLE
gridstack alignment problem

### ISSUE THREAD

**Issue by adeiry** [troolee/gridstack.js#201]
I have a problem with gridstack item alignment, they don't look in the same line like the demo shows.
I use bootstrap with sb admin 1.0.3
Please help me with the issue.
![gridstack](https://cloud.githubusercontent.com/assets/9880387/9135680/a5f151a8-3d18-11e5-8911-bde8c3447e06.PNG)

**Comment by h-nazzal** [comment]
set up a demo at jsfiddle or codepen
