### ISSUE TITLE
Не хватает события "Finish"

### ISSUE THREAD

**Issue by kovalenkos** [troolee/gridstack.js#205]
---english-----

Very cool plugin, but I can not find the finish of the event its activities, something like
$ (this.getGrid ()). on ('finish', function (event) {
alert ('finish');
});

that after drawing sizes run following logic.
-----russian----

Очень классный плагин, но вот не могу найти события окончания его деятельности, что то типа
$(this.getGrid()).on('finish', function (event) {
            alert('finish');
        });

чтобы после отрисовки размеров запускать следующую логику.

**Comment by mgwidmann** [comment]
I believe doing `$('#my-gridstack').gridstack()` sets up the grid synchronously. Not 100% sure, but I think after that line, the grid is done.

**Comment by troolee** [comment]
Yes, `$('#my-gridstack').gridstack()` is synchronous method so you can do you logic right after the call
