### ISSUE TITLE
Prevent widget click event after drag and resize

### ISSUE THREAD

**Issue by deechicago** [troolee/gridstack.js#207]
I create click event to each widget but after drag or resize, the click event is fired. How can I prevent click event from dragging and resizing?
Thanks.

**Comment by pySilver** [comment]
hm, I belive this is not related to lib at all. Mute your event while drag/resize start and reenable on stop.

**Comment by deechicago** [comment]
Thank you for reply.
I understand. I tried to call eventPreventDefault() on drag/resize start but after stop, click() is still fired...

**Comment by pySilver** [comment]
eventPreventDefault has nothing to do with that. you need to remove and reattach event (or try to handle this in event function, I belive jQ UI offers is_dragging / is_resizing events)

**Comment by h-nazzal** [comment]
try `return false;` to stop propagation and event bubbling as well as preventing the default behavior.

**Comment by deechicago** [comment]
Thank you guys. 
I solved this by add/remove click event listener on drag start/stop. Maybe adding a internal "click" event is good?

**Comment by h-nazzal** [comment]
i odnt think that would be a good idea.. ux wise as the user dont usually expect dragggable objects to be clickable as well .. it's quite confusing.
