### ISSUE TITLE
Buttons Clickable Within Widget?

### ISSUE THREAD

**Issue by applecrusher** [troolee/gridstack.js#208]
Is it possible to have a checkbox clicked from within a widget? If so, how could this be done?

**Comment by h-nazzal** [comment]
yes it is possible...  just put the button/check-box inside the widget!!

**Comment by janyksteenbeek** [comment]
You can put in any HTML element that you can imagine. An image, a checkbox, an input field. Everything! :smile:

**Comment by applecrusher** [comment]
In Chrome 44, this doesn't seem to work for me. I created a table in HTML and I dynamically inserted this as a widget. One of the columns had a checkbox. When I try to click on the checkbox nothing happens because it thinks I clicking on the grid.

**Comment by pySilver** [comment]
Setup a demo (codepen or whatever)



Dnia 12 sie 2015 o godz. 17:15 applecrusher <notifications@github.com> napisał(a):

**Comment by troolee** [comment]
It should work. It could be jQuery UI problem with your setup
