### ISSUE TITLE
z-index of .grid-stack-item-content conflicts with application designs

### ISSUE THREAD

**Issue by derekm** [troolee/gridstack.js#213]
I'm designing a grid with nested grids as containers. In order to move widgets in and out of nested grids I'm developing an "add/evict" UI mode for the editing of nested grids.

The z-index of .grid-stack-item-content is interfering with my ability to highlight the widgets of other nested grids as movable/relocatable:
![thrive - dashboard - mozilla firefox_034](https://cloud.githubusercontent.com/assets/379469/9343322/e3d4172e-45c6-11e5-95de-16f065b5e9db.png)

If I comment-out .grid-stack-item-content's z-index rule, then I get the desired look:
![thrive - dashboard - mozilla firefox_035](https://cloud.githubusercontent.com/assets/379469/9343347/f93eda72-45c6-11e5-9a58-c3a5306d3827.png)

This "z-index: 0 !important" rule also inhibits Intro.js' ability to point at and highlight an element in the grid item's inner contents for delivering help instructions to the user.

Why is this z-index rule in place? It looks like I can run just fine without it... But am I missing something?

**Comment by mmustala** [comment]
This same "z-index: 0 !important" rule is also disabling any modal windows that should open to the screen. Removing the z-index rule solves the issue.

The good thing is that now I really understand how z-index works. http://philipwalton.com/articles/what-no-one-told-you-about-z-index/ helped me to figure out why my modal was not on top of the screen.

**Comment by radiolips** [comment]
I'm able to use modals and etc. Could you provide a jsfiddle? I'm going to close this ticket, but if you're still having an issue, please provide the fiddle and reopen. In my own tests I am not having a problem, even when using Highcharts and modals.

**Comment by mmustala** [comment]
It depends where the html for the modal locates in the dom. If you have the html before the grid it will work. But if the modal html is after the grid html, then you will see this issue, because of z-index stacking. 

I used to place the modal html to the bottom of the page with jQuery append, but now I'm putting it into the beginning of the page, right where the body starts, and there is no issues any more.

**Comment by radiolips** [comment]
I'm glad you have figured out a workaround. If you'd like to provide a jsfiddle, I'd be happy to look into the issue further.
