### ISSUE TITLE
how re attach detach node ??

### ISSUE THREAD

**Issue by esmaill21** [troolee/gridstack.js#221]
i want to minimize and maximize a box but i cant re attach a node in page ....
also data-bind  not work in html appended

**Comment by gugahoi** [comment]
I accomplished this by simply overriding the styles. Basically created a class `maximized` and positioned it fixed with top, bottom, left, right to 0. That way I simply toggle the class to maximize or put it back in the grid.

**Comment by radiolips** [comment]
The method @gugahoi mentions is similar to how we've done it in projects as well.
