### ISSUE TITLE
Problem with cell_width

### ISSUE THREAD

**Issue by danielandross** [troolee/gridstack.js#222]
I am having an issue here. My goal is to create a 3x3 Grid where widgets are either 1/3 or 2/3 or 3/3 of document's width/height.
My Code is:
var options = {
            animate : false,
            cell_height: Math.floor($(document).height()/3),
            cell_width: Math.floor($(document).width()/3),
            width: 3,
            height: 3,
            float : true,
            draggable : {handle : '.dashboard-widget-header', scroll : true, appendTo : 'body'},
            vertical_margin: 10,
            always_show_resize_handle: /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)
        };
        gridstack = $('.grid-stack').gridstack(options);

Am I missing something?

Edit: My css:

.grid-stack {
  width: 100%;
}
.grid-stack>.grid-stack-item[data-gs-width='1']{
  width: 33% !important;
}
.grid-stack>.grid-stack-item[data-gs-width='2']{
  width: 66% !important;
}
.grid-stack>.grid-stack-item[data-gs-width='3']{
  width: 99% !important;
}
.grid-stack>.grid-stack-item[data-gs-height='1']{
  height: 33% !important;
}
.grid-stack>.grid-stack-item[data-gs-height='2']{
  height: 66% !important;
}
.grid-stack>.grid-stack-item[data-gs-height='3']{
  height: 99% !important;
}

With the css the widget have the size I wish. But this does not seem to affect the "drag-n-drop release points". They keep their size of 1/12 of the document but with only 3 cells so only a fourth of space is in use.

Can you help me?

**Comment by derekm** [comment]
Did you use the SASS/SCSS recipe from the documentation for regenerating the grid CSS?

**Comment by danielandross** [comment]
Thanks. I read this passage over.
