### ISSUE TITLE
Not defined errors

### ISSUE THREAD

**Issue by Johnathon332** [troolee/gridstack.js#225]
I have downloaded the latest jquery ui libraries and gridstack js files and css and have referenced these in my project, however I am getting errors 

ReferenceError: _ is not defined
factory(jQuery, _);

This is within the gridstack.js file and when I try to use the example off the github page I get.

TypeError: $(...).gridstack is not a function
$('.grid-stack').gridstack(options);

**Comment by troolee** [comment]
Hi, you also need lodash.js or underscore.js

**Comment by Johnathon332** [comment]
The thing is, I do have lodash

**Comment by joemorcullo8** [comment]
@troolee Hi, on the latest Gridstack.js that I downloaded there is no lodash.js or underscore.js, but still I'm getting an error.

**Comment by abdullahseba** [comment]
Hi I know this is old but why dont the docs mention this?

**Comment by william-e-schroeder** [comment]
It is even older, and still not mentioned.
