### ISSUE TITLE
when using minified css, animate is laggy in Chrome on Windows; non-minified is smooth

### ISSUE THREAD

**Issue by jalipert** [troolee/gridstack.js#226]
No idea what is causing this issue, but my workaround is to minify the original css file in gulp myself, and animations are smooth as butter.

**Comment by DoctaWorm** [comment]
Also experiencing this issue. The animation works great in Internet Explorer 11, but it's very laggy in Google Chrome v45.0.2454.99 m

**Comment by radiolips** [comment]
Could you provide a jsfiddle? I'm not having this issue. Perhaps at some point something (Chrome or gridstack) had a change that fixed the problem? Closing, but please reopen and provide fiddle if you're still encountering this issue.
