### ISSUE TITLE
Rearrange dashboard

### ISSUE THREAD

**Issue by lokeshhctm** [troolee/gridstack.js#229]
I placed several div tags dynamically with add_widget API.
Each DIV tag has a close button along with one data table.
I want whenever close button is clicked, widget should be removed from dashboard which i successfully did but it leaved  blank space on the dashboard instead dashboard rearrange all DIV tags.

**Comment by getrupendra** [comment]
https://github.com/troolee/gridstack.js#remove_widgetel-detach_node 

This should help.
