### ISSUE TITLE
setting a default minimum grid area

### ISSUE THREAD

**Issue by spitzbubchen** [troolee/gridstack.js#230]
Just wondering if it is possible to specify a default minimum grid size area (height and width) before widgets are added?

var options = {
       ?????
};
$('.grid-stack').gridstack(options);

If added widgets exceed this area the area would then dynamically expand to accommodate them. If widgets are removed such that the area required is less than the minimum it would go back to the default minimum grid area. I didn't see a way to do this in the docs.

**Comment by troolee** [comment]
You can setup `min-height` css style for `.grid-stack` container.

**Comment by vbinithyanandamv** [comment]
Hi @troolee If we set min-height to container, its affecting the resize of the grid items. Any idea of why?

**Comment by patril** [comment]
Same issue here. If a min-height is specified on the container, resizing an item will cause the height to snap to a smaller value.

**Comment by mandys** [comment]
+1

Facing same issue.
Passing min-height is making resize not happen correctly.
