### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by randoum** [troolee/gridstack.js#231]
Sorry to use the issue board for that
Do you have a projected date to release 0.2.4?

Cheers

**Comment by randoum** [comment]
Up

**Comment by troolee** [comment]
Unfortunately due to heavy busy days at my main work I have no ETA for release. Sorry

**Comment by randoum** [comment]
Did you thought about finding a trusty collaborator to help you then?

**Comment by randoum** [comment]
3 months later I would like to know if now you have visibility on an ETA, or still not ?
Thanks and regards
