### ISSUE TITLE
How to make gridstack auto widgets moving stop towards upward?

### ISSUE THREAD

**Issue by nicefellow1234** [troolee/gridstack.js#234]
Hi,
I hope that gridstack team will be in perfect health..!
I just want to be able that when I move a widget so the other widgets don't go upward direction to fill it's empty place..!
Instead more like I want the other widgets to stay at their location when I move one widget and don't go upward to fill the newly moved widget place..!
How am I gonna do that? Can anybody let me know please..? I tried to check and search everywhere but either not getting it or didn't get it how to make it work..!
My GridStack Code : http://pastebin.com/PZVKXmKS

**Comment by dandehavilland** [comment]
Try setting `float: true` in the initialization options.

**Comment by nicefellow1234** [comment]
@dandehavilland Indeed it worked..Thanks very much for helping to not stop to believe in gridstack as a solution for our problems..!
Also the Grid Items are really not moving around very smoothly how can I make it smooth like gridster..! like it goes from one place to another with a little transition like that..!

**Comment by radiolips** [comment]
@nicefellow1234 You may change the CSS to create the same sort of transitions.
