### ISSUE TITLE
Auto resize disable

### ISSUE THREAD

**Issue by nijesh-wiredelta** [troolee/gridstack.js#235]
On resize the widget height and width is auto adjusted to proportionate size, I want to disable it and have the same width and height of widget after resize it. Please comment.

**Comment by troolee** [comment]
Can you provide more details?

**Comment by jinma1978** [comment]
I would like to reopen this ticket to ask the same question. Once a widget had been sized, changing the screen resolution and browser size will automatically move the and resize the widget. How can I disable that automatic move/resizing? Basically, I only want the widget to be moved and resized from direct user input to the widget not from external condition like screen browser window size change.

**Comment by vikasKacholia** [comment]
I am also facing same issue , you got any solution for this ?
