### ISSUE TITLE
Restrict items to certain sizes

### ISSUE THREAD

**Issue by indriemarius** [troolee/gridstack.js#236]
Hey,

Is there a way in the current API's functionality to restrict the size of an element to certain width-height pairs ?

For example, allow an item to be **1x2** or **2x2**, but not **2x1**. Or any other restrictions for that matter. Any different item to have different accepted sizes.

Thanks.

**Comment by LevTaylor** [comment]
Hey,

you can set it like this on the fly:

    widget.option({
	min_width:1,
	min_height:2
    });

or add these attributes:
    
    data-gs-min-width ="2"  data-gs-min-height ="1"
