### ISSUE TITLE
Add option to add_widget() to not append node

### ISSUE THREAD

**Issue by jhpedemonte** [troolee/gridstack.js#238]
To go along with issue #216 and the current impl of `remove_widget`, the function `add_widget` should have an option to skip the call to `append()`. This will allow us to use gridstack in a situation where the DOM nodes are already in place and we don't want gridstack to move or destroy existing nodes.

**Comment by karellm** [comment]
Is there a reason this was closed @troolee ? I would really like that option, in our current implementation we are forced to overwrite `addWidget` which is quite hacky. Thanks!

**Comment by troolee** [comment]
mathod `makeWidget` has been added for this purpose https://github.com/troolee/gridstack.js/tree/master/doc#makewidgetel
