### ISSUE TITLE
Run cell_height(val) on a specific box.

### ISSUE THREAD

**Issue by antonradev** [troolee/gridstack.js#240]
Hi!
How can I get the current box from the entire grid container.
grid.cell_height(val) executes on the entire grid and to all of the boxes inside. 
Can I set height in pixels on a specific box?
Thank you!

**Comment by troolee** [comment]
You cannot change height in pixels for specific widget. Because gridstack is a grid of cells you can change widget height in cells: 1, 2, 3... Please check `resize` method: https://github.com/troolee/gridstack.js#resizeel-width-height
