### ISSUE TITLE
Documentation/examples include unnecessary <div/>

### ISSUE THREAD

**Issue by timwis** [troolee/gridstack.js#242]
Hello, I just wanted to let you know that several of your documentation examples include creating an unnecessary `<div/>` element, for example:

```javascript
grid.add_widget($('<div><div class="grid-stack-item-content" /><div/>'),
			node.x, node.y, node.width, node.height);
	}, this);
```
While it appears you intend for it to serve as a closing div tag, like `</div>`, what it's actually doing is creating an extra `<div></div>` at the end. The trailing `/` tells jQuery it's an empty `<div>` tag. For instance, `$('<div/>')` is valid jQuery syntax to create an empty div, and results in `<div></div>` being added to the DOM.

The correct way to add the container would be, `$('<div><div class="grid-stack-item-content" /></div>')`

**Comment by troolee** [comment]
It's a typo. Thank you!
