### ISSUE TITLE
Review the code

### ISSUE THREAD

**Issue by NGorco** [troolee/gridstack.js#248]
I think, you do not clear the code due to this 

   GridStackEngine.prototype.commit = function() {
        this._update_counter = 0;
        if (this._update_counter == 0) {
            this.float = this._float;

:smiley:

**Comment by NGorco** [comment]
And fix batch_update. It not working at all.

**Comment by radiolips** [comment]
#306, #267 and this ticket all seem related. We will look into this tomorrow and should be able to get a fix into v0.2.5-dev (master) then.

**Comment by troolee** [comment]
It's fixed now. Thank you.
