### ISSUE TITLE
How to update grid stack item height runtime

### ISSUE THREAD

**Issue by devSam123** [troolee/gridstack.js#249]
Hi! i have a requirement of minimizing the widget height run time. so when i click on minimize icon i want to reduce the height of grid stack item as well(for inner content its already happening as a part of code). We are using Angular App. Kindly help me on this. Any help at this time will be greatly appreciated.

**Comment by devSam123** [comment]
Hi! i could achieve this using update method-

                          if (collpased) {
                              collpased = false;
                              controller.gridstack.update(element, null, null, null, 2);
                              this.className = "icon-minimize";
                          } else {
                              collpased = true;
                              controller.gridstack.update(element,null,null,null,1);
                              this.className = "icon-maximize";
                          }

Is 1 is the lowest possible minimum height ? can we set a height lower to 1 as well?

**Comment by troolee** [comment]
Yes, 1 is the lowest possible height. But you can change height of one cell in px during gridstack initialization
