### ISSUE TITLE
Is it possible to create vertically responsive/scaling grids and widgets

### ISSUE THREAD

**Issue by jarlarntzen** [troolee/gridstack.js#250]
Hi.

It's easy enough to create a horizontally responsive grid with 100% width and this does seem to behave quite nicely.

Is there a similar way to set the grid to 100% of the viewport height while each widget inside also scales vertically to fit? The idea is that, exactly in the same manner as the grid scales horizontally, the grid will also scale vertically.

Thanks,
Jarl

**Comment by derekm** [comment]
You could probably use a variant of this trick:

https://github.com/troolee/gridstack.js/issues/102#issuecomment-133538587

But I think you'd have to set cell height programmatically on window resize events.

**Comment by jarlarntzen** [comment]
Thanks. I'll try to implement the current horizontal bootstrap scaling scheme in a similar vertical fashion where there are 12 rows which stretch to adapt to the height of the viewport. 
Plenty nice tips to try in the StackOverflow linked in #102

**Comment by McQuinTrix** [comment]
@jarlarntzen Hey, were you able to solve vertical aligning issue?

**Comment by McQuinTrix** [comment]
I solved this issue changing the line 522 in gridstack.js to :

`'height: ' + ((this.opts.cell_height * (i + 1) + this.opts.vertical_margin * i))/7.7 + '%;',`

and changing the 537 line in gridstack.js to :

`'top: ' + ((this.opts.cell_height * i + this.opts.vertical_margin * i))/7.7 + '%;', `

and in your own CSS line give
```
.gridstack{
   height: 100% !important;
}
```

**Comment by jarlarntzen** [comment]
Looks very cool! I have to get around to try this! Thanks!

**Comment by radiolips** [comment]
Scaling can be done, as @McQuinTrix has mentioned, by modifying CSS and by tapping into the JS (modifying `gridstack.js` is not preferred, but this can be done by listening to events instead). Closing this ticket. Please let me know if you have further issue.

**Comment by wheresjames** [comment]
Thanks to everyone for the tips.  Since I couldn't find a full working solution anywhere, I thought I would provide a link to [this example](http://bl.ocks.org/wheresjames/3689d262f2a0edf98eee0b6ad781e511) that does not involve modifying `gridstack.js`.
