### ISSUE TITLE
how to trigger resize event? currently just onresizestart and onresizestop events.

### ISSUE THREAD

**Issue by litaotao** [troolee/gridstack.js#251]
I would like to do something when user is resizing the size of one `grid-stack-item`.

currently just `onresizestart` and `onresizestop` events, can add a `onresize` event or how do I implement `onresize` event ?

thanks a lot

**Comment by radiolips** [comment]
You should be able to use the undocumented `resize` event triggered by jQuery-ui.

**Comment by DoctaWorm** [comment]
This should get documented, took me and another developer day or two to figure out how to implement a feature that uses this event. I believe he'll be submitting a pull request sometime today on this.

**Comment by jiann4321** [comment]
Need this function as well jquery.resize() listen is not helping either.

**Comment by radiolips** [comment]
@jiann4321 
https://github.com/troolee/gridstack.js/tree/develop/doc#gsresizestopevent-ui
