### ISSUE TITLE
Any way to use this without position absolute?

### ISSUE THREAD

**Issue by timwis** [troolee/gridstack.js#252]
Hey guys, I'm trying to use gridstack to build a layout for this [visualization tool](http://vizw.it/?gist=a304ce8fac9c14dfbf16). I've got it working but I'm running into issues with the impact of `position:absolute`. Namely that if the height of the content expands past the widget container, there's no way for the widget container to realize it and expand its height like a normal `<div>` would. The way I had it originally setup with bootstrap `row` and `col-md-6` worked very well.

Is there any way to use gridstack without `position:absolute`? If you can point me in the right direction I'm happy to go the rest of the way.

**Comment by timwis** [comment]
In case anyone's come across this from a google search, here's what I ended up doing to make it use bootstrap rows and columns:

```javascript
var container = $('#page-content');
var heightInterval = 60; // from gridstack.js
var current = {x: null, y: null};
var row;

config.cards.forEach(function(config) {
	// If y suggests we're on a new row (including the first item), create a new row
	if(config.y !== current.y) {
		row = $('<div class="row"></div>');
		container.append(row);
		current.y = config.y;
		current.x = 0;
	}
	
	var column = $('<div/>');
	
	// Add width class
	column.addClass('col-sm-' + config.width);
	
	// If x is not the same as our current x position, add offset class
	if(config.x !== current.x) {
		column.addClass('col-sm-offset-' + (config.x - current.x));
	}
	// Set height of new div
	column.css('min-height', config.height * heightInterval);
	
	// Increment current.x to new starting position
	current.x += config.width;
	
	// Add the div to the current row
	row.append(column);
	
	// Initialize vizwit on new div
	vizwit.init(column, config.vizwit, {
		vent: vent,
		fields: fields
	});
});
```

**Comment by artknight** [comment]
I do like your approach to just using bootstrap grid layout to display the items. I am wondering what you do when you have a column span several rows and other items that show up below to slide up to avoid having white space introduced by <div class="row">?

Thanks

**Comment by timwis** [comment]
@artknight yeah, this approach is not foolproof -- especially because gridstack lets you rearrange the order without actually changing the order of the JSON objects. I started working on a [fresh alternative](http://codepen.io/timwis/pen/meLYOv) using dragula but never finished.

**Comment by artknight** [comment]
@timwis I have used your initial approach and added an algorithm that attempts to "correct" some of the rowspan behavior ( since all items with different item.y will be placed initially into a new row ). Check it out and if you feel like we could collaborate and create something awesome.
https://jsbin.com/bedoliv/16/edit?js,output

Right now it only works on a grid up to 4 column. There are 4 layouts that address issues that. To see the  layouts without the algorithm in place, simply uncomment **enable_alg = false** on line 21

**Comment by timwis** [comment]
Awesome! I'll dive in tomorrow

**Comment by artknight** [comment]
Perfect!

**Comment by artknight** [comment]
@timwis did you have a chance to examine the code?

**Comment by zspitzer** [comment]
this looks really good, are you going to create a repo?

**Comment by troolee** [comment]
I don't think it's event possible to implement all variation of layouts and features gridstack now supports using only bootstrap layout.

And there is no such a goal at least for the next few releases.
