### ISSUE TITLE
Gridstack.js:Re-size and Draggable feature not working when window is minimized to IPad Resolution

### ISSUE THREAD

**Issue by devSam123** [troolee/gridstack.js#253]
Hi! I am using gridstack.js in my project. When i resized the browser to Ipad resolution , then the gridstack items are no more resizable and draggable. I am not at all able to resize or drag the items. Kindly help me on this on how to enable resizing and dragging on this resolution as well. Any help at this time will be greatly appreciated.

**Comment by jm06487** [comment]
Any updates?  I'm trying to use the demo on my iPhone and nothing happens.  If I use the demo on my iPad that has a wider screen it works with no problems.

**Comment by jm06487** [comment]
Update: found out that changing the gridstack.css value for max-height from 768px to 340px to accommodate a iphone screen size.  Also have to change the default value in gridstack.js default value in opts. to 340 as well.  

Hope this helps anyone that was searching for this solution.

**Comment by devSam123** [comment]
Thanks a lot !! Will definitely try this out. 

Could you please also help me on one more issue , this is the link for that https://github.com/troolee/gridstack.js/issues/254. Thanks in advance.
