### ISSUE TITLE
While scrolling the inner content of grid-stack-content-item , item itself gets dragged, on mozilla browser.

### ISSUE THREAD

**Issue by devSam123** [troolee/gridstack.js#254]
Hi, i am using gridstack.js in my project. I came across this scenario on Mozilla browser. When there is a scroll bar in grid-stack-content-item then while trying to scroll , the item gets dragged. This doesn't appear on chrome. I checked on ie11 , where i am able to scroll without dragging, but after that not able to drop the item anywhere. We are focusing more on ie 11 browser, thus can't ignore it. 
Kindly help me on fixing this issue on ie11 and Mozilla browser. Any help at this time will be greatly appreciated.

**Comment by troolee** [comment]
You can specify dragging handle for your widget (widget's header, a button or so) https://github.com/troolee/gridstack.js#options
