### ISSUE TITLE
get updated positions after removing an element

### ISSUE THREAD

**Issue by azza0091** [troolee/gridstack.js#255]
If I remove an element from the grid, all the other elements are reordered to fill in the gap (when possible). I store the elements position in a DB and I'd need to update their position as they move.
I am using the "change" event to detect when some element changes size or position, but this event is only fired when I manually drag or resize an element, not if the items are automatically reordered due to the deletion of another element.
Is there any way I can make it fire in that condition? ore some other method to detect the updated elements?

**Comment by radiolips** [comment]
Removing a widget via the `grid.remove_widget` will fire a `change` event for all affected widgets.
