### ISSUE TITLE
Determine the position in the grid, where the cursor is.

### ISSUE THREAD

**Issue by iliyaZelenko** [troolee/gridstack.js#256]
Hi.
First, I want to thank the author for a good library, respect you.
How to determine the position in the grid, where the cursor?
I want to add a method add_widget to place the cursor where the widget.
I would like to highlight this place styles.
Thank you.

**Comment by radiolips** [comment]
Closing because the question is not specific to gridstack. You may calculate where the cursor is and, using gridstack's function `getCellFromPixel`, determine what location to pass to `add_widget`.
