### ISSUE TITLE
onReady or onLoad event

### ISSUE THREAD

**Issue by movie4** [troolee/gridstack.js#259]
Hello, thanks for great app!

gridstack.js have an event like?

```
gridstack.on('ready', function() {
  // gridstack is ready.
});
```

**Comment by movie4** [comment]
+1

**Comment by radiolips** [comment]
I'm rather unclear on what you mean. When you call `.gridstack()`, the element in question should promptly be prepared for grid manipulation. However - is the grid empty, or full? (option `auto` true or false?)

**Comment by movie4** [comment]
Resolve by https://github.com/troolee/gridstack.js/tree/master#load-grid-from-array 
Thanks
