### ISSUE TITLE
how to use more than 12 col?

### ISSUE THREAD

**Issue by rauljuncoV** [troolee/gridstack.js#260]
All the calculations happen inside the CSS files accommodating a max of 12 col. What's the motivation of doing that in the CSS instead of the using the JS to make all the math dynamically. I apologize before hand since I don't know the reason behind the decision of having this inside the CSS.

**Comment by iliyaZelenko** [comment]
+

**Comment by whipdancer** [comment]
I would like to use more than 12 columns as well.

**Comment by lomomas** [comment]
You can set the width to any number of columns. There is this small python script in the documentation to generate the CSS to match the number of colums. I discovered it too late and wrote a small script for myself (took about 5 minutes).

**Comment by troolee** [comment]
Please refer to the doc https://github.com/troolee/gridstack.js#change-grid-width

You can generate CSS for any grid size. Just use SASS
