### ISSUE TITLE
resize method does not increase width if grid-stack-item is at the far right of gridstack container

### ISSUE THREAD

**Issue by jemag** [troolee/gridstack.js#263]
When resizing a  grid-stack-item with the resize method, the item cannot have a bigger width if it is at the extreme right of the gridstack container. It seems like the container is limiting the increase of width of the grid-stack-item.
![resize problem](https://cloud.githubusercontent.com/assets/7985687/10698852/16331b00-7981-11e5-9c6e-3f7200b72525.png)

Basically, the resize method seems to always resize the width toward the right of the object but the container is limiting that operation. When the grid-stack-item is at the far right of the container, the grid-stack-item should resize the width toward the left instead.

**Comment by kdietrich** [comment]
I guess you have only activated the resize handle in the bottom right corner. If you want to increase the size to the left, you also have to enable the bottom left handle.

See: https://github.com/troolee/gridstack.js#options
Demo: http://troolee.github.io/gridstack.js/

**Comment by jemag** [comment]
I am not using the resize handle. I am using the resize method from the api --> resize(el, width, height).

Basically we want our grid-stack-items to be able to change between two different widths using a button. We do NOT want users to be able to change the size of the item with a handle or to any other value than the 2 specified by us.

**Comment by jemag** [comment]
Just to make things more clear. Here is a small prototype that shows how the dashboard looks before making any change to the size of the items.
![before resize modified](https://cloud.githubusercontent.com/assets/7985687/10730839/d15a8b2c-7bc8-11e5-8bb7-51fa48a9dda7.png)
Once the user click on the button, the items should grow to their new size using the resize method.
Here is the current result using this method:
![after resize modified](https://cloud.githubusercontent.com/assets/7985687/10730855/ec05c00e-7bc8-11e5-9d55-4743eaf91517.png)

We can clearly see that the bottom right item did not grow to the full size, being limited to the right by the container. I think when the item is near the far right of the container, it should be able to grow from the left also, so that the resize method works everywhere, and not in only some specific locations.

**Comment by radiolips** [comment]
You can override the resizable options. As @troolee mentions, you may not want to include a few of them. This, however, will solve your problem:
https://github.com/troolee/gridstack.js#override-resizabledraggable-options

**Comment by jemag** [comment]
I simply added a check on the item position and if it is close to the edge, I move the item accordingly to the left before activating the resize. Maybe a bit hacky but works quite well for our current setup.

Would still be nice if gridstackjs would detect this situation automatically.

**Comment by radiolips** [comment]
Reopening - I see that you stated you are using the API. Via the API, we should have an optional parameter dictating which direction to expand: nw, sw, ne, or se.

**Comment by radiolips** [comment]
I misunderstood this previously. You're saying you want the API to automatically know what direction to resize in. Unfortunately, that removes some of the intuitiveness, because we would expect it to be unable to resize in certain situations where it would suddenly be able to resize. Because you're using the API, you can actually do this yourself. You may tap into the `willItFit` API call, and, if it does not fit, try another direction. By using the `update` API call, you can set the x, y, width, and height of the widget. In your case, it will help. I'm closing, but please let me know if you have any issue still.
