### ISSUE TITLE
Freezing the Grid ?

### ISSUE THREAD

**Issue by daslicht** [troolee/gridstack.js#265]
Hi,
is there a way to make the Grid no longer editable ?
Or is there a way to render the grid as standard bootstrap code?

Is it possible to use the grid to create a 'layout' on the fly (add elements), 
enter some content and save it and it can be displayed even without js ?

~Marc

**Comment by kdietrich** [comment]
Please take a look at the `static_grid` option: https://github.com/troolee/gridstack.js#options.

**Comment by daslicht** [comment]
Ok nice !

```
static_grid - makes grid static (default false). If true widgets are not movable/resizable. You don't even need jQueryUI draggable/resizable. A CSS class grid-stack-static is also added to the container.
```

So I could create my grid as I go , than set it to static and save the generated html output ?
Or how would that be used ?

**Comment by kdietrich** [comment]
Exactly. However the preferred use-case would be to serialize the grid, save it and restore from that later. See: http://troolee.github.io/gridstack.js/demo/serialization.html#

**Comment by daslicht** [comment]
Yeah I saw that, but to restore it you need js ? 
What happens if there is no js ? 
Will the content be output just unformatted  or is it simply not rendered?

**Comment by daslicht** [comment]
What is this random number css class used for? eg: 'grid-stack-2879' it is each time I create a grid something different.
I just tried the static_grid function  and noticed that the ```grid-stack-static``` is set.
But what does that supposed to to do ? 
see: https://github.com/troolee/gridstack.js/issues/266

**Comment by daslicht** [comment]
Is there anywhere an example how to : 
```
 It allows you to build draggable responsive bootstrap v3 friendly layouts. 
```
If I just get the html code after setting static, i wont have a bootstrap compatible layout.
please ?
