### ISSUE TITLE
Set Static ?

### ISSUE THREAD

**Issue by daslicht** [troolee/gridstack.js#266]
Hello,
I have tried to use the set_static function but without success yet.
here is my approach : 

https://jsbin.com/ducefu/6/edit?js,output

How do I call set static correctly? please

**Comment by daslicht** [comment]
Just noticed that the static class is added !

```
set_static(static_value)

Toggle the grid static state. Also toggle the grid-stack-static class.

static_value - if true the grid become static.
```
What does  *the grid become static* exactly mean please?

**Comment by kdietrich** [comment]
`set_static` is not available in the latest version v0.2.3. See README: https://github.com/troolee/gridstack.js/blob/v0.2.3/README.md.

If you want to use `set_static` consider to build the latest version from master. And please note that github is not a helpdesk for your problems. Issues are only meant to track bugs or future requests.

**Comment by kdietrich** [comment]
The documentation says: `If true widgets are not movable/resizable. You don't even need jQueryUI draggable/resizable. A CSS class grid-stack-static is also added to the container.` And please note that github is not a helpdesk for your problems. Issues are only meant to track bugs or for future requests.

**Comment by daslicht** [comment]
I can still move or resize items even tho they has been set static....
But never mind we no longer consider using this plugin.
