### ISSUE TITLE
Collisions Are Not Moving

### ISSUE THREAD

**Issue by metal-slime** [troolee/gridstack.js#268]
I'm working on a new instance of gridstack and I can't get collisions to move the items. Doesn't matter if it is a generic set of empty containers or my actual data. The _fix_collisions function fires off successfully. It detects the collision and sets the x and y values appropriately. However, these values never actually enter into the grid and the items never move.  Clean project or not clean, doesn't matter. Collision moves never take place. Any thoughts?

**Comment by metal-slime** [comment]
Problem was using version 4 of lodash.js. Going to a previous version, 3.5 from one of the demos, appears to have fixed the problem.

**Comment by lomomas** [comment]
Do you have any idea which lodash function in the version 4 pre-release causes this error? I try to figure out if it's a lodash problem or a gridstack problem.

**Comment by neuoy** [comment]
I had the same issue, with lodash 4.0.0. I wonder how many people ran into this issue since it's usually what you do first when you need to install a new dependency : install the latest version. Would probably be worth a warning in the dependencies list.

**Comment by cdoshi2000** [comment]
I had the same issue too. Should it not work with the latest version of lodash? Or is it lodash that has the problem?

**Comment by andrewr88** [comment]
If you take a look at PR #309 for the required changes to gridstack, lodash 4.0 removed the context parameter in favor of more explicitly using the _.bind method.

**Comment by cdoshi2000** [comment]
Perfect @andrewr88 That works!!! Cheers. Awesome!
