### ISSUE TITLE
how to make elements editable in gridstack , thanks ?

### ISSUE THREAD

**Issue by litaotao** [troolee/gridstack.js#269]
hi, thanks for building gridstack, it's amazing. here is my use case of [gridstack](https://github.com/litaotao/IPython-Dashboard)

[![2015-10-31 6 55 52](https://cloud.githubusercontent.com/assets/4660350/10863222/50c87c66-8001-11e5-9753-8e827be983ae.png)](https://github.com/litaotao/IPython-Dashboard)

and now I want to select some data in that table just like selecting data in excel, but it triggers the drag function of gridstack when I click and move the mouse trying to select data.

So I want to know is there any way to make the children elements in gridstack editable ? great thanks.

PS: here is a [demo online](http://troolee.github.io/gridstack.js/demo/nested.html) , in that demo, is there anyway to make the text in a separate, editable text area ?

thanks again

**Comment by edborden** [comment]
Gridstack elements are just HTML elements. You can put anything inside them. So if you want to have an editable field like a TextBox, you can put that inside a Gridstack container element.

**Comment by litaotao** [comment]
@edborden  thanks for your reply, but have you test your solution before put it out? Actually, as I said before, even though you put an textbox inside a gridstack container, it will not be editable, since the gridstack container have triggered the `drag` event once you click and move the the mouse.

**Comment by edborden** [comment]
@litaotao You have to grab the mousedown event and prevent it from propagating. If you make a JSBin, I can try to help.

**Comment by litaotao** [comment]
@edborden I've find a way to make it , will give a demo here later, thanks.
ps. gridstack is amazing

**Comment by litaotao** [comment]
@edborden I use a way to make the editable option controllable. in my project [IPython-Dashboard](https://github.com/litaotao/IPython-Dashboard/tree/v-0.1.2-visualiza-table) 

these is a button which can control the gridstack editable or not.

- un-editable

<img width="590" alt="screen_shot 2015-11-10 at 4 21 32 pm" src="https://cloud.githubusercontent.com/assets/4660350/11057568/25ebc426-87c7-11e5-8f56-09b969ba3c2f.png">

- editable after click
<img width="98" alt="screen_shot 2015-11-10 at 4 22 14 pm" src="https://cloud.githubusercontent.com/assets/4660350/11057600/70cafbc4-87c7-11e5-94bd-9bd5feaf14fc.png">


related html and js code:

```
<button class="fa fa-fw fa-sm fa-circle-o-notch" onclick=toggleGridEditable(this) style="background: none;background-color: inherit;border: none; padding: 0px 0px">         \
              </button></td>
```

```
function toggleGridEditable(obj){
  // clear any active button if set before
  $.each($("button.fa-circle-o-notch"), function(index, btn_obj){
    if (obj != btn_obj){
      btn_obj.className.includes("down") ? btn_obj.classList.remove("fa-spin") : null;
      btn_obj.className.includes("down") ? btn_obj.classList.remove("down") : null;
      btn_obj.style.color = "";
    }
  });
  // tag a new button
  $(obj).toggleClass("down");
  $('.grid-stack').data('gridstack').movable('.grid-stack-item', obj.className.includes("down"));
  $('.grid-stack').data('gridstack').resizable('.grid-stack-item', obj.className.includes("down"));
  obj.style.color = obj.className.includes("down") ? "green" : "";
  obj.className.includes("down") ? obj.classList.add("fa-spin") : obj.classList.remove("fa-spin");

  console.log("grid stack movable");
}
```


will close this issue later

**Comment by juwilliams** [comment]
I had a similar issue. Here is the workaround I used:

    addWidgetHandler : function(view, grid, item, options){
            $(item).draggable({cancel : 'table tr td,span, input'});
            $(item).removeAttr('style');
            $(item).append(view);
            $(item).hide();
    var widget = grid.add_widget(item, options.x, options.y, options.width, options.height, options.findNextPosition);

            $(item).fadeIn(200);

            return widget;
        }

**Comment by radiolips** [comment]
You can use a specific class for dragging an object. Please refer to the `handle` property of the `draggable` grid option.
