### ISSUE TITLE
How to generate dist files

### ISSUE THREAD

**Issue by marcodejongh** [troolee/gridstack.js#273]
Currently contributing is a bit hard because the build setup for this plugin isn't stored in the repo.
Would someone mind creating a grunt or gulp file and adding it to the repo so contributors can regenerate the dist directory upon submitting a PR.

**Comment by jlowcs** [comment]
Here's my pull request: https://github.com/troolee/gridstack.js/pull/283

**Comment by kdietrich** [comment]
Thanks @jlowcs.
