### ISSUE TITLE
Uncaught TypeError: $(...).gridstack is not a function

### ISSUE THREAD

**Issue by icdindia** [troolee/gridstack.js#279]
getting this error while trying to run the demo:

Uncaught TypeError: $(...).gridstack is not a function
(anonymous function) @ (index):120
j @ jquery.min.js:2
k.fireWith @ jquery.min.js:2
m.extend.ready @ jquery.min.js:2
J @ jquery.min.js:2

**Comment by icdindia** [comment]
solved : the issue is with jquery 1.11.3

realised that it is only compatible with jquery 1.11.1

**Comment by raja4014** [comment]
I m getting the error, "TypeError:$(...).gridstack is not a function". It was a dashboard application developed using Gridstack. From many days it was working fine. As part of app maintenance did some changes to fix errors. But the code related to gridstack was not changed. Also, We didn't do any version changes of Jquery. No idea how to handle this error. Any ideas? 

Thanks in advance.

**Comment by nerdess** [comment]
@icdindia i have the same issue, added  "jquery": "1.11.1" as a dependency in package.json and ran npm install again but the error persists...
