### ISSUE TITLE
Gridstack dragging outside parent

### ISSUE THREAD

**Issue by nniicc** [troolee/gridstack.js#282]
Hey

Im trying to make gridstack that fills up the parent element with 100% width and height,
but im not finding any solutions for this,
```html
<div class="droppable-container">  //width: 900px, height: 800px
    <div class="grid-stack"></div>
</div>
```

```javascript
var options = {
    float: true,
    draggable: {
        containment: $(".droppable-container"),
        scroll: false
    },
    resizable: {
        containment: $(".droppable-container")
    }
};
```

I want to disable dragging outside of the parent element,

I managed to stop the resizing outside of the parent but dragging is still enabled

**Comment by ascendantofrain** [comment]
Do you have a jsfiddle that could show your issue more precisely?

**Comment by radiolips** [comment]
This shouldn't be a problem, unless I'm misunderstanding you. Could you please provide a jsfiddle? In the meantime, I'm closing this ticket, because of inactivity. Please feel free to reopen with more information.
