### ISSUE TITLE
Resize and drag moves node one column to left automatically when using many columns

### ISSUE THREAD

**Issue by lomomas** [troolee/gridstack.js#284]
I changed the grid width (colums) to 50. At some columns the indicated target column jumps one column to the left. 

Therefore I made two changes:

1. in the drag function: `var x = Math.ceil(ui.position.left / cell_width),` to jump to the right and not to the left, because going to the right has less impact on the position of other elements, because the problem only appears on elements beyond column #30.

2. In the resize function I changed the code that it uses the current x and y values and not ui.position. 
` var x = ui.element.attr('data-gs-x'), 
         y = ui.element.attr('data-gs-y'), `

Until now I haven't had any problems using these changes and it does not seem to have any impact on the standard behaviour.

**Comment by radiolips** [comment]
Closing because this is a repeat of #141.
