### ISSUE TITLE
Width and height changes on resize

### ISSUE THREAD

**Issue by GertVen** [troolee/gridstack.js#285]
Hi,

Is it possible to somehow get the final values of a div after a resize has been completed? Currently I'm using the plugin along with Highcharts and would like to resize my chart along with the widget. I got everything working using the "resizestop" event but I've seen the resized div still changes its width and height to get everything in alignment with the other components after the event has triggered.

Thanks!

**Comment by lomomas** [comment]
I ran into a similar issue that the content within one panel must react to the new size. The new width and high is calculated after the resizestop. For now I just used an small timeout (10ms) and that was in our case enough time and panel dimension was updated.

**Comment by GertVen** [comment]
Thank you for the answer. I implemented a similar solution but had to set my timeout to 200ms in order for everything to resize correctly.
