### ISSUE TITLE
Disabling Horizontal Resize only

### ISSUE THREAD

**Issue by ddanielbee** [troolee/gridstack.js#286]
Hi, 

Is it possible to disable only horizontal resize ? I need to make a grid where height may vary, but width is always static.

**Comment by DoctaWorm** [comment]
Wouldn't just enabling the south resizeable work
```javascript
$('.grid-stack').gridstack({
    resizable: {
        handles: 's'
    }
});
```

Then you're only ever re-sizing the height, and your width will always be static

**Comment by ddanielbee** [comment]
Yes, that works. I am quite new to jQuery UI and missed that, thank you.

**Comment by DoctaWorm** [comment]
No problem! I can relate.
