### ISSUE TITLE
Gridstack not fluent

### ISSUE THREAD

**Issue by Cannonb4ll** [troolee/gridstack.js#287]
Hello everyone,

I recently implemented Gridstack, which is working just as I needed.

The only thing I am having a problem with, is the smoothness/fluentness(?) of the plugin on my website. When I resize a widget it does not resize on the fly but needs a few MS to render to the new size, its hard to explain but the point is, it does not resize fluently like the demo on http://troolee.github.io/gridstack.js/ does.

Can there be an issue with my jQuery version? Currently having version 2.1.4 jQuery.

**Comment by zspitzer** [comment]
Try doing a profile with chrome dev tools to see what is slowing down rendering?
Does it still happen if you have the grid without any content loaded inside it?

**Comment by Cannonb4ll** [comment]
I have found out why.

I had this in my HTML:

<div class="grid-stack" data-gs-width="12" data-gs-animate="yes">

When I removed data-gs-animate it was all solved.
