### ISSUE TITLE
When can we expect v0.2.4 release?

### ISSUE THREAD

**Issue by DoctaWorm** [troolee/gridstack.js#290]
Those `min_width`/`min_height` methods would be extremely helpful to use in some projects. Can we get a roadmap of when we can expect a release?

**Comment by zspitzer** [comment]
alas it seems this project is semi abandoned, lots of people are using it, pull requests are piling up 

any feedback @troolee? maybe you could allow other committers?

**Comment by DoctaWorm** [comment]
More committers would be wonderful. That needs to happen.

**Comment by genachka** [comment]
+1

**Comment by troolee** [comment]
Hey guys, I'm trying to clean all the mess now :)
