### ISSUE TITLE
Drop widget into trash

### ISSUE THREAD

**Issue by Notheros** [troolee/gridstack.js#291]
Is possible to implement a "drop to remove" feature? For example, drag and drop a widget inside a div (or any other element you want) to remove it.

I think this would be awesome!

**Comment by zspitzer** [comment]
have a look at this to get you started 
http://stackoverflow.com/questions/9796934/jquery-ui-remove-element-when-dropped-into-a-div-using-droppable

**Comment by troolee** [comment]
Duplicate of #133
