### ISSUE TITLE
Widgets are invisible after loading html-Code from Database

### ISSUE THREAD

**Issue by penta93** [troolee/gridstack.js#293]
Hi,

We are saving the entire html-Code from inside the grid in a database.
When we load the code back in the grid, the widgets (in the following example "#widget-1") are invisible, but the code is visible in the source-code.
```javascript
$('.grid-stack').append(data);
```

generated html source code (from DB)
```html
<div class="grid-stack grid-stack-8686" style="height: 0px;">
 <div id="widget-1" class="grid-widget grid-stack-item ui-draggable ui-resizable ui-resizable-autohide"  data-gs-x="0" data-gs-y="0" data-gs-width="2" data-gs-height="1" data-gs-auto-position="yes">
  <div class="grid-stack-item-content ui-draggable-handle">...</div>
  <div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90; display: none;"></div>
 </div>
</div>
```

Thanks for your help in advance!

**Comment by Unsttopabull** [comment]
Bit late but still if someone has the same problem.
I don't think just adding divs directly to the DOM works (At least it doesn't for me). You have to then manualy call **add_widget()** for each element. 

```js
$(".grid-stack").add_widget(domElement, x_pos, y_pos, width, height)
```

Also I've noticed that div classes are just for styles. The library keeps its own info in about widgets so changing the classes manually won't work you have to call the associated library function so the internal data gets updated as well.
