### ISSUE TITLE
Make widgets square regardless the window size

### ISSUE THREAD

**Issue by vukcuvardic** [troolee/gridstack.js#296]
Is it possible to make square widgets regardless the window size?
Currently the height of the widgets stay the same on window resizing, while the width changes. This way on narrow screens the widget becomes unproportional.
Any help would be more then welcome...

**Comment by DoctaWorm** [comment]
You could maybe try and override the "mobile" min_width which is default at 768px so once you've hit that break point it'll flip the widgets to fit the screen/phone/ipad view.

**Comment by troolee** [comment]
You can set window resize event handler and update grid cells height with value you need: https://github.com/troolee/gridstack.js#cellheightval

Be aware that it could be performance expensive on large grids
