### ISSUE TITLE
Height and width steps size

### ISSUE THREAD

**Issue by Cannonb4ll** [troolee/gridstack.js#297]
Hello everyone,

I was wondering, how can I change the size difference when u resize an item? 

What I mean is following: 

![Example](https://snapr.pw/i/ade731c7e6.png)

I would like to place the widget on the position I currently have there, but it only allows more to the right, or more to the left, but there is no step in between, how can I resolve this?

**Comment by DoctaWorm** [comment]
Gridstack at default deals with 12 columns, and those columns are at a set width, so you either snap to the column to the left or to the right. 

If you want you could try and control what the min-width is for each column. But I don't think that's what you want. I haven't tried anything above gridstacks default column count and I don't believe it's possible to do so with out running into issues.

**Comment by troolee** [comment]
You need to setup more columns for the grid to get step size you need. Please check the docs https://github.com/troolee/gridstack.js#change-grid-width
