### ISSUE TITLE
Parallely resize d3 pie charts while resizing widgets

### ISSUE THREAD

**Issue by satishsahani10** [troolee/gridstack.js#298]
I am using d3 charts inside the gridstack widget. How can i resize charts while resizing widgets

**Comment by radiolips** [comment]
You may hook into the `resizestop` event. 
```
$('.grid-stack').on('resizestop', function (event, ui) {
    var grid = this;
    var element = event.target;
});
```
If you'd prefer to do this in "parallel," as you specifically request, you may hook into the `resize` event instead. I'd caution though, that this will get fired many time. Let me know if you have any problems.
