### ISSUE TITLE
maintain aspect ratio

### ISSUE THREAD

**Issue by KevinSimple** [troolee/gridstack.js#304]
hi, I've made some changes to gridstack, which allows the widget maintain aspect ratio and user can set unit column height width in pixel, do you want merge my changes ?

**Comment by Servuc** [comment]
You should do a pull request ;)

**Comment by KevinSimple** [comment]
I think this project no ones maintain on it... ATM

**Comment by troolee** [comment]
Yes, please make a PR.

Thank you

**Comment by kschiffer** [comment]
@KevinSimple Hey, did this PR ever happen? I am interested in this.

**Comment by KevinSimple** [comment]
@kschiffer , no, i didn't do a PR, though i hope i could., i was tied to many projects, and moving to Angular 2, front-end world's changing so fast..

**Comment by mandys** [comment]
@KevinSimple interested in this. can you share the pointers at least ?

**Comment by KevinSimple** [comment]
@mandys @kschiffer , sorry guys, i left the company i worked on this feature, so i cant really do a PR any more, but i can tell you whats underhood happening, just calculate the grid item height/width ratio when grid initializing, then after, watch the grid container resize event, adjust each grid item to be the initial ratio, then its done.
