### ISSUE TITLE
Maximize and minimize button on widget

### ISSUE THREAD

**Issue by VishmayShah** [troolee/gridstack.js#305]
Hello,

I have put two button on every widget like 'Maximize' and 'Minimize'. I want a functionality like when i click on Maximize button, my widget resize to max height and all other widget set to new position accordingly and when i click on Minimize  button it will reset to min width and height and all other widget set to new position accordingly. Currently  my widget gets overlap to each other on maximize button click.

Pls help me if any one has solution. It's very urgent.

Thanks in advance.

**Comment by radiolips** [comment]
I see you have said this is urgent. I apologize for the delay, but we are now playing catch up. Could you provide the CSS/HTML you have? A jsfiddle would be great. I've been able to get this working by simply changing the CSS for the particular widget I'm maximizing.

**Comment by VishmayShah** [comment]
we have solved issue by dynamic adding and putting restrictions in codes and patches
thank you for reponce
