### ISSUE TITLE
Reloading gridstack without triggering updates

### ISSUE THREAD

**Issue by techypaul** [troolee/gridstack.js#306]
Hi,

We are using Gridstack as a multi-user dashboard. When one user makes a change on their computer, it changes for everyone else. We do this by polling our server for changes, comparing to current, then remove_all and looping add_widget to build the new one if required.

The destroying and adding the widgets back process triggers our ajax to send back all the changes to the server again.

Is there a way to reload dashboard quietly, or add_widget without causing the change trigger?

Paul.

**Comment by troolee** [comment]
Did you try to use `batch_update` & `commit`?

**Comment by radiolips** [comment]
There may be a bug in `batch_update` and `commit` (via #267). We will investigate tomorrow and will close this ticket when it's verified working.

**Comment by troolee** [comment]
It should be fine now.
