### ISSUE TITLE
Updating gridstack dependencies via bower breaks all

### ISSUE THREAD

**Issue by developingo** [troolee/gridstack.js#307]
Apparently the version change from lodash 3.5 to 4.0 introduces some backwards incompatible changes that makes gridstack stop working

https://github.com/lodash/lodash/wiki/Changelog

I've tested this with demo/knockout.html against lodash 4.0 and 3.10.1.

It breaks in 4:
![broken](https://cloud.githubusercontent.com/assets/790756/12334135/fdb46114-babd-11e5-8fc5-33e4f549d8fe.png)

And works on 3.10.1
![lodash-3 10 1](https://cloud.githubusercontent.com/assets/790756/12334130/f5632838-babd-11e5-9c82-b6729a62003a.png)

**Comment by jippi** [comment]
:+1: ! spend 3 hours debugging this

`lodash < 4.0` works fine

**Comment by vhiroki** [comment]
@jippi, me too. I've spent some hours trying to figure out what was breaking Gridstack. Thought that it was jQueryUI, but it was lodash.

Please, change this issue's name to something like: "overlapping widgets..."

**Comment by andrewr88** [comment]
#309 has the gridstack changes that will make lodash 4.0 work
