### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by jippi** [troolee/gridstack.js#311]
Hi,

Is this project actively maintained? seem to be a lot of open issues and PRs left to rot 

Are the owner not interested in the project, or simply overwhelmed by the popularity? 

Can the owner (@troolee) maybe use some help, from me or from some of the other active contributers

Best!

**Comment by artknight** [comment]
+1

**Comment by genachka** [comment]
+1

**Comment by DoctaWorm** [comment]
+1 

I've been waiting for v0.2.4 for past couple of months.

**Comment by zspitzer** [comment]
+1

**Comment by jippi** [comment]
ping @troolee :)

**Comment by str** [comment]
+1 I got here because the original gridster looks dead too.

**Comment by kdietrich** [comment]
+1 I've sent @troolee also an email.

**Comment by DoctaWorm** [comment]
I almost feel like we may need to make a new "official" fork. With more maintainers/contributors. I e-mail him as well back in December. I never got a reply.

**Comment by jippi** [comment]
I've made a fork that we can continue work on :)

https://github.com/jippi/gridstack.js  

poke me if you want commit-bit :)

**Comment by Alchnemesis** [comment]
+1

**Comment by jippi** [comment]
I've updated my fork to be an actual organization, to lift it above just one person / alias :) 

let me know if you want to have commit-bit to that :)

**Comment by str** [comment]
I see the issue got closed without any explanation. 

@jippi I see your fork. Have you applied any changes/pr to it or is it a mirror to this repo?

**Comment by genachka** [comment]
See #290 where @troolee has indicated that he's back to working on cleaning things up.

**Comment by jippi** [comment]
@str i just forked it directly from this repo yesterday

**Comment by jippi** [comment]
@genachka its great @troolee is back, but history show that the project is larger than him - would be great if he could share commit-bit to other contributers as well, so the project got less risk of stalling for 6months+ again :)

**Comment by artknight** [comment]
+1

**Comment by genachka** [comment]
@jippi I completely agree that this should be opened to additional committers. Whether he opens that up here, or on one of the forks like the one mentioned in #316, I agree it should be done. It would be a shame to continue having this happen on a project that has good potential.

**Comment by troolee** [comment]
I've setup slack chat https://gridstackjs.slack.com so if someone is interesting to be a part of the project — you're welcome. I would like to discuss the project milestones and main goals. So we can be on the same page.

To join: http://gridstackjs.troolee.com
