### ISSUE TITLE
Knockout, will_it_fit & remove_widget

### ISSUE THREAD

**Issue by MargoJunker** [troolee/gridstack.js#313]
How I can make grid like http://troolee.github.io/gridstack.js/demo/knockout.html
have 3 X 3 and will_it_fit controlling it??

And would like to know, what I need to do to get Delete Me button working on Float Grid Demo...

**Comment by troolee** [comment]
I didn't get you question.

Float grid demo is just to show what is floating mode. You can use `float` option with knockout demo and check how it works
