### ISSUE TITLE
add_widget should not add a widget if grid is full

### ISSUE THREAD

**Issue by str** [troolee/gridstack.js#315]
I set the height + width to have a max size. If I have a grid full if widgets and call add_widget once more, it creates a new row, but shouldn't

**Comment by MargoJunker** [comment]
this.add_new_widget = function () {
                    var node = this.items.pop() || {
                                x: 0,
                                y: 0 ,
                                width: 1,
                                height: 1
                            };
                    if (this.grid.will_it_fit(node.x, node.y, node.width, node.height, true)) {
                        this.grid.add_widget($('<div><div class="grid-stack-item-content"><a class="btn btn-default" id="delete_widget">Delete me</a></div><div/>'), node.x, node.y, node.width, node.height, true);
                    }
                    else {
                        alert('Not enough free space to place the widget');
                    }
                    
                }.bind(this);

                $('#add-new-widget').click(this.add_new_widget);

I dont know if this helps you, but it works on me...

**Comment by str** [comment]
Yea, in the end that's what I did.
