### ISSUE TITLE
Issue in serialize data (Save grid to array)

### ISSUE THREAD

**Issue by bhavin-imobdev** [troolee/gridstack.js#322]
Hello There,

I have used bellow code for get grid layout

    $('.grid-stack').on('dragstop', function (event, ui) {
        var items = [];

        $('.grid-stack-item.ui-draggable').each(function () {

            var $this = $(this);

            items.push({

                x: $this.attr('data-gs-x'),

                y: $this.attr('data-gs-y'),

                width: $this.attr('data-gs-width'),

                height: $this.attr('data-gs-height'),

                content: $('.grid-stack-item-content', $this).html()

            });
        });
    });

items array made perfect.but issue is x and y position.
It's return previews position of grid.

can you please fix this issue.

**Comment by kdietrich** [comment]
You should get attributes using the node:

    var node = $this.data('_gridstack_node');
    items.push({
       x : node.x,
       y : node.y,
       width: node.width,
       height: node.height
    });

**Comment by kdietrich** [comment]
You should use gridstack node to get attributes:

    var node = $(this).data('_gridstack_node');
    items.push({
       x: node.x,
       y: node.y,
       width: node.width,
       height: node.height
    });
