### ISSUE TITLE
How we can change drag placeholder

### ISSUE THREAD

**Issue by bhavin-imobdev** [troolee/gridstack.js#329]
Hello,

How we can customise drag place holder as per gridster.js (move step)

kindly help us for the same.

**Comment by radiolips** [comment]
Are you speaking of the dashed line around the widget when it's being dragged? If so, you may change or override the CSS. This section of `gridstack.css` may be what you're looking for:

```
.grid-stack .grid-stack-placeholder > .placeholder-content {
  border: 1px dashed lightgray;
  margin: 0;
  position: absolute;
  top: 0;
  left: 10px;
  right: 10px;
  bottom: 0;
  width: auto;
  z-index: 0 !important;
  text-align: center;
}
```

**Comment by bhavin-imobdev** [comment]
No I'm talking about move grid

my grid height and width 3 so My requirement is user only move min 3 step

currently user drag grid and grid passion is update only 1 column

**Comment by troolee** [comment]
Can you provide a sample? Or screenshot with how it works now and what you are expecting

**Comment by bhavin-imobdev** [comment]
![gridstack](https://cloud.githubusercontent.com/assets/11473733/13136150/158e0ab6-d63d-11e5-96da-ada43f2bb2e1.png)
![gridster](https://cloud.githubusercontent.com/assets/11473733/13136151/158ef26e-d63d-11e5-85cc-d873edcd2692.png)

I have send both images please check I want to move grid like gridster js

**Comment by chdeshpc** [comment]
Was there any update on this? Even I need something like this. I have columns with different column-width. And my placeholder is not moving along with dragging item.

I need help on this.

**Comment by david-trujillo** [comment]
Hi! Any updates? I’m working on something similar, but I can only control the item movement through drag events, but I’m having trouble controlling the placeholder movement

````
grid.on('drag', function (event, element) {
      const node = element.gridstackNode;
      if (node) {
          node.y = Math.round((node.y ?? 0) / 2) * 2;
          node.x = Math.round((node.x ?? 0) / 2) * 2;
      }
});
````
