### ISSUE TITLE
Non-resizable (readonly) component becomes resizable after window resize

### ISSUE THREAD

**Issue by aquirier** [troolee/gridstack.js#331]
1) Init gridstack component with jquery UI option resizable: { disabled: true }. Do not explicitly specify 'data-gs-no-resize' attribute for widgets
2) Make sure widgets are not resizable
3) Resize the size of your browser so that the width of the window is less than 768px so the component is shown in mobile phone size
4) Go the size of the browser back to full screen
=> Now user can change the size of widgets by dragging and dropping from low-right corner of a widget
Expected: The user should not be allowed to resize the widget in read-only mode

P.S. Specifying 'data-gs-no-resize' attribute for widgets seems to be a temporary workaround for readonly mode but the bug should be fixed in a normal way.

**Comment by radiolips** [comment]
Have you tried using the option `staticGrid: true`? Or, for your problem, do you want to allow moving and only disable resize?

**Comment by aquirier** [comment]
Hi, 'staticGrid' option is good solution in my case, thanks for the info, i'll try it! But I hope, my previous post is also helpful to make the component better. Thank you!

**Comment by radiolips** [comment]
Absolutely. Thanks for the feedback - we'll incorporate a fix for this in v0.2.5.

**Comment by aquirier** [comment]
Unfortunately, staticGrid: true option doesn't work for me.
I use last stable release version 0.2.4 + knockout.js.

**Comment by radiolips** [comment]
@aquirier for the latest stable version, you'll want static_grid. In version 0.2.5, gridstack is moving away from underscores in variable names, to follow better Javascript convention.

**Comment by radiolips** [comment]
Changing this to enhancement. Will add a new option for disabling resizable and draggable separately, without interfering with jquery-ui options. Fixes the problem and allows for new functionality (only drag or only resize).
