### ISSUE TITLE
Dependencies in RequireJS ignored

### ISSUE THREAD

**Issue by kafoso** [troolee/gridstack.js#332]
http://stackoverflow.com/questions/35480483/gridstack-js-not-loading-correctly-in-requirejs-using-underscore-js-jquery-and

I have provided the necessary dependencies. However, Gridstack still looks for Lodash and various jQueryUI components from what appears to be hardcoded paths, `/js/lodash.js` and `/js/jquery-ui/*.js`.

**Comment by radiolips** [comment]
I understand your issue.

jquery-ui is a massive library. As such, gridstack opts not to require the entire library. Instead, it requires only the small pieces it needs to run properly. In your SO question, you appear to have come across the solution yourself - use the AMD version of jquery-ui, which has the components separated into modules.

Gridstack itself is not looking for libraries in a hardcoded path. It is a default configuration, which you may certainly override. In your require.config, I see that you are including underscore. You may also include lodash, which I believe will likely solve your issue. Please let me know if this doesn't help or if you still have a concern.

**Comment by radiolips** [comment]
I'm closing this issue both because this information should provide helpful and additionally because some of these dependencies will be removed in the near future.

**Comment by kafoso** [comment]
All right, then. I'm not happy with it, but if that is how you choose to design your application, then that is completely fair.

Thanks for the quick response.
