### ISSUE TITLE
Widgets jump when widget area is large and is dragged from bottom.

### ISSUE THREAD

**Issue by tamisalex** [troolee/gridstack.js#335]
Don't know if this is an issue or if I am doing something wrong.

![launcher](https://cloud.githubusercontent.com/assets/5487505/13180272/bf2e9604-d6f5-11e5-8578-baf97f58f4f8.gif)

**Comment by radiolips** [comment]
This shouldn't be happening. It looks like you're using the float option? Take a look at http://troolee.github.io/gridstack.js/demo/float.html for a working example. If you still need help at that point, please reopen this and provide a jsfiddle for us to take a look at.
