### ISSUE TITLE
Viewport size for rows

### ISSUE THREAD

**Issue by str** [troolee/gridstack.js#338]
I'm using gridstack.js for a webapp that's being used in 55'' TV screens. Because the resolution changes from TV to TV, I found a way to define sizes based on the viewport. This way if I want to have grid with 3 rows, I was defining the rows with 
        cellHeight: '33.2vh',

vh is a viewport size described in https://css-tricks.com/viewport-sized-typography which is great because I can define each  row to be 33.2, which is 33.2% of the screen. 

I did a pull request https://github.com/troolee/gridstack.js/commit/b979982cc55afee72aeff7faaeacee096f4fbb7f  which was accepted but  then it was reverted.

Could anyone help me accepting the commit? If someone disagrees, could you please explain me why?

Thank you.

**Comment by radiolips** [comment]
@troolee put your code back in. Apologies!
