### ISSUE TITLE
Is it possible to put Bootstrap responsive tables into grids?

### ISSUE THREAD

**Issue by mvr1976** [troolee/gridstack.js#343]
Is it possible to get reponsive behaviour of Bootstrap-styled grid content on resize of a grid, nota viewport?

**Comment by radiolips** [comment]
I don't think I'm quite understanding you, @mvr1976. Could you provide some code or a jsfiddle? I'd be happy to help - I think the answer your question is, "Yes." but I'd like to provide you with more info.
