### ISSUE TITLE
Can't resize grid-item exactly.

### ISSUE THREAD

**Issue by minhphong263** [troolee/gridstack.js#345]
When I resize a grid-item, it changes dimension, but not exactly I want. Grid-item seem change dimension with height and width like fixed, not flexible.
Thanks so much!!!

**Comment by radiolips** [comment]
Could you explain more or possibly provide some code example? It sounds like you're asking about changing just width or just height, but both are supported and should not cause you trouble.

**Comment by minhphong263** [comment]
Hi @radiolips, sory for my question. Btw, thank your comment.
