### ISSUE TITLE
IE HierarchyRequestError in addWidget Method

### ISSUE THREAD

**Issue by dbleyenda** [troolee/gridstack.js#352]
Internet Explorer 11 throws "SCRIPT5022: HierarchyRequestError" when trying to append widget. 

I have debugged and narrowed the issue to this line: 
https://github.com/troolee/gridstack.js/blob/master/src/gridstack.js#L1002

I had googled a lot, this is the best explanation of SO.
http://stackoverflow.com/questions/1256394/what-exactly-can-cause-an-hierarchy-request-err-dom-exception-3-error/1258409#1258409

Any clues?

**Comment by radiolips** [comment]
I've got some ideas but don't have IE 11 access at the moment. If no one else beats me to it, I'll look into this tomorrow and get back to you. Thanks for bringing it to our attention, and apologies for the inconvenience.

And, damn, even after eleven major versions in, IE is still screwing up our internet...

**Comment by dbleyenda** [comment]
I really appreciate what you are doing, it means a lot to me! Tell me if I can be of any help solving the issue.

And yes, hopefully IE will disappear some day!

**Comment by radiolips** [comment]
Huh! This is working for me. Could you provide a JSfiddle, please? It sounds like either there's something fishy going on with your gridstack base or maybe a parameter being passed in is causing some sort of issue.

**Comment by dbleyenda** [comment]
@radiolips I will make a JSFiddle but it will take for me some time to reproduce as exactly as we face the bug in production.

In the meantime, here: http://data.cityofpaloalto.org/dashboards/8031/library/ is one link of our production environment that has the issue in IE 11.

For the record, we use v0.2.3. I have tested in my development environment using the lastest version of your code (0.2.4), but it stills reproduce the problem. Also, in another part of the app (that requires credentials to access it) we are using a newer version of jQuery, backbone and underscore, and it has the same issue with adding the widget to the grid in IE 11.

**Comment by radiolips** [comment]
Thanks! I've verified that I have the same problem as you do on IE11. However, I'm able to get gridstack to work properly in IE11 outside of the site you linked.

In the console I'm getting an error about an unmatching tag. Something as small as that could be causing IE11 to disallow the element from being added to the page. Unfortunately, there are a lot of lines in your source, so it's rather difficult for me to track down, but I have a hunch that fixing that may fix your problem.

**Comment by dbleyenda** [comment]
Unfortunatelly, I have already tried that, and that does not solve the issue.

There is something between the append() that does stackGrid on addWidget method and the element that receives the appended code.

Will continue checking.

Thanks!

**Comment by radiolips** [comment]
Keep me posted on this and let me know how I can help. As I said, I'm able to get this working in IE 11 with a new gridstack, even with `add_widget` in `v0.2.4`. Could you try making a new blank page with just a gridstack and have it add widgets? It should work and will be a better starting point.

I understand what you're asserting about the way gridstack is adding the node to the DOM, but I assure you that I've been able to run this successfully in IE 11.

**Comment by dbleyenda** [comment]
@radiolips We resolve the problem, but as we said before IE is a bag of shit. 

There is a reserved name "item" that we were using anda caused the issue, but it didn't complain of that. Instead it complained in the append. Debugging with the tool of IE (which is awful) we get there and notice the "item" variable wasn't behaving as expected.

FYI, http://stackoverflow.com/questions/29253542/implicitly-global-item-variable-difference-between-internet-explorer-and-fir

Thanks a lot for your help!
