### ISSUE TITLE
Links inside gridstack item not registering "focus" event on left click

### ISSUE THREAD

**Issue by jjim50** [troolee/gridstack.js#356]
I stumbled upon a bug while trying to place a Bootstrap popover inside a gridstack item. It seems that left click "focus" events aren't being registered but right clicking raises it normally even though there's `role="button"`.

A minimal test case is the following:

`<div class="grid-stack-item-content">
        <a tabindex="0" class="btn btn-lg btn-danger" role="button" data-toggle="popover" data-trigger="focus" title="Dismissible popover" data-content="And here's some amazing content. It's very engaging. Right?">Dismissible popover</a>
    </div>`

`$('[data-toggle="popover"]').on('focus', function(e) {
        console.log('focused');
      });`

When you left click nothing is logged to the console. Right click and all is good. Removing the element from gridstack html markup fixes the problem.

**Comment by radiolips** [comment]
Could you throw this into a jsfiddle? gridstack should bubble up click events. I've got all kinds of crazy stuff inside of a gridstack item and haven't had problems. If you could put a running example together, I'd be happy to help.

**Comment by jjim50** [comment]
https://jsfiddle.net/ctto3m1n/6/
This is pretty much the setup I'm using now, only that I attach the popover to the body.
Another interesting thing I saw while putting this example together is that if I shrink the result pane width until the panels occupy 12 columns, the popovers work. If the result pane width is such that the panels are side by side, the focus event isn't triggered.

**Comment by radiolips** [comment]
I'm getting an error in the console with this fiddle. Looks like you may be missing lodash, perhaps? Could you fix it up? I have some idea of what may be causing an issue, but if we have a small play area (jsfiddle!) where we can make sure we're seeing the same thing, we'll know it to be working.

**Comment by jjim50** [comment]
Fixed, sorry I neglected to update.

**Comment by radiolips** [comment]
It's still giving me that error in the console when I go to the link you had posted:

https://www.dropbox.com/s/rchg61m2sjvn75u/Screenshot%202016-02-24%2009.24.58.png?dl=0

**Comment by jjim50** [comment]
https://jsfiddle.net/jjim50/h18c2fae/5/
This should work, sorry again.

**Comment by radiolips** [comment]
It appears that jquery-ui is swallowing up the focus. I'm sure this is related to resize and/or drag. However, you may get around this easily. Change `data-trigger="focus"` to `data-trigger="focus click"`. Let me know if that helps.

**Comment by jjim50** [comment]
Changed it, it works on click now but clicking outside the popup doesn't dismiss it. This is a problem because I attach the popup to the body. The popup has a a button inside that triggers a modal. Modal displays but the popup z-index positions it above the modal.

So I'll have to go bug hunting in jquery-ui most likely?

**Comment by radiolips** [comment]
I think that might be the case, unfortunately. One option you could try is to set the grid to not be resizable or draggable when you click on the popup. Then, when the popup is exited, you could again allow it. The easiest way to do this is probably to use the `setStatic(true)` method, then `setStatic(false)` when you're done. I haven't tried this out, but I'd imagine it would work.

Just a quick note - this method will only work in `v0.2.5-dev`. It's a feature/bug fix that was added recently.

**Comment by jjim50** [comment]
For reference, another workaround would be to use a `<button>` tag instead of `<a>`.
