### ISSUE TITLE
Widgets appearing in wrong positions when adding multiple widgets with x,y

### ISSUE THREAD

**Issue by jbrevel** [troolee/gridstack.js#362]
I have been saving widget details to a json structure and then trying to load based on this structure. When looping through and adding the widgets the do not load into the correct positions. I have auto position set to false and have specified x,y,width and height for each. Heres some code:

```
//function to load widgets
$.each(b, function (a, b) {
         addWidget(b);
 });
```

```
//function to add widget to gridstack
function addWidget(obj) {
        var grid = $('.grid-stack').data('gridstack');
        
	el = $('<div class="grid-stack-item"><div class="grid-stack-item-content" id="'+obj.reportWidgetDetails.id+'" title="header">'+obj.reportWidgetDetails.header+'</div>'); grid.add_widget(el, obj.reportWidgetDetails.x, obj.reportWidgetDetails.y, obj.reportWidgetDetails.width, obj.reportWidgetDetails.height, false);
      
    }
```

```
//heres an example of json
{"widget1": {
	"reportWidgetName": "widget1",
	"reportWidgetDetails": {
		"id": "widgetIlvexI9X1",
		"title": "widget1",
		"height": 8,
		"width": 4,
		"y": 0,
		"header": "widget1",
		"x": 0
	}
},
"widget2": {
	"reportWidgetName": "widget2",
	"reportWidgetDetails": {
		"id": "widgetIlvexI9X2",
		"title": "widget2",
		"height": 8,
		"width": 4,
		"y": 0,
		"header": "widget2",
		"x": 2
	}
},
"widget3": {
	"reportWidgetName": "widget3",
	"reportWidgetDetails": {
		"id": "widgetIlvexI9X3",
		"title": "widget3",
		"height": 8,
		"width": 4,
		"y": 30,
		"header": "widget3",
		"x": 0
	}
},
"widget4": {
	"reportWidgetName": "widget4",
	"reportWidgetDetails": {
		"id": "widgetIlvexI9X4",
		"title": "widget4",
		"height": 8,
		"width": 4,
		"y": 30,
		"header": "widget4",
		"x": 2
	}
}
}
```

Any help would be very much appreciated!

**Comment by radiolips** [comment]
I love JSON. Would you mind tossing all of this into a jsfiddle for me and get a running example? I will be happy to help get this working to your liking.

**Comment by Julienng** [comment]
this [fiddle](https://jsfiddle.net/Julienng/1o2jbsk3/) have the problem with dom initialization of card position

**Comment by jbrevel** [comment]
You can see from this [https://jsfiddle.net/jbrevel/4c0L5s0w/1/](url) that the "Text Row6 Column2" is appearing down on row 8. Seems to happen randomly and not seeing why. Also, I have named all widgets to show what row and column they should appear on. Thanks in advance.

**Comment by radiolips** [comment]
This is happening because there's no guarantee of the order of the widgets. You want to use `batch_update` (or `batchUpdate` in `v0.2.5-dev`).

```
  var grid = $('.grid-stack').data('gridstack');
    grid.batch_update();
    $.each(json, function (a, b) {
        $.each(b, function (c, d) {
            addWidget(d);
        });
    });
    grid.commit();
```

`batchUpdate` will force gridstack to wait until `commit` to actually push things to the DOM. The elements are pushed toward the top, so if row 5 is not there prior to row 6, it's possible for an issue to occur. Alternatively, you could set float to true temporarily.

**Comment by jbrevel** [comment]
Thanks radiolips, I'll give it a go and see if I can get it working 😊

**Comment by jbrevel** [comment]
This worked great, thanks!!

**Comment by vipulpatil001** [comment]
Hi All,

I am facing the same issue, I have updated my code accordingly above but it's not working for me, can any one help me to sort out this problem.

Thanks in advance...!!!

**Comment by itsmrhuter** [comment]
I had this same issue happen after adding multiple widgets and then adjusting the grid columns. To resolve this I simply set the grid column value before adding widgets and then they would be inserted into their correct positions.

**Comment by adumesny** [comment]
@itsmrhunter changing the column could WILL reposition/resize widgets by design (unless you pass ColumnOptions='none' and items do fit)

**Comment by itsmrhunter** [comment]
@adumesny Ahh ok that makes sense! I was just encountering an extremely similar result as OP and when I figured out what was happening I thought I would post it here just in case anyone else runs into the same thing.
