### ISSUE TITLE
Widgets overlapped when using addWidget() with auto=true

### ISSUE THREAD

**Issue by Framnk** [troolee/gridstack.js#366]
Hi, I just recently upgraded to 0.2.5-dev from 0.2.4-dev and everything seems fine except that for some reason when dynamically adding widgets using the addWidget() method with auto=true, it seems to be not auto positioning anymore and overlapping my widgets on top of each other at 0,0.

In 0.2.4-dev I would call addWidget() with a position of 0,0 and my default width and height and let autopositioning put the widget in the appropriate location.  This doesn't appear to work anymore in 0.2.5

**Comment by Framnk** [comment]
Sorry, this appears to have been some kind of CSS issue

**Comment by tracyalison11** [comment]
What was your CSS issue?
