### ISSUE TITLE
Iframe inside gridstack card block resize

### ISSUE THREAD

**Issue by Julienng** [troolee/gridstack.js#379]
Hi,
I have configurable components inside one of my card. All `super user` can define a dynamic content for a particular context into the application. To be sure that an error cannot crash all the page, the content is load inside an iframe.

I create a simplified jsfiddle to reproduce the problem: [https://jsfiddle.net/Julienng/bacgnfut/](https://jsfiddle.net/Julienng/bacgnfut/)

Try to resize diagonally the biggest card (number 3) to reproduce the error on jsfiddle.

edit: the third card should have a `#teest valuueeee` content into the iframe. Run again the jsfiddle if missing.

**Comment by troolee** [comment]
It seems to be a problem with jQuery UI resizable. You can resize it slowly but if mouse gets over iframe mouse events stop go to resizable element.

Can you please try to reproduce this not with gridstack but only using resizable. Or I can check this later...

In case if it's issue with jqui resizable you should do some workaround with you layout: for instance add some padding between widget edges and iframe. I've tried to set editor's width to 90% and it worked fine.

**Comment by troolee** [comment]
As I thought it is an issue with jquery ui resizable. Please check out this demo https://jsfiddle.net/j2kjqst0/

**Comment by Julienng** [comment]
Hi, I couldn't try yesterday sorry. I will add some padding or block resizable for this component. I go report the bug to JQuery. Thanks for your help
