### ISSUE TITLE
can't float after remove one widget

### ISSUE THREAD

**Issue by iamwelk** [troolee/gridstack.js#381]
first, the grid is look like this
![image](https://cloud.githubusercontent.com/assets/6983075/13490569/773558d8-e168-11e5-9c26-959167d84bd2.png)
after remove the gird with no chart, it become 
![image](https://cloud.githubusercontent.com/assets/6983075/13490616/bb0516ca-e168-11e5-8671-1403618fa126.png)
the question is:
why the last item doesn't float to last row,here is my option
```
var options = {
    cell_height: 80,
    float: true,
    resizable: {
        disabled: true
    }
};
$('.grid-stack').gridstack(options);
```

**Comment by radiolips** [comment]
Hello, @iamwelk! I'd be happy to help you, though you may not love the response.

The `float` option allows for widgets to be placed anywhere - I think this may be different than what you are thinking. You may write code to to what you'd like, though. If you add a widget with the `autoPosition` property set, it will go to the first available spot. In this case, if you remove then add the widget on the second line, it will be re-added to the first line.

**Comment by iamwelk** [comment]
@radiolips  Thanks for your help. Maybe it could have a refresh function to rearrange the items after remove one of those items. I think this can be usually used~
