### ISSUE TITLE
Resize handles color

### ISSUE THREAD

**Issue by jan-krakora** [troolee/gridstack.js#383]
Since version 0.2.5 you have dropped dependency on the FontAwesome and you are using svg background image for resize handles.

How can one change color of those resize handles now?

**Comment by troolee** [comment]
Yes, we removed dependency of FontAwesome because a lot of people don't use it in their projects and have it for only one icon is overhead.

To customize how resizing handle looks like you can override CSS for `.grid-stack > .grid-stack-item > .ui-resizable-se`.
