### ISSUE TITLE
How use in Angular 2?

### ISSUE THREAD

**Issue by LPalmito** [troolee/gridstack.js#384]
Is there any sample of code where it is used for Angular 2?

Thanks a lot!

**Comment by kdietrich** [comment]
We have an Angular.js port available at: https://github.com/kdietrich/gridstack-angular.
I'm certain that we will update this port when Angular 2 is in a more stable release state. Meanwhile you can use this port for Angular 2 using `ngUpgrade`. Maybe it is a good idea to open an issue at `gridstack-angular` to track this request at the right place.
