### ISSUE TITLE
A check before jQuery UI related functions

### ISSUE THREAD

**Issue by gausarts** [troolee/gridstack.js#389]
First of all, thank you for your great work ;)

As mentioned in #173 and #144, there have been requests to decouple GridStack from jQuery UI.
I understand a full decoupling will require a lot of work, but that will be a great plus when it happens ;)

FYI, I am currently working on a Drupal 8 module to integrate with your plugin, and have similar point like the other threads: Admin editable, but front end static.

The addition of staticGrid option helps this, however I noticed JS errors when no jQuery UI is loaded.
At ~line 875 no check is run prior to calling `.draggable` and `.resizable`. The issue is resolved once I add a check:
`if (this.opts.draggable || this.opts.resizable) { ....`

I am not sure about any better check up there.
I wonder if you could incorporate the fix into the next release?

I would also love to hear if jQuery UI decoupling is on the roadmap?
Sorry if I missed any other related thread to this issue. The above two mentioned are the closest I found by now.

Thanks again.

**Comment by radiolips** [comment]
Let's start with the juicy stuff: part of the gridstack roadmap is to get rid of _all_ dependencies, not just `jqueryui`. There will be a plugin system, initially just for drag/resize, and we'll kickstart it by providing two or three options for drag/resize. As part of that, we will necessarily have to accomplish the query you're asking about.

There are a couple ways to enable/disable drag and resize. That makes it awfully easy to do a small fix like the one you're proposing but end up in a weird state.

Perhaps it's worth adding in a variable that holds the status of whether or not draggable/resizable are allowed, independently. These can be checked before any call to `.draggable` or `.resizable` are made.

Our "next big thing" is definitely to build out the plugin system, but just in case it doesn't make it into `v0.3.0`, I would be happy to implement exactly what you're asking for.

**Comment by gausarts** [comment]
Awesome, glad to hear it is on the roadmap ;)
Thank you for any possible short term fix on this as this is likely one of the most wanted features when I release the module. Truly appreciated.

**Comment by radiolips** [comment]
Closing. This has been resolved.
