### ISSUE TITLE
I can't use resize method

### ISSUE THREAD

**Issue by ourterr** [troolee/gridstack.js#39]
Hi, when I use grid.resize($('.grid-stack-item[data-gs-x="0"]'), 3, 4); it gives me errors

**Comment by troolee** [comment]
Hi,

what kind of errors? I've just run your code and it worked with no issues. Which browser do you use?

**Comment by ourterr** [comment]
I want create site with 3 columns. 1, 3 columns will have fixed size of widgets and work as sortable (jquery ui). Second one work as gridstack. This is my example 
![gridstack](https://cloud.githubusercontent.com/assets/7116501/5617832/9d3ae3d0-9534-11e4-915a-e6396c01f978.png)
and how it works now http://marketop.org/gridstack/2.html
