### ISSUE TITLE
Clone node on drop

### ISSUE THREAD

**Issue by notbear** [troolee/gridstack.js#396]
I'm trying to make an application where items can be **copied** from the palette to the canvas. For now gridpack supports only moving between grids. I hoped that it would be enough to remove line 785 from v0.2.5 which removes the source of element, but it leads to undesired behaviors when I try to copy the  element from palette into canvas two or more times.

Example: http://codepen.io/NotBear/pen/EKyYqB/

Please advice

**Comment by troolee** [comment]
Try to unbind all events handlers and data attributes of cloned item

**Comment by notbear** [comment]
Thanks, I will try and let you know.

**Comment by AndrewKerton** [comment]
Did you find a solution to the problem?

**Comment by notbear** [comment]
@attractivePoop I'm sorry, but not. My team resigned from gridstack due to changed requirements.

**Comment by attractivePoop** [comment]
Thank you for the response.

**Comment by mcelligottnick** [comment]
@troolee  @attractivePoop I have solved this with a faux clone implmentation - https://gist.github.com/mcelligottnick/2d17a65615eb54b1c744050cb31ed028

**Comment by redstubble** [comment]
@troolee I am hitting this same issue. I have tried to unbind all attributes and events to no avail can you provide a snippet to point me in the right direction.

**Comment by radiolips** [comment]
We'll take a look at adding this ability into `v.0.2.7` so that no hacky workaround will be required

**Comment by Kamshak** [comment]
Also looking for this, has anyone found a workaround for this?

**Comment by nelsonad** [comment]
Hey all, I ran into this issue too and posted my fix before I saw this issue. 

#542

**Comment by AurelDragut** [comment]
Guys, what do you think about reloading the source grid's content on drag start?

**Comment by radiolips** [comment]
This will be available in some form or another in `v1.0.0`. Please check [my blog](https://dylandreams.com/) for more information. I'll post in the next few days about how this will work.

**Comment by radiolips** [comment]
This works on the `develop` branch now. Please be sure to use `draggable` setting `helper: clone`.

**Comment by tanobi92** [comment]
Hi @radiolips , I tried to use setting helper: clone for draggable in example two.html, but failed. I downloaded new version 1.0.0. Help me! Thanks!

**Comment by abayob** [comment]
@tanobi92 It works fine here! What is your code, how are you using it? What do you expect should happen?

**Comment by tanobi92** [comment]
Oh @radiolips , I use file gridstack.all.js in folder "dist" when it runs, and I use gridstack.js when it fail.
