### ISSUE TITLE
Items disappear in multiple-grid after dragging

### ISSUE THREAD

**Issue by AlienRSV** [troolee/gridstack.js#397]
When I have multiple grids (12 in this case) and the same amount of items in all the grids (5), the items sometimes disappear on dragging.
[demo.zip](https://github.com/troolee/gridstack.js/files/169178/demo.zip)

The Javascript error: "TypeError: n.el is null" in gridstack.js, row 585. col 21.

**Comment by eagoo** [comment]
this bug should be fix first

**Comment by eagoo** [comment]
there is a serial bug when multi grid on droppable 
$(self.container).droppable({
...
out: function(event, ui) {
                    var el = $(ui.draggable);
                    var node = el.data('_gridstack_node'); //eagooqi
                    if (node && node._grid != self && node._added) { //eagooqi if not self and is _added by drag accept el
                        el.unbind('drag', onDrag);

                        node.el = null;
                        self.grid.removeNode(node);
                        self.placeholder.detach();
                        self._updateContainerHeight();
                        el.data('_gridstack_node', el.data('_gridstack_node_orig'));
                    }
                },

**Comment by radiolips** [comment]
Thanks again, @eagoo . Just to keep things tidy, I'm closing this in favor of #451 as well. We'll be sure to resolve all of these bugs.

**Comment by Senthil880** [comment]
Hi @radiolips  Still Disappearing issues facing in gridstack1.0 while widget moving from one grid to another. Please do need full.
and im using gridstack-angular .Thanks in advance

**Comment by radiolips** [comment]
Hey @Senthil880 . Use #451 for commenting, please. Also, we don't directly support gridstack-angular, so if you have issues specific to that, you'll want to post on that github.

**Comment by Senthil880** [comment]
#451  Thanks. Even though we using gridstack.js using Jquery while we dragging the item from one grid to another for 5-10 times some of items are get disappear from the grid
i.e Grid1 has 5 items as well Grid2 has 5 item while we playing around from one grid another some of items disappear finally we have 8 or 9 items in both grids.Please look in this example http://gridstackjs.com/demo/two.html
Thanks..

**Comment by pavan-suthar** [comment]
Hi,
I have also a same bug, it was happening in nested, it was disappearing while dragging from one parent to another parent.
I worked on debug in and got the reason.

its due to same class on parent and nested gridstack items. please keep the different class for parent and nested.


<code>
let gridMain = GridStack.init({
				itemClass		: "grid-stack-parent",
			}, '.grid-stack.main');
</code>

**Comment by adumesny** [comment]
@pavan-suthar do you mind filling a separate bug with example showing the issue still happening with latest code ?
the disappearing when dragging between siblings (two.html) should have been fixed (even when doing fast) by myself, but I have not heard about issue when nested...
