### ISSUE TITLE
unwanted "cloned" handle adding to existing div. 

### ISSUE THREAD

**Issue by jm06487** [troolee/gridstack.js#399]
When I drag a widget to another grid stack parent.  The drop is successful, but my re-size handle is added again, and adds a new one every time i move it to another parent.

Example,

- div data-gs-x="0" data-gs-y="0" data-gs-width="3" data-gs-height="2" class="grid-stack-item ui-resizable ui-draggable ui-resizable-autohide""
- div class="grid-stack-item-content ui-draggable-handle"></div>
- div></div>
- div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90; display: none;"></div>
- div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90; display: none;"></div></div>"

**Comment by radiolips** [comment]
Thanks, @jm06487. You're using a very experimental feature. As we move forward with gridstack.js, we hope to enhance and fix. Thanks for the feedback. This will be logged and the ticket will be updated when the issue has been resolved.

**Comment by jm06487** [comment]
a solution has been found on similar requests.. Thank you.

**Comment by mspruthv** [comment]
@jm06487 : Can you please post the solution for this issue ?
