### ISSUE TITLE
Grid Width and Height

### ISSUE THREAD

**Issue by ArribaArriba** [troolee/gridstack.js#400]
Hi
Try the following:
`<div style="max-width:600px; max-height:850px;width:600px; height:850px; border: 1px solid">
			<div class="grid-stack" data-gs-width="100" data-gs-height="100">
			</div>
        </div>`
	
....
`$('.grid-stack').gridstack({float:true;cellHeight:5;verticalMargin:1});
$('.grid-stack').data('gridstack').addWidget($('<div><div class="grid-stack-item-content">' + i + '</div></div>'),30, 10, 14, 20);`

The widget cannot be dragged below 599px (height) ! The only correct way to get it beyond that point is to put data-gs-height="142", because 142=850px/600px

Another issue: any verticalMargin value greater than 1 modifies the 599px water mark and we can go way beyond 850px. Why ?

Finally inverting width and height (width=850px, height=600px) in the HTML works fine without the 142 trick.

The 599px let's me think that somewhere in the code height is used as width, or vice versa.

Regards
Fadi

**Comment by radiolips** [comment]
Could you provide a jsFiddle? Additionally, #405 provides insight into a verticalMargin issue. I believe this is causing at least part of your issue.

**Comment by ArribaArriba** [comment]
I've solved the problem by setting data-gs-width=100 and data-gs-height=$('.grid-stack').parent().height() / (options.cellHeight + options.verticalMargin)

This said I'm wondering how this setting reconciles with the defined css, for I defined:

.grid-stack > .grid-stack-item[data-gs-x='n'] { width:n%;}
.grid-stack > .grid-stack-item[data-gs-y='n'] { width:n%;}
.grid-stack > .grid-stack-item[data-gs-width='n'] { width:n%;}
.grid-stack > .grid-stack-item[data-gs-height='n'] { width:n%;}

with n going from 1 to 100. "data-gs-height" is often different from 100 with the above formula.
