### ISSUE TITLE
Doesn't work on mobile devices

### ISSUE THREAD

**Issue by javayoung** [troolee/gridstack.js#401]
Working fine on desktop computers but can not drag on mobile devices. Thanks

**Comment by zatchgordon** [comment]
Did you include touch-punch.js?
This library is supposed to automatically make dragging work on mobile devices.

**Comment by troolee** [comment]
Most probable you didn't include touch-punch.js. JQuery UI doesn't work properly on mobile devices without this library.

Please feel free to re-open the issue if you still experiencing the problem after all.

**Comment by zgmunshi** [comment]
I have added touch-punch.js but it's still not working on mobile devices.
