### ISSUE TITLE
Reload options on the fly

### ISSUE THREAD

**Issue by ChristianRinne** [troolee/gridstack.js#402]
Hello,

is there a way to reload the grid options on the fly?

Lets say i start the grid with:
`            var options = {
                width: 25,
                min_width:1200,
                vertical_margin: 1,
                animate: true,
                always_show_resize_handle: false,
                cell_height: 5,
                resizable: {
                    handles: 'se, sw, ne, nw'
                }
            };`

and after i push for example F3 animate should go to false

Is there a way? (without setAnimation - Iam using an older version)

Thanks a lot

**Comment by troolee** [comment]
No. You can patch you version and add `setAnimation` functionality.
