### ISSUE TITLE
Widget/Blocks fill whole grid space

### ISSUE THREAD

**Issue by gitn00b1337** [troolee/gridstack.js#403]
Hi, this library looks great. I'm just getting started and am integrating knockout models, but don't want to use a knockout component as it causes other issues. I am finding when I populate the grid with elements all the elements seem to get a width of the whole grid and it doesnt know what to do with them. I have found the exact same issue here http://jsfiddle.net/m3qj3qs1/1/ from someone else trying to modify the demo. 

Is there a reason for this? I can provide my own code if it's possibly a bug. Many thanks

**Comment by gitn00b1337** [comment]
Noticed on the supplied link there's a gridstack missing error ... go figure. In my code it's all good though

<h2>Grid Stack Test</h2>
<div id="toolbox">
    <div id="widget" style="width: 100px; height: 100px; background: red;"></div>
</div>

<button data-bind="click: $root.populateGrid">Populate</button>

<script>
var appModel = function() {
    var self = this;

    this.options = {
        cellHeight: 80,
        verticalMargin: 10,
      //  float: true,
        auto: false
    };
    // element
    this.$grid = $('#grid-stack').gridstack(self.options);
    // gridstack object
    this.grid = self.$grid.data('gridstack');
    this.widgets = ko.observableArray([]);

    this.populateGrid = function () {
        self.widgets(widgets);  
    }

    this.deleteWidget = function () {
    }

    this.afterAddWidget = function (items) {
        var item = _.find(items, function (i) { return i.nodeType == 1 });
        self.grid.makeWidget(item);
        ko.utils.domNodeDisposal.addDisposeCallback(item, function () {
            self.grid.removeWidget(item);
        });
    }

}

$(function () {
    app = new appModel();
    ko.applyBindings(app);
})

var widgets = [
                { x: 0, y: 0, width: 2, height: 2 },
                { x: 2, y: 0, width: 4, height: 2 },
                { x: 6, y: 0, width: 2, height: 4 },
                { x: 1, y: 2, width: 4, height: 2 }
];
</script>

**Comment by radiolips** [comment]
@gitn00b1337 I'd love to help, but if you could fix the jsFiddle error, it'd be of much assistance. I apologize for the inconvenience, but could you get that working? I'll then look into it promptly.

**Comment by gitn00b1337** [comment]
A more than fair request. I was going to make a sample with my code, but after fixing the js link I sent (just old references) it seems to still be a problem. From what I can tell there's an issue with the CSS 
http://jsfiddle.net/byL1ep6a/1/
Thanks for your time

**Comment by troolee** [comment]
Because of small width, gridstack collapses to one column mode therefore you see all widgets with 100% height. Please check `winWidth` option to disable this behaviour https://github.com/troolee/gridstack.js/tree/master/doc#options
