### ISSUE TITLE
Something is wrong with cellHeight

### ISSUE THREAD

**Issue by parthbhagat** [troolee/gridstack.js#405]
Hello @troolee ,

I am using gridstack v0.2.5 with jQuery v1.11.1, jQuery UI v1.10.4 and bootstrap v3.2.0.

I am exploring gridstack to display resizeable and drag-drop enabled dashboard widgets.

Here something strange I've observed. Please find code snippet below.

> < style type="text/css">
> 	.grid-stack {
> 		background: #f5f5f5;
> 		width: 80%;
> 	}
> 	.grid-stack-item-content {
> 		color: #2c3e50;
> 		text-align: center;
> 		background-color: #18bc9c;
> 	}
> </ style>
> < script>
> $(function () {
> 	var options = {
> 		cellHeight: 1,
> 		verticalMargin: 1,
> 		width: 3,
> 		auto: false,
> 		handleClass: 'widget-title',
> 		resizable: {
> 			handles: "e, s",
> 			grid: [330, 50],
> 			helper: "resize-helper"
> 		}
> 	};
> 	$('.grid-stack').gridstack(options);
> 	var grid = $('.grid-stack').data('gridstack');
> 
> 	var template = '< div class="widget-component" id="widg">< div class="grid-stack-item-content">< div class="widget-title" style="background-color: blue; color: white; height: 40px;">' + 3 + '</div><div>< h1>This is content</h1></div></div></div>';
> 
> 	grid.addWidget($(template), 0, 0, 1, 200, false);
> 	grid.addWidget($(template), 0, 1, 1, 1, false);
> 	grid.addWidget($(template), 0, 2, 1, 1, true);
> });
> </ script>

When I run above code then first widget (widget with height = 200), having actual height of 399 pixel. Here is the derived height from chrome: 
`.grid-stack-instance-5517 .grid-stack-item[data-gs-height="200"] {
    height: 399px;
}`

If we consider cellHeight and verticalMargine, height of widget should be 200 pixel. But it looks like something is going wrong. Probably, it is considering verticalMargin as well, that is why it is doubled to what cellHeight is.

If I set cellHeight = 1 and verticalMargin = 10, then height of the widget derived is:
`.grid-stack-instance-9343 .grid-stack-item[data-gs-height="200"] {
    height: 2190px;
}`

Let me know if my understanding is wrong at some point/s.

Here is jsFiddle [link](https://jsfiddle.net/hgf3zvbh/).

**Comment by radiolips** [comment]
Thanks for the jsFiddle, it was extremely helpful. I agree, there appears to be some screwy logic here. The vertical margin should be a constant, but is instead multiplied by the height. We'll look into this.

**Comment by Rapheer** [comment]
I'm having this problem too, is there an development on the subject? some workaround that I can use or even something that I need to adjust?

**Comment by brunolanova** [comment]
+1

**Comment by armensg** [comment]
+1 this issue

**Comment by radiolips** [comment]
I've given this a lot of thought, and I've tried several options, but I've concluded that what we currently have is correct. The "formula" is (`widgetHeight` * (`cellHeight` + `verticalMargin`) - `verticalMargin` = widget height in px.  One `verticalMargin` is deducted from the height because it needs to leave a gap at the bottom. Including all of the `verticalMargin`s in the height is what keeps the grid looking like a grid.

However, I believe I have found one very minor bug while investigating this, but it's unrelated to your issue.

I hope this information helps. Please let me know if there are any issues.

**Comment by ivansborn** [comment]
Hi, I have one problem. I have to change dynamically verticalMargin, and if I do that, items increases height. How can I use this formula and where? I need to have same items size,  but different size of verticalMargin. How can I do that if I have similar code like @parthbhagat jsfiddle? Thanks.
