### ISSUE TITLE
Widget packing 

### ISSUE THREAD

**Issue by TheChifer** [troolee/gridstack.js#406]
I am using gridster for building a dashboard, dashboard will support adding, removing, moving & resizing of widgets. Gridster does everything I want & is quite a comprehensive framework. However I wonder if I can achieve better packing(less empty spaces) of widgets specially when you move them around. In this gridster demo
http://gridster.net/ , when you move a widget the whole grid is NOT rearrange for better packing. However something like freewall - http://vnjs.net/www/project/freewall/ does a full grid rearrange and ends up with much better utilization of space.

Gridster does support auto position in addWidget() which works nicely.How can I achieve better packing with gridster when resized, moved or delete of widgets?

**Comment by somchaisomsi** [comment]
I think you are in the wrong section buddy! this is gridstack not gridster!  :)
