### ISSUE TITLE
Cant move widget to another grid-stack after it has been added to one (nested stack)

### ISSUE THREAD

**Issue by MartinA1** [troolee/gridstack.js#408]
I have 2 gridstack regions where I can drop widgets. I have configures them to accept widgets with class '.grid-stack-item.widget'. The problem is that when I drop the widget into one gridstack, I can only move it inside that gridstack.

Am I doing something wrong ? I have tried to approach this from every possible angle I can imagine. Any help is appreciated.

Test situation (with codepen example):

Drop a widget from "Widget UI" To one of the drop regions (marked green).
Now try to drag that widget into the second drop region (the other green area)
You will see that you are unable to move it there although if you had dropped it there in the first place the region would have accepted the widget. 

http://codepen.io/dolorsitamet/pen/ONjEmg

**Comment by radiolips** [comment]
Closing. We will keep #451 open, as it mentions a few issues, all related.
