### ISSUE TITLE
Only Draw Needed CSS Classes

### ISSUE THREAD

**Issue by mgwidmann** [troolee/gridstack.js#41]
With a high `data-gs-max-height` (and large widgets on the page) it can make resizing and initial load less performant. 

For all nodes, just draw the CSS classes +/- 10 `cell_height`s.
[This loop](https://github.com/troolee/gridstack.js/blob/master/src/gridstack.js#L428) causes the performance problems when `max_height` is something like `10,000` for example, that loop makes resizing extremely glitchy.

**Comment by mtyeh411** [comment]
+1

**Comment by troolee** [comment]
I will check this. Thank you for your feedback.

**Comment by troolee** [comment]
Guys,

Can you confirm the issue on the latest source code? If so, please share your configuration, your browser and widgets amount.

I've just tried with `max-height` of 100,000 and `cell_height` = 1 and everything was working fine.

**Comment by mgwidmann** [comment]
I had pretty severe issues with just `10,000` and `cell_height` of 1. I haven't had a chance to test it myself but I'd say that its good if you tried with 100k. :+1:

**Comment by troolee** [comment]
Please re-open the issue if you experience the bug again.

Cheers.
