### ISSUE TITLE
removeWidget without detaching Node won't reflow the other widgets

### ISSUE THREAD

**Issue by BobbyT** [troolee/gridstack.js#411]
Hi,

I found an bug after using gridstack-angular which lets angular taking care of the DOM and 
just uses removeWidget(widget, false) to remove the widget from the gridstackjs inner data structures.

As a result the grid resize itself, but the other widgets around don't move to their new positions.

Take a look at this screenshot (using gridstack-angular demo http://kdietrich.github.io/gridstack-angular/demo/):
![](https://cloud.githubusercontent.com/assets/1628544/14226841/720dc726-f8ee-11e5-852f-fea7026ae3ae.png)

I stacked three widgets over each other and removed the middle one. The grid (blue) adjusts, the widgets not.

**Comment by kdietrich** [comment]
This worked perfectly fine in `v0.2.4`, the bug was introduced in `v0.2.5`.

**Comment by Terren** [comment]
I'm encountering this issue as well.  Any idea when it might be fixed?  Any ideas on a workaround if need be?

**Comment by dangji** [comment]
I tried moving widgets using something like this
 
`$('.grid-stack').data('gridstack').grid.moveNode(node,x,y);`

It seemed to work fine at first, but then it stopped working for me.

**Comment by inventaethiago** [comment]
I solved this by modifying gridstack-angular's "destroy" function to call Gridstack's batchUpdate() and commit() methods before and after removing the item, respectively.

**Comment by kdietrich** [comment]
Fixed by https://github.com/troolee/gridstack.js/pull/502.
