### ISSUE TITLE
Some help needed on widget drag-drop and resize

### ISSUE THREAD

**Issue by parthbhagat** [troolee/gridstack.js#412]
Hello,

I am using gridstack library with version 0.2.5.

With this library I want to load dashboard widgets using Ajax calls. First ajax call will fetch how many columns a dashboard could have and meta information of widgets for the dashboard. Second ajax calls will be make to fetch detailed information about each widget needs to be loaded (based on first ajax call).

I have provided more information on stackoverflow. Could not upload code on jsfiddle, as there are some references to local file system. So posted all necessary code on [stackoverflow](http://stackoverflow.com/questions/36402703/issue-with-gridstack-drag-drop-and-resize-not-working).

**Comment by troolee** [comment]
Please check this demo to see how serialization can be done http://troolee.github.io/gridstack.js/demo/serialization.html
