### ISSUE TITLE
when options cellHeight set 'auto' ,resize first added widget ; other widget resize at same time

### ISSUE THREAD

**Issue by eagoo** [troolee/gridstack.js#423]
in demo/float.html
ex: 
var options = {
		cellHeight:'auto'
            };
            $('.grid-stack').gridstack(options);

  new function () {
                this.items = [
                    {x: 0, y: 0, width: 2, height: 2},
                    {x: 3, y: 1, width: 1, height: 2},
                    {x: 4, y: 1, width: 1, height: 1},
                    {x: 2, y: 3, width: 3, height: 1},
//                    {x: 1, y: 4, width: 1, height: 1},
//                    {x: 1, y: 3, width: 1, height: 1},
//                    {x: 2, y: 4, width: 1, height: 1},
                    {x: 2, y: 5, width: 1, height: 1}
                ];

                this.grid = $('.grid-stack').data('gridstack');

                this.addNewWidget = function () {
                    var node = this.items.pop() || {
                                x: 12 * Math.random(),
                                y: 5 * Math.random(),
                                width: 1 + 3 * Math.random(),
                                height: 1 + 3 * Math.random()
                            };
                    this.grid.addWidget($('<div><div class="grid-stack-item-content" /><div/>'),
                        node.x, node.y, node.width, node.height);
                    return false;
                }.bind(this);

                $('#add-new-widget').click(this.addNewWidget);
            };

when  add first widget ,and the second and other widget;
then resize first widget ,while the second and other widget resize at the same time 
is it  a bug?

**Comment by eagoo** [comment]
and the first widget can not resize only horizontal or vertical

**Comment by radiolips** [comment]
@eagoo Apologies for the delayed response. Could you provide a jsfiddle? I think I understand what you're saying, but having something to test in and see visually would help.

**Comment by eagoo** [comment]
https://jsfiddle.net/eagoo/rxvjewpg/3/
![image](https://cloud.githubusercontent.com/assets/13099426/17654548/cbd79370-62d6-11e6-8bce-c0530b839b73.png)

**Comment by radiolips** [comment]
@eagoo I'm happy to be able to tell you that this was fixed in `v0.2.6`, which was just released!
