### ISSUE TITLE
How to retain Gridstack layout when user backs up (uses the back button.)

### ISSUE THREAD

**Issue by designerx2** [troolee/gridstack.js#424]
Hello all, 

I'm enjoying this wonderful library and have my grid saving to a user specific table. All of that works fine when the user refreshes or revisits a page.. but when the user backs up to a layout page it displays the grid layout of the initial page request (as opposed to an updated or user modified grid layout.) 

Do I need to incorporate something like History.JS or the history api to retain grid changes upon page back button usage?

Thanks in advance, 
Stan

**Comment by troolee** [comment]
What browser do you use and how do you initialize gridtack? It seems working with no problem for demos http://troolee.github.io/gridstack.js/demo/ I can go backward/forward and grids work just fine

**Comment by troolee** [comment]
I'm closing the issue due inactivity. Please feel free to re-open it if any.
