### ISSUE TITLE
Enable collisions

### ISSUE THREAD

**Issue by ArribaArriba** [troolee/gridstack.js#427]
Hi,
Is there a way to allow collisions ? At least an option to prevent GridStackEngine.prototype._fixCollisions from executing.
Regards

**Comment by troolee** [comment]
Hi,

Why? What is a use case?

**Comment by ArribaArriba** [comment]
Hi,
I'm trying to build a sort of a floating dashboard. The problem is that when you try to move widgets around the collision algorithm gets in the way sometimes, when there's not enough room for example, thus preventing the widget from moving or resizing. I've temporary solved a part of the problem with the following line:

grid.grid._fixCollisions = function() {};

after each grid creation. But I don't like this kind of hacks, and it doesn't solve all my problems.

Nevertheless the result is that you can now overlap the widgets.

**Comment by troolee** [comment]
Sorry, I still don't understand what you're trying to achieve.

**Comment by troolee** [comment]
I'm closing the issue due inactivity. Please feel free to re-open it if you think it still require attention.
