### ISSUE TITLE
Static seems to require jquery-ui

### ISSUE THREAD

**Issue by kke** [troolee/gridstack.js#428]
Using from the CDN and it seems to work fine, except I'm getting this in console:

    Uncaught TypeError: c.draggable is not a function

The readme says:

    If true widgets are not movable/resizable. You don't even need jQueryUI
    draggable/resizable.

I have a widget layout editor and I'm now trying to generate the static non-editable representation of it and would like to keep the requires to the minimum.

**Comment by troolee** [comment]
https://github.com/troolee/gridstack.js/pull/431 closes the issues

**Comment by kke** [comment]
Nice!
