### ISSUE TITLE
Code-docs mismatch: draggable defaults are wrong

### ISSUE THREAD

**Issue by aletorrado** [troolee/gridstack.js#430]
Notice the `scroll` attribute.

Code is:
```
            draggable: _.defaults(opts.draggable || {}, {
                handle: (opts.handleClass ? '.' + opts.handleClass : (opts.handle ? opts.handle : '')) ||
                    '.grid-stack-item-content',
                scroll: false,
                appendTo: 'body'
            }),
```

Docs says:
- `draggable` - allows to override jQuery UI draggable options. (default: `{handle: '.grid-stack-item-content', scroll: true, appendTo: 'body'}`)

**Comment by troolee** [comment]
Thank you

**Comment by aletorrado** [comment]
Anyway, I don't understand why gridstack overrides jQuery original default, which is true.
