### ISSUE TITLE
Error in Y-axis cell calculation

### ISSUE THREAD

**Issue by aletorrado** [troolee/gridstack.js#436]
Hi, I've noticed that GridStack have an issue when dragging items downwards: items don't move until they reach one more item downwards.

You can try on the demo page, by dragging item no. 5 over item no. 8: [http://troolee.github.io/gridstack.js/](http://troolee.github.io/gridstack.js/). As you can see, nothing happens until no. 5 bypasses no. 8 by some distance.

The correct behavior would be to switch positions instantly, as when dragging no. 5 over no. 1, or no. 5 over no. 6.

**Comment by radiolips** [comment]
Hey, @aletorrado ! Thanks for letting us know. For the time being, this is actually expected behavior. We have a few open tickets encouraging some gridstack enhancements, some of which will require a rewrite of the collision. At that point, swapping widgets may become more intuitive.
