### ISSUE TITLE
Cannot move items properly when float and 100% height

### ISSUE THREAD

**Issue by mkarpinski** [troolee/gridstack.js#438]
HI,

I have set gridstack to be in float mode.
Also I have set the gridstack element to be 100% height (and width).

Now I cannot properly drag items in the container.
First of all I cannot move to the bottom. When I drag element tries to snap to the last row that has other element in it. When I have no items in gridstack when dragging new one onto it, the item will be placed in first row no matter what.

I have to fill all the rows with some items initially in order for the gridstack to work properly.

Here is example of what I mean:
![issue](https://cloud.githubusercontent.com/assets/93120/14854545/6c8a271c-0c90-11e6-804c-2a3f4d44f032.jpg)

My gridstack settings are:
`var gOptions = {
        float: true,
        resizable: {
            autoHide: true
        },
        verticalMargin: 4,
        height: 8,
        animate: true,
        removeTimeout: 100,
        acceptWidgets: '.grid-stack-item'
    };`

**Comment by ZoolWay** [comment]
This is also true without `float`. I have the same problem and can only drop items where they would be in a row where we already have items or in the next row if adjacent to another item.

**Comment by ZoolWay** [comment]
It is possible to drag the items _freely_ when setting `data-gs-locked="true"` on the items. For the moment I do that for all items. Looks like the `_packNodes` function removes _unnecessary_ rows - maybe this should be controllable through a option? Not sure which other things it does for us.

**Comment by radiolips** [comment]
@ZoolWay could you put together a jsfiddle? I understand what you're saying and I agree that this should not be the outcome, but if you put together a fiddle I can get a better idea of what's happening. Thanks!

**Comment by ZoolWay** [comment]
@radiolips I tried to put together a most basic fiddle:

https://jsfiddle.net/ZoolWay/9tga7oam/

jQuery 2.2.3
jQuery UI 1.11.4
lodash 4.11.2
Gridstack 0.2.5 (with extra css)

With one widget, it is impossible to move it to the second row. But you can resize it as you like to multiple rows.

When you uncomment the second widget, which is locked one, you can:
- Freely move it within the complete grid
- Move Widget 1 in row 2 (idx1) under widget 2 in row 1 (idx0)

Hope that helps.

**Comment by radiolips** [comment]
If I use the following settings in your jsfiddle, it does work:

```
var options = {
    width: 6,
    handle: '.draghandle',
    float: true,
    height: 12
};
$('.grid-stack').gridstack(options);
```

Closing, but let me know if this does not help you. Thanks!
