### ISSUE TITLE
Nested grid one column mode height

### ISSUE THREAD

**Issue by kke** [troolee/gridstack.js#439]
I'm not sure if this is the same as issue: #98

I have a main grid with a bunch of widgets
One of those widgets is a secondary grid

In normal viewport size it's all good, but when the main grid is or goes into one column mode, the widget hosting the secondary grid needs to grow in height or parts of its content won't be visible. 

If I somehow disable the one column mode from the secondary grid only, then I would need horizontal scrolling and that's not nice.

The widget hosting the secondary grid does not have min or max height set, just the normal gs-height.

It is still possible for me to work around that by not using a nested grid and just add the same content to the main grid as separate smaller widgets, but if you have some simple way I can keep it like it is, that would be awesome.

Also I noticed that .resize and .update don't update the data-gs-height or width of the item.

**Comment by kke** [comment]
Could there maybe be something like data-gs-height and data-gs-one-column-height?

**Comment by radiolips** [comment]
One column mode can now be controlled strictly through the Javascript, and can be handled differently for nested grids. Hopefully that will make what you're doing easier.

You can actually hook into `oneColumnMode` by periodically checking the grid to see if it is enabled. We may add in an event to make it even easier.

`.resize` and `.update` should both be updating `data-gs-height` - if you access them with `.attr('data-gs-height')` it should work.

Please reopen if there's anything more we can do, or if you have any more questions.
