### ISSUE TITLE
Possible to have this work with contenteditable on the item-content div?

### ISSUE THREAD

**Issue by ktshannon** [troolee/gridstack.js#440]
Tried to accomplish, but obviously being overridden. Tried to also force focus on the click, but it defeats the purpose of where the user clicked to edit for the text. Has anyone worked with this?

**Comment by radiolips** [comment]
I haven't personally worked with this, but I'd be happy to spend some time looking into it. Could you provide a jsfiddle for me to, well, fiddle around with? There's no reason that it shouldn't work, so if there's some issue, I can make changes to `gridstack` to ensure the click is propagating to the HTML5 listener.

**Comment by ktshannon** [comment]
Thanks @radiolips I setup a basic fiddle. https://jsfiddle.net/L74m7rjp/1/

Obviously the issue being that click activates being able to drag, but click also activates the contenteditable..

Haven't had a chance to look into this fully yet, other js libraries similar seemed to allow double click to activate the contenteditable, but it would break when trying to move the cursor with single click inside the text, ultimately causing a buggy user experience.

**Comment by radiolips** [comment]
@ktshannon Are you able to use a handle for dragging, so that the entire thing is not draggable?

```
					draggable: {
						handle: '.panel-heading'
					}
```

I believe this solves your problem. Otherwise, you'll need to handle the content div in your code. Let us know if you have any more problems.
