### ISSUE TITLE
everytime i initialize gridstack i get an error

### ISSUE THREAD

**Issue by tomkidumbuyo** [troolee/gridstack.js#441]
this._addClass is not a function
._create@http://localhost/collage/assets/plugins/jquery-ui-1.12.0-rc.2.custom/jquery-ui.min.js:6:25214

 here is my initialization code.

`$(function () {
			$('.grid-stack').gridstack({
				cellHeight: 80,
				verticalMargin: 10
			});
		});`
the error continues... im using lodash jquery and jquery ui. plus angular js. i dont know wat seems to be the problem. here is the full error.

Error: this._addClass is not a function
._create@http://localhost/collage/assets/plugins/jquery-ui-1.12.0-rc.2.custom/jquery-ui.min.js:6:25214
$.widget/</proxiedPrototype[prop]</<@http://localhost/collage/assets/js/flat-ui/flat-ui.js:421:19
$.Widget.prototype._createWidget@http://localhost/collage/assets/js/flat-ui/flat-ui.js:580:3
$.widget/$[namespace][name]@http://localhost/collage/assets/js/flat-ui/flat-ui.js:382:4
$.widget.bridge/$.fn[name]/<@http://localhost/collage/assets/js/flat-ui/flat-ui.js:527:30
.each@http://localhost/collage/assets/js/vendor/jquery.min.js:2:2971
m.prototype.each@http://localhost/collage/assets/js/vendor/jquery.min.js:2:833
$.widget.bridge/$.fn[name]@http://localhost/collage/assets/js/flat-ui/flat-ui.js:522:4
GridStack.prototype._prepareElementsByNode@http://localhost/collage/assets/plugins/gridstack.js-master/dist/gridstack.js:1109:9
GridStack.prototype._prepareElement@http://localhost/collage/assets/plugins/gridstack.js-master/dist/gridstack.js:1159:13
GridStack/<@http://localhost/collage/assets/plugins/gridstack.js-master/dist/gridstack.js:608:17
u@http://localhost/collage/assets/plugins/lodash.js:6:412
se@http://localhost/collage/assets/plugins/lodash.js:52:208
Jn/<@http://localhost/collage/assets/plugins/lodash.js:30:486
s@http://localhost/collage/assets/plugins/lodash.js:7:477
Jn@http://localhost/collage/assets/plugins/lodash.js:30:1
T/jt.prototype.value@http://localhost/collage/assets/plugins/lodash.js:119:142
GridStack@http://localhost/collage/assets/plugins/gridstack.js-master/dist/gridstack.js:607:13
$.fn.gridstack/<@http://localhost/collage/assets/plugins/gridstack.js-master/dist/gridstack.js:1648:1
.each@http://localhost/collage/assets/js/vendor/jquery.min.js:2:2971
m.prototype.each@http://localhost/collage/assets/js/vendor/jquery.min.js:2:833
$.fn.gridstack@http://localhost/collage/assets/plugins/gridstack.js-master/dist/gridstack.js:1644:1
@http://localhost/collage/assets/js/vendor/jquery.min.js line 2 > eval:3:1
m.Callbacks/j@http://localhost/collage/assets/js/vendor/jquery.min.js:2:27239
m.Callbacks/k.add@http://localhost/collage/assets/js/vendor/jquery.min.js:2:27553
m.fn.ready@http://localhost/collage/assets/js/vendor/jquery.min.js:2:29641
m.fn.init@http://localhost/collage/assets/js/vendor/jquery.min.js:2:24668
m@http://localhost/collage/assets/js/vendor/jquery.min.js:2:393
@http://localhost/collage/assets/js/vendor/jquery.min.js line 2 > eval:2:3
.globalEval/<@http://localhost/collage/assets/js/vendor/jquery.min.js:2:2613
.globalEval@http://localhost/collage/assets/js/vendor/jquery.min.js:2:2587
.domManip@http://localhost/collage/assets/js/vendor/jquery.min.js:3:22992
.append@http://localhost/collage/assets/js/vendor/jquery.min.js:3:20502
.html/<@http://localhost/collage/assets/js/vendor/jquery.min.js:3:22025
m.access@http://localhost/collage/assets/js/vendor/jquery.min.js:3:3284
.html@http://localhost/collage/assets/js/vendor/jquery.min.js:3:21623
e@http://localhost/collage/assets/js/angular/angular.min.js:22:136
z/<.link@http://localhost/collage/assets/js/angular/angular-route.min.js:7:138
E@http://localhost/collage/assets/js/angular/angular.min.js:49:345
f@http://localhost/collage/assets/js/angular/angular.min.js:42:399
v/<@http://localhost/collage/assets/js/angular/angular.min.js:42:67
V/<@http://localhost/collage/assets/js/angular/angular.min.js:43:299
y@http://localhost/collage/assets/js/angular/angular.min.js:47:23
v@http://localhost/collage/assets/js/angular/angular-route.min.js:6:311
Bd/this.$get</h.prototype.$broadcast@http://localhost/collage/assets/js/angular/angular.min.js:104:516
g/<@http://localhost/collage/assets/js/angular/angular-route.min.js:11:165
Ad/e/k.promise.then/C@http://localhost/collage/assets/js/angular/angular.min.js:92:366
Ad/e/k.promise.then/C@http://localhost/collage/assets/js/angular/angular.min.js:92:366
Ad/g/<.then/<@http://localhost/collage/assets/js/angular/angular.min.js:94:28
Bd/this.$get</h.prototype.$eval@http://localhost/collage/assets/js/angular/angular.min.js:102:304
Bd/this.$get</h.prototype.$digest@http://localhost/collage/assets/js/angular/angular.min.js:100:42
Bd/this.$get</h.prototype.$apply@http://localhost/collage/assets/js/angular/angular.min.js:103:98
f@http://localhost/collage/assets/js/angular/angular.min.js:67:96
E@http://localhost/collage/assets/js/angular/angular.min.js:71:85
pd/</v.onreadystatechange@http://localhost/collage/assets/js/angular/angular.min.js:72:133

<div class="ng-scope" ng-view="">

**Comment by radiolips** [comment]
@tomkidumbuyo There's an angular gridstack repo available here: https://github.com/kdietrich/gridstack-angular - for issues specific to running gridstack with angular, please refer there.
