### ISSUE TITLE
stick to bottom within gap

### ISSUE THREAD

**Issue by pknecht** [troolee/gridstack.js#443]
Dear guys,

I am having a hard time modifying gridstack so that items within a gap may not stick to the top but to the bottom instead.
Currently I am stuck in the ._packNodes function. My educated guess was to sort the the nodes otherway round with _sortNodes(-1) and iterate starting by 0.
But none of that works.

Can you help me by giving me some hint what I'm missing or if the code structure doesn't allow such a mod?
Thank you.

Paul

**Comment by radiolips** [comment]
Unfortunately, this will be a little difficult to work in, and we don't plan on supporting it in the future.
