### ISSUE TITLE
it's possible drag content between grids

### ISSUE THREAD

**Issue by huntercl** [troolee/gridstack.js#445]
You can move the content found within the grid "green box" to another grid ,
one example the text I want to move to any box, but only the text .
Try performing the jquery ui draggable with , but when you move the contents to another box disappears.
example : https://jsfiddle.net/huntercl/phhyh5yd/1/
![111](https://cloud.githubusercontent.com/assets/9697067/15114903/8b97547c-15d2-11e6-8983-77ca2cce6997.jpg)

thanks

**Comment by radiolips** [comment]
I don't fully understand. Text is not inherently an object. You may be able to write some custom code, but I think that what you're asking for is not possible. I've tried using your demo, but unfortunately I still don't completely understand. Please reopen if you're still having an issue and think we may be able to help.
