### ISSUE TITLE
resize proportionally

### ISSUE THREAD

**Issue by TheCherry** [troolee/gridstack.js#450]
Is there any way to set a option, that a grid-stack-item can only be resize proportionally? The initial ratio should be remain. 

Or any workaround? I try to get the size from the doted border in the resize event, but I cant find that one. I find only the size from the current container, not the one who will set the final size.

**Comment by radiolips** [comment]
Hi, @TheCherry! This does not currently exist. We will consider this in development.

**Comment by radiolips** [comment]
Apologies - this actually exists. If you use the `cellHeight: auto` option when initializing your grid, your widgets will automatically update the height as you change the width. I'm closing this ticket, but please let us know if this doesn't resolve your issue.

**Comment by TheCherry** [comment]
`var options = {
      cellHeight: "auto"
    };
    $('.grid-stack').gridstack(options);`
Did try that, but that dont help me. I need as example a widget with 2x2, the rezise can only be 3x3, 4x4, 5x5.
Or a another example: 1x3 > 2x6
