### ISSUE TITLE
Remove gap between each block/widget

### ISSUE THREAD

**Issue by damerakiran** [troolee/gridstack.js#453]
can u please any one tell me how can i remove gap between each block.

thanks in advance

**Comment by ekomsctr** [comment]
For the vertical gap between lines, just set in the grid options verticalMargin: 0, meanwhile for the gap between items on the same line you have to set the css properties "left" and "right" of the class "grid-stack-item-content" to 0px, or just remove the class.

**Comment by radiolips** [comment]
Thanks for resolving this, @ekomsctr. If there's any further issue, @damerakiran, please let us know.

**Comment by edirectorios** [comment]
Hello, where exactly must this vertical margin be set?
Maybe you mean margin.top?

**Comment by dearsina** [comment]
> Hello, where exactly must this vertical margin be set?
> Maybe you mean margin-top?

You set it as an option. I can't seem to find it in the documentation, but it's still (version 2.0.2) a valid option:

```
GridStack.init({
        verticalMargin: 0,
});
```

**Comment by adumesny** [comment]
no, in 2.x it's called `margin` and apply in code to both... as opposed to css vs code which was a mess.
