### ISSUE TITLE
Disable resize dynamically

### ISSUE THREAD

**Issue by leandrogutierrez** [troolee/gridstack.js#454]
Hello, i´m triying to disable resize from a widget after mouse-click over a panel-heading within the grid-stack-item-content, using:
  var grid = $('.grid-stack').data('gridstack');
  var node = $(this).parents('.grid-stack-item'); 
  grid.resizable(node,false);
Please tell me what i´m doing wrong.
Thank you very much and sorry for my english.

**Comment by radiolips** [comment]
This should be all you need. Could you provide a jsfiddle displaying your issue? What you've pasted looks okay.

**Comment by radiolips** [comment]
This may have been resolved from another fix in `v0.2.6`. This is working for me, so I'm closing this out, but please reopen if you're having problems even in `v0.2.6`. Thanks for using gridstack! Sorry you had to wait so long for a response.
