### ISSUE TITLE
data-custom-id

### ISSUE THREAD

**Issue by danou83000** [troolee/gridstack.js#457]
where place data-custom-id in the content
I tried :
this.saveGrid = function () {
              this.serializedData = _.map($('.grid-stack > .grid-stack-item:visible'), function (el) {
                  el = $(el);
                  var node = el.data('_gridstack_node');
                  return {
                    **id: el.attr('data-custom-id'),**
                    x: node.x,
                    y: node.y,
                    width: node.width,
                    height: node.height
                  };
              }, this);

              $('#saved-data').val(JSON.stringify(this.serializedData, null, '    '));
              return false;
            }.bind(this);

function addNewWidget() {
            var grid = $('.grid-stack').data('gridstack');
            **grid.addWidget($('<div><div data-custom-id="ggg"** ........................

**Comment by radiolips** [comment]
The final parameter of `addWidget` will allow for a custom id to be passed. This will set the `data-gs-id` attribute of the element.
