### ISSUE TITLE
Would it be possible not to attach resizable/draggable jquery-ui widgets if not needed( for performance reason)

### ISSUE THREAD

**Issue by pmoradei** [troolee/gridstack.js#458]
Hi ! 

My application is made of many pages and each page has a grid with an average of 30 widgets inside. The user of the application can go from page to page.
On mobile devices (i'm talking about not very powerful ones, for example im using a HP Slate 21 tablet with Chrome),  attaching 30 times draggable/resizable is significantly lowering the performance. 

So my questions are : 

Would it be possible not to attach resizable to a widget with data-gs-no-resize to true?
Resizable could be then attached via the methods enableResize(doEnable, includeNewWidgets) or resizable(el, val).

Would it be possible not to attach draggable to a widget with data-gs-no-move to true?
Draggable could be then attached via the methods enableMove(doEnable, includeNewWidgets)/ movable(el, val).

Finally, it would be completely up to the developper to choose when to attach movable/resizable behaviour.

Thanks !

**Comment by radiolips** [comment]
@pmoradei Have you tried using static? Also, if you don't have jQuery UI, you should not have a problem running `gridstack`, which may help in your case. I'm closing this because we intend to eventually remove `jquery-ui`, but, for the time being, my suggestion should help you. Please reopen if you have an issue.

**Comment by pmoradei** [comment]
Hi!
I do need jQuery UI! 
I dont want my grid to be static. 
(yes i'm complicated :))

It would  be great if we could have a "lazy initialized" grid. Where resizable/draggable feature would be attached just when needed.(using gridstack api methods movable/resizable) 

I red the gridstack code and if a widget is initialized as not movable(data-gs-no-move to true) it first attaches draggable and then disables it.
It would be nice not to attach draggable/resizable at all, it would greatly increase performance when there is a lot of widgets inside the grid.

**Comment by radiolips** [comment]
We could certainly initialize it lazily. Why would this change performance much?

**Comment by pmoradei** [comment]
Of course my case is very specific so I understand your question : 
my application is made of many pages and each page has a grid with an average of 30 widgets inside. The user of the application can go from page to page. Going from one page to another must be as quick as possible that's why avoiding attaching 30 or 50 draggable and resizable widget could be interesting!

Thanks for your time!
