### ISSUE TITLE
Max width in oneColumn mode

### ISSUE THREAD

**Issue by clanghout** [troolee/gridstack.js#462]
When a widget has a maxWidth smaller than the width of the grid, then this widget will appear smaller than the available width in one column mode.

**Comment by Julienng** [comment]
Can you provide an exemple of this please ?

**Comment by clanghout** [comment]
It seems to be a bug at my own project, for now I am not able to reproduce the problem in a fiddle.

**Comment by clanghout** [comment]
https://jsfiddle.net/02kx0md2/1/ 
was able to reproduce the issue using gridstack 0.2.5, this issue is not there in gridstack 0.2.2

**Comment by radiolips** [comment]
@clanghout I don't understand the problem. Could you clarify for me, please?

**Comment by radiolips** [comment]
This has been resolved in the master branch.
