### ISSUE TITLE
Get final position after drag and drop

### ISSUE THREAD

**Issue by brunosnascimento** [troolee/gridstack.js#463]
How can i get the final position after drag and drop one element?
Is there some special function that capture it?

**Comment by mpasterkamp** [comment]
Check out the events in the documentation.
You could use the onChange event it the onDragStop()

**Comment by radiolips** [comment]
Closing. There are a couple events you could use to get this information, as @mpasterkamp (thanks!) mentions. Please let me know if you're having any more issues.
