### ISSUE TITLE
select and drag multiple widgets

### ISSUE THREAD

**Issue by spitzbubchen** [troolee/gridstack.js#466]
It would be nice if it was possible to select multiple widgets and drag them all instead of selecting and dragging each widget one by one.

**Comment by radiolips** [comment]
Thanks. I assume you mean moving widgets, right? Dragging for resize with multiple selected would present a difficult ux.

**Comment by radiolips** [comment]
I don't think this makes sense for the near future. As I mentioned, the UX would be difficult. Something like this may be possible to build on top of gridstack, but this won't be part of the actual core library. Possibly this could be part of the new plugin system being introduced with `v0.3.0`.

**Comment by johnsoncherian** [comment]
Hi @radiolips and @spitzbubchen Is this issue still open.? Is the feature implemented now.?

**Comment by adumesny** [comment]
no it is not. shift/Ctrl+Select could be used to select but then moving collision would be quite difficult. if you need to move items as group, use sub-grid instead.

**Comment by eduardokaiserjr** [comment]
> no it is not. shift/Ctrl+Select coudl be used to select but then moving collision could be quite difficult. if you need to move items as group, use sub-grid instead.

Hi @adumesny. First of all, thanks for this awesome work of maintaining Gridstack.

About the multi items drag thing, you said that it is possible to select and move more than a item. Would you mind to point the right direction on how to do it (without subgrid) despite the collision problem?

**Comment by adumesny** [comment]
@eduardokaiserjr I said `shift/Ctrl+Select **could** be used to select...` but it is not today as you can't drop multiple items.

**Comment by dearsina** [comment]
I used Codex to allow for multi-select, it works pretty well. I can select multiple items, and once I start to drag them, a wrapper element is created and that's the element that gets moved around. So it _is_ possible, and frankly quite a useful addition.

**Comment by adumesny** [comment]
@dearsina please explain what do you mean by codex ?
solving this in the general case, eg: you have holes in your selection but float:false and you move it over other items, would be incredibly complex and likely odd ux. Not gonna happen. that's what sub-grids are for (managing groups of widgets as a unit).
