### ISSUE TITLE
Gridstack having two column grid widgets 

### ISSUE THREAD

**Issue by swarnab** [troolee/gridstack.js#467]
Hi,

I want to display two widgets by row in gridstack. getting x,y positions from an array. first 3 widgets displaying correct. But third widget on wards (from Fourth)widgets are  displayed below third widget.

  {x: 0, y: 0, width: 3, height: 3},
                    {x: 6, y: 0, width: 3, height: 3},
             		{x: 7, y: 1, width: 3, height: 3},
                    {x: 13, y: 1, width: 3, height: 3},
                    {x: 14, y: 2, width: 3, height: 3},
                    {x: 20, y: 2, width: 3, height: 3},
             		{x: 21, y: 3, width: 3, height: 3},
              

PLEASE HELP ME.

**Comment by Julienng** [comment]
Hi,
It seems like you don't take care of the `height` and `width` of the element to place the next one
Why you don't place them by drag and drop and watch the `x` and `y` position ?

**Comment by swarnab** [comment]
actually user searches for query and result data is added as widget to gridstack. So i want to display the widgets two in a row. for look and feel. so the width and height are fixed. Please suggest.

**Comment by Julienng** [comment]
I just say that for you to test and understand how things work :)
An exemple of my grid look like:
- value width = 6 because the grid has 12 column by default
```js
[
// first line
{ x: 0, y : 0, width : 6, height : 8},
{ x: 6, y : 0, width : 6, height : 8},
// second line
{ x: 0, y : 8, width : 6, height : 9},
{ x: 6, y : 8, width : 6, height : 9},
]
```
As you can see, I take care of  the height of card for component under the first line

**Comment by swarnab** [comment]
hi,  
below is my code, i need two column grids,  but grids displayed one below other.

please help 




<!DOCTYPE html>
<html lang="en">
<head>
    

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> grid demo</title>




    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.0/jquery-ui.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.5.0/lodash.min.js"></script>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/gridstack.js/0.2.5/gridstack.min.css" />
<script type="text/javascript" src='http://cdnjs.cloudflare.com/ajax/libs/gridstack.js/0.2.5/gridstack.min.js'></script>

    <style type="text/css">
        .grid-stack {
            background: lightgoldenrodyellow;
        }

        .grid-stack-item-content {
            color: #2c3e50;
            text-align: center;
            background-color: #18bc9c;
        }
       .grid-stack-item[data-gs-width="2"]  { width: 100% }
    .grid-stack-item[data-gs-width="1"]  { width: 50% }
    .grid-stack-item[data-gs-x="1"]  { left: 50% }
  
    </style>
</head>
<body>
    <div class="container-fluid">
        <h1>Float grid demo</h1>

        <div>
            <a class="btn btn-default" id="add-new-widget" href="#">Add Widget</a>
        </div>

        <br/>

        <div class="grid-stack">
        </div>
    </div>


    <script type="text/javascript">
        $(function () {
         
$('#add-new-widget').click(function(){
           var options = {
                float: true,
               width: 6
            };
            $('.grid-stack').gridstack(options);
        this.grid = $('.grid-stack').data('gridstack'); 

           
               this.items = [
                    {x: 0, y: 0, width: 3, height: 3},
                    {x: 6, y: 0, width: 3, height: 3},
             		{x: 7, y: 1, width: 3, height: 3},
                    {x: 13, y: 1, width: 3, height: 3},
                    {x: 14, y: 2, width: 3, height: 3},
                    {x: 20, y: 2, width: 3, height: 3},
             		{x: 21, y: 3, width: 3, height: 3},
                    {x: 27, y: 3, width: 3, height: 3},
                    {x: 28, y: 4, width: 3, height: 3},
                    {x: 34, y: 4, width: 3, height: 3},
             		{x: 35, y: 5, width: 3, height: 3},
                    {x: 41, y: 5, width: 3, height: 3},
                   {x: 42, y: 6, width: 3, height: 3},
                    {x: 48, y: 6, width: 3, height: 3},
             		{x: 49, y: 7, width: 3, height: 3},
                    {x: 55, y: 7, width: 3, height: 3},
                    {x: 56, y: 8, width: 3, height: 3},
                    {x: 57, y: 8, width: 3, height: 3},
             		{x: 63, y: 9, width: 3, height: 3},
                    {x: 64, y: 9, width: 3, height: 3}
                   
                ];  
                this.grid = $('.grid-stack').data('gridstack');

                
                    var node = this.items.shift();
                    this.grid.addWidget($('<div><div class="grid-stack-item-content" /><div/>'),
                        node.x, node.y, node.width, node.height);
                   // return false;
                //}.bind(this);

               // $('#add-new-widget').click(this.addNewWidget);
         //   };
        
        
      });
         
              
          

      
        });
    </script>
</body>
</html>

**Comment by swarnab** [comment]
Hi Julienng,

Thanks a lot for the reply , really it solved the issue.
