### ISSUE TITLE
get position after drag n drop

### ISSUE THREAD

**Issue by ambit-ashish** [troolee/gridstack.js#472]
Hey, what is call back function you used for the event drag? I am new to gridstack and want to save the position in drag n drop action? Could you please me with this?
How can i get the final position after drag and drop one element?
Is there some special function that capture it?

**Comment by mpasterkamp** [comment]
I would suggest checking out the grid stack events in the documentation

**Comment by radiolips** [comment]
As @mpasterkamp mentioned, please check here for more information. Let me know if you're still having problems.

https://github.com/troolee/gridstack.js/tree/master/doc#events
