### ISSUE TITLE
Add widget to the end of the grid

### ISSUE THREAD

**Issue by orelil** [troolee/gridstack.js#473]
Is there any way to add widgets to the end of the grid (after last widget and if no place in a new row)? actually if location is not provided the widget will be added to the top left ..

**Comment by mpasterkamp** [comment]
What I'm doing is I enable the autoposition property before I add the widget to the grid. this adds the widget to the end of the grid (as you suggested). However, enabling autoposition gave us unintended behaviour when you move widgets out of the grid. So after we add the widget to the grid with autoposition enabled we disable autoposition again.

**Comment by orelil** [comment]
in API doc i saw that the auto position tells to ignore data-gs-x and data-gs-y attributes and to place element to the first available position - i guess there is no guarantee it will be placed at the end of the grid ..

**Comment by Julienng** [comment]
I use `autoposition` to place my card at the end too
