### ISSUE TITLE
Resize node on custom width

### ISSUE THREAD

**Issue by peterkalos** [troolee/gridstack.js#475]
I have changed width from 12 to 100 and compile SCSS with $gridstack-columns: 100

From example
https://jsfiddle.net/atq85cy5/

When I resize bigger node on right-hand side,
I got something weird, The node has been moved (a little move to left-hand side) automatically.

It should be fixed in old position?

Thank you,
Peter

**Comment by radiolips** [comment]
@peterkalos very odd. I've taken a look at your jsfiddle and agree, it's odd that it's moving it slightly.

**Comment by radiolips** [comment]
Closing. I'm no longer seeing an issue in your jsfiddle. Please reopen if you're still having a problem.

**Comment by peterkalos** [comment]
@radiolips I still got this problem.

[Imgur](http://i.imgur.com/0ywTXg1.gifv)
