### ISSUE TITLE
AddWidget direction issue.

### ISSUE THREAD

**Issue by KennethanCeyer** [troolee/gridstack.js#479]
Hello developer!

I have a question about a 'addWidget' method.

First of all, I am korean (I am not good at writing english, enough.)

I have been using your gridstack plugin in our solution,

And 'addWidget' be called when user click 'add' button.

I want new widget to be added on bottom of the area. (but added on the top.)

The code is here

```javascript
angular.element('.grid-stack').data('gridstack').addWidget($('<div></div>').html(e),
                    parseInt((!opt.pos_x || isNaN(opt.pos_x)) ? 0 : opt.pos_x),
                    parseInt((!opt.pos_y || isNaN(opt.pos_y)) ? 0 : opt.pos_y),
                    parseInt(opt.width && !isNaN(opt.width) ? opt.width : 6),
                    parseInt(opt.height && !isNaN(opt.height) ? opt.height : 2)
                    );
```

Can i change the direction option?
If i can, Where should i make the changes of those options.

**Comment by DoctaWorm** [comment]
I believe if you use `autoPosition: true` will if you your desired result. Unless I'm not fully understanding what it is you want.  [Here's the documentation on addWidget](https://github.com/troolee/gridstack.js/tree/master/doc#addwidgetel-x-y-width-height-autoposition-minwidth-maxwidth-minheight-maxheight-id). 

Also since it appears you're using angular. Have you looked at posting this issue over at the [angular-gridstack](https://github.com/kdietrich/gridstack-angular) repository

**Comment by KennethanCeyer** [comment]
@DoctaWorm Thank you for quick answer. I am really dumb.

I have another question, I need `copy feature`, it means grid copy(i have customized `contents fill` logic),

And the plugin will insert after original grid.

But i can't set in correct position, if original grid in center and user use copy feature. new copied grid added on weird position among each of siblings grid which is nearby original grid

Is it have copy feature what i said?

**Comment by DoctaWorm** [comment]
Hmm, I'm not quite following what you're saying could you provide and example in a jsfiddle or a codepen?

**Comment by radiolips** [comment]
@KennethanCeyer I'm not sure what you mean, either. If you're still having this issue, please provide a jsfiddle. If not, I'll close this out in a couple days. Hope you've gotten it to work!

**Comment by radiolips** [comment]
Closing this, but please reopen if you're continuing to experience issue.
