### ISSUE TITLE
Add charts to different widgets

### ISSUE THREAD

**Issue by griphi** [troolee/gridstack.js#480]
Hi,

I have tried to add different charts to different widgets, but I get no solution.
Have anybody the same problem or a solution?

Thanks

**Comment by radiolips** [comment]
Welcome to gridstack.js, @griphi ! If you're trying to have different charts in different widgets, this is definitely the library for you. Many people use this for such a case. Could you provide some code to show your problem? There should be no issue.

**Comment by griphi** [comment]
`<div class="container-fluid">
<div id="dashboard">
    <div class="active-widgets">
        <div class="header-title">
          <h1>Report</h1>
        </div>
        <div class="grid-stack"></div>
    </div>
    <div class="header-title">
        <h1>ToolBox</h1>
    </div>
    <div class="inactive-widgets">    
        <div class="grid-stack"></div>
    </div>
</div>

<div id="template" style="display: none;">
    <div class="widget">
        <div class="grid-stack-item-content">
            <div class="portlet-header" style="vertical-align: middle;">
                <span class="header"></span>
                    <button class="na-icon na-icon-gear widget-conf"></button>
            </div>
            <div class="content">
                <p id="demo"></p>
            </div>
        </div>
    </div>
</div>`

This is a template of @alangunning and I do not understand, how he adds different charts to different widgets using gridstack as library.

Thanks

**Comment by radiolips** [comment]
I still don't understand. The link provided does not have charts.

**Comment by griphi** [comment]
Exactly, but I want to put in every Widget another Chart.
But I do not know how to make it on the website I have posted.
If I add a Chart in the <div class="Content"> every single Widget has the same Chart. Bit I want to have in every single Widget another Chart.

Thanks for help.

**Comment by radiolips** [comment]
@griphi Alan's code uses the concept of a template and each widget simply duplicates the templated code. You'll need to write your own code and not use a template if you want each widget to have different contents.

If you're still having an issue after rebuilding, please open a new ticket and provide a jsfiddle. Thanks! Good luck.

**Comment by radiolips** [comment]
@griphi I hope you were able to accomplish what you wanted. If not, I've put together a tutorial that you can follow to add charts to widgets.

[Charts and Dashboards tutorial](https://dylandreams.com/2017/05/06/of-charts-and-dashboards/)

**Comment by HasiniA99x** [comment]
@radiolips  Hi https://dylandreams.com/2017/05/06/of-charts-and-dashboards/ This link doesn't work. Can you please update the link?
