### ISSUE TITLE
setStatic not working!

### ISSUE THREAD

**Issue by artknight** [troolee/gridstack.js#481]
I peeked at the source and I am seeing this code that seems to prevent the grid to be made static

```
 if (self.opts.staticGrid || typeof node == 'undefined' || node === null) {
                return;
            }
```

`self.opts.staticGrid` is set to `true` so this will return before doing anything

**Comment by radiolips** [comment]
You're right. It looks like #431 broke this functionality. I'm pleased the jQuery-ui requirement was removed, but unfortunately it only accounted for `static` being set initially and not dynamically changed. We'll probably end up rolling back the change set. Thanks for identifying this.

**Comment by radiolips** [comment]
@artknight This should be fixed in `v.0.2.6`. Could you let me know? It should still make sure jquery-ui is not a requirement, but should now work if you modify `setStatic` at any time.

**Comment by radiolips** [comment]
@artknight I have no idea if this was fixed Aug 16, 2016, but it should be fixed now. `setStatic` was working, but `staticGrid` was not. And now it does work.

**Comment by artknight** [comment]
this is fixed now. Thanks!
