### ISSUE TITLE
Using gridstack with KendoUI Tabstrip

### ISSUE THREAD

**Issue by syedhabeebuddin** [troolee/gridstack.js#482]
Hi ,

We need to move the controls (i.e. Drag drop the controls within a Tab of Kendo UI Tabstrip.)
For moving the controls we thought of using "gridstack" , but its not working. 

Lets take we have 2 KendoGrids and 2 KendoCharts within a tab of Kendo Tabstrip ,that needs to be swapped their position.

My question here is does Gridstack supported on Kendo UI platform. If possible can I gat a sample for the same.

**Comment by syedhabeebuddin** [comment]
I  need some help on this..

**Comment by radiolips** [comment]
Hey, syed! I'm not familiar with Kendo UI. Could you provide some images or code to help explain your issue? Thanks!

**Comment by jvelezc** [comment]
here you go: https://github.com/jvelezc/GridStackDemo

**Comment by troolee** [comment]
Hi @syedhabeebuddin,

we do not provide a support of any bindings to third party libraries like knockout.js, angular.js, etc. gridstack from the box doesn't support these libraries, but we make all possible to make other people create that bindings as smoothly as possible.

If you're implementing bindings for third party libraries and you need specific API inside gridstack core, feel free to ask and we will try to help you.
