### ISSUE TITLE
Gridstack with jQuery 3.x

### ISSUE THREAD

**Issue by acerberus** [troolee/gridstack.js#486]
Gridstack does not work out of the box with jQuery 3.x. The problem is that it uses the deprecated size() function (https://api.jquery.com/size/). In order to make it work one can register the size function as

     //size function for gridstack
     $.fn.size = function(){
          return this.length;
     };

**Comment by PaulBullivant** [comment]
This change worked for me without having to create an extra function
`var isNested = this.container.closest('.' + opts.itemClass).size() > 0;`
TO
`var isNested = this.container.closest('.' + opts.itemClass).length > 0;`

**Comment by radiolips** [comment]
This will be taken care of in the next development update very shortly.
