### ISSUE TITLE
Dynamic resizing of widget doesn't persist when dragged for the first time

### ISSUE THREAD

**Issue by sophanox** [troolee/gridstack.js#488]
Hi there,

I have a widget which expands or shrinks dependent on the content inside it (FancyTree folders). I do this by adding or subtracting from the data-gs-height as the content expands/contracts. Unfortunately, when I then drag this widget, it doesn't seem to adhere to the new data-gs-height, and instead appears to revert back to the minimum height. 

As you can see in the below image, when dragging for the first time, the placeholder shadow indicates the height that the widget will snap to.

![image](https://cloud.githubusercontent.com/assets/19409202/17331468/f2101922-58c2-11e6-9316-9f743a4ad28c.png)

What is a little odd is that, if I first resize the widget (even so that it stays its original size), the drag action works without a problem.

This suggests there's another field that I need to update when I dynamically resize a widget, but I can't figure out where it is as it doesn't appear to be a data attribute that I can see.

Any suggestions? Many thanks

**Comment by radiolips** [comment]
Hey, @sophanox ! Have you tried adjusting the width/height using the `resize` function?

[https://github.com/troolee/gridstack.js/tree/master/doc#resizeel-width-height](https://github.com/troolee/gridstack.js/tree/master/doc#resizeel-width-height)

**Comment by sophanox** [comment]
Ah yes that has worked! Many thanks :)
