### ISSUE TITLE
CSS overflow-y: auto drags container rather scroll in Firefox

### ISSUE THREAD

**Issue by venkata82** [troolee/gridstack.js#489]
I just added more content to one of the Demo's widget. I see a y scroll bar.
I can't scroll content, it is triggering drag and whole is dragging.

![scrollissue](https://cloud.githubusercontent.com/assets/2564808/17385913/6c1014e6-59ab-11e6-8037-dddb13900f54.png)

**Comment by radiolips** [comment]
@venkata82 This is actually normal behavior. As you can see, you may drag any of the panels by clicking and dragging anywhere on the panels. However, you may set a specific drag handle so that only a particular place will be draggable.
