### ISSUE TITLE
Multiple Resize-Handles

### ISSUE THREAD

**Issue by renebrain** [troolee/gridstack.js#49]
Hi,

is it possible to show more than one Resize Handle? I would also like to have a handle on the bottom-left side, so that the User can decide where he wants to resize his widget.

Thanks

PS: I think i wrote this into the wrong section. Sorry :/

**Comment by troolee** [comment]
I think I can implement this

**Comment by troolee** [comment]
Hi,

I've finally implemented this. Sorry for delay.

Please take a look on new available options `resizable` and `draggable`. You can also check this [sample](https://github.com/troolee/gridstack.js#override-resizabledraggable-options).
