### ISSUE TITLE
Resizing options (e, w, s...) over the individual nodes, instead of common Grid options

### ISSUE THREAD

**Issue by kalokamgit** [troolee/gridstack.js#494]
It could be better if resizing options are providing with each node. so that I can resize few are in vertical & few are in horizontally.

**Comment by radiolips** [comment]
This now works on the `develop` branch. Use `data-gs-resize-handles="e, s"` for east+south resize handles on one widget, for example. Thanks for the suggestion!

**Comment by jan-krakora** [comment]
Is this option still available in the current 7.x.x version? I mean, this update does not work.

```javascript
gridStack.update(el, {
    resizable: {
        handles: 'e, s'
    }
});
```

Do I have to use attributes?

**Comment by adumesny** [comment]
@jan-krakora doesn't work as an update, only intial creation

**Comment by kanyesthaker** [comment]
Does this still exist? I cannot see any mention of this `data-gs-resize-handles` attribute anywhere in the codebase, nor in its documentation. I'm not sure how else to get each widget to control its own resize behaviors.

**Comment by adumesny** [comment]
@kanyesthaker if you set the min/max it will prevent resizing in that direction. as for the feedback, it's `'gs-resize-handles'`
