### ISSUE TITLE
Two Grids Demo - different Widgets on Grid1 and Grid 2

### ISSUE THREAD

**Issue by griphi** [troolee/gridstack.js#495]
Hi,

I have a question about Two Grids lib.
I am using Grid 1 and Grid 2 to dragging widgets between those grids.
But the grid1 and the grid2 have the same Widgets, but I want to have on grid1 different Widgets as on grid2.

The two Grid Demo Shows the issue for me.

Thanks

**Comment by radiolips** [comment]
Hi @griphi. When dragging a widget from one grid to another, the widget should be the same. You're able to change the styles using CSS if you'd like. I'm unable to identify an issue here, so I am closing. Please reopen and describe your issue in more detail if you have more issues. Thanks!
