### ISSUE TITLE
Cannot swap grids when the height is fixed to 1

### ISSUE THREAD

**Issue by bragboy** [troolee/gridstack.js#498]
I am trying to fixate the height of the rows to be 1 and have three grids of 4x4 size. I am trying to swap the grids in the same row but not able to do so. Please go through the following fiddle URL (ensure your monitor is stretched well enough to reproduce my issue)

https://jsfiddle.net/bragboy/8v8vez8d/2/

![image](https://cloud.githubusercontent.com/assets/1298587/17621137/0a9ebe00-60af-11e6-825e-1d0cf8652beb.png)

My options are below
```javascript
var options = {
    cellHeight: 20,
    verticalMargin: 10,
    resizable: {disabled: true},
    height: 1
  };
```

Also when the width of the window is reduced, I can hardly drag the widgets at all. Please help/guide me on this.

![image](https://cloud.githubusercontent.com/assets/1298587/17621123/f6b45738-60ae-11e6-9187-fb8a8cd45cdf.png)

**Comment by radiolips** [comment]
That's correct. When the screen is in `oneColumnMode`, you cannot reorder. When there's only one row, you cannot swap. Due to the collision algorithm used, swapping is not an option. This will be updated in the future and enhancement tickets are already open.
