### ISSUE TITLE
Cloning widget when moving from one grid to another 

### ISSUE THREAD

**Issue by redstubble** [troolee/gridstack.js#499]
I have seen a number of similar issues, however I cannot seem to get any to work. I have one template gridstack which I want to drag widgets onto another dashboard. However I want to duplicate this widget rather than move it. 

I have tried removing $(ui.draggable).remove(); and removing the attributes, however the behaviour is still not working. The element is still bound to the cloned element. How do I reset this?

Or is it easier to create a draggable element using Jquery that can bind into the gridstack, when dragged over it?

Any hints or tips would be greatly appreciated.

**Comment by radiolips** [comment]
We'll handle this in #396 . You may want to watch that one, as hopefully we'll have many fixes in `v0.2.7`, including a fix for this. Thanks! Please reopen if you feel this is different from the other, or open a new ticket if you have any more issues. Thanks, @redstubble !

**Comment by radiolips** [comment]
This works on the `develop` branch now. Please be sure to use `draggable` setting `helper: clone`.

**Comment by nichols12** [comment]
The `helper:"clone"` work's on 0.40 version?
