### ISSUE TITLE
Save Data?

### ISSUE THREAD

**Issue by taylorman57** [troolee/gridstack.js#50]
This probably isn't the proper place to ask this, but how can I get the data on demand (coordinates, width, height, id)?

It seems like most people would eventually want to save their layout to a database or something else, but I am not finding any information on how to do this.

**Comment by taylorman57** [comment]
It seems like this code, which I found in one of the other "issues" can extract all of the needed data. Right now I just have it doing an "alert" but the ending json string should be used by jQuery to submit the data.

function saveData() {
        var items = [];

        $('.grid-stack-item.ui-draggable').each(function () {
            var $this = $(this);
            items.push({
                x: $this.attr('data-gs-x'),
                y: $this.attr('data-gs-y'),
                w: $this.attr('data-gs-width'),
                h: $this.attr('data-gs-height'),
                content: $('.grid-stack-item-content', $this).html()
            });
        });

        alert(JSON.stringify(items));
    }

**Comment by troolee** [comment]
Hi,

I will update docs with a sample of serialization/deserialization.

**Comment by bbirand** [comment]
Yes, having the above function incorporated in the main codebase would be great. 

Freeboard has a pair of such functions, `freeboard.serialize()` and `freeboard.loadDashboard` for this purpose. Extremely useful.

**Comment by troolee** [comment]
@bbirand Please check out this note https://github.com/troolee/gridstack.js#save-grid-to-array

**Comment by bbirand** [comment]
Great insight; thanks!
