### ISSUE TITLE
How to make a static widget? staticGrid does not work... 

### ISSUE THREAD

**Issue by sumikoabe** [troolee/gridstack.js#517]
Hi, this is great lib that I am looking for creating a dashboard.
A specified widget need to be a static one. I checked the code and that looks like the there is property named staticGrid need to be true. I set it as:

var widgets = [
                {id: 'widget0', x: 0, y: 0, width: 2, height: 2, staticGrid: true },                
                {id: 'widget1', x: 2, y: 0, width: 1, height: 1},
                {id: 'widget2', x: 3, y: 1, width: 2, height: 2},
                {id: 'widget3', x: 1, y: 2, width: 1, height: 1}
            ];

The following is all of my code...

<!DOCTYPE html>
<html lang="en">
<head>
    

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dash board demo</title>

    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="./dist/gridstack.css"/>    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.0/jquery-ui.js"></script>    
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.5.0/lodash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.2.0/knockout-min.js"></script>
    <script src="./dist/gridstack.js"></script>
    <script src="./dist/jscolor.js"></script>

    <script type="text/javascript">
function setTextColor(picker) {
		document.getElementsByTagName('body')[0].style.color = '#' + picker.toString()
	}
        /*
      function toggleDropdownMenu()
      {
        var e1 = document.getElementById(id1);
        var style_string = 'height:'+new_height+';margin-left:0px;';
        e1.setAttribute('style', style_string);
        e1.style.display = 'none';

        var e2 = document.getElementById(id2);
        e2.style.display = 'block';
        e2.style.height = '2000px';
        //e2.setAttribute('height', 1400);
        e2.setAttribute('style', 'overflow-y:scroll;');
      }*/
    </script>
    <style type="text/css">
        .grid-stack {
            background: lightgoldenrodyellow;
            
        }

        .grid-stack-item-content {
            color: #2c3e50;
            text-align: center;
            background-color: #18bc9c;
        }
        .grid-stack-item-content button{
            background-color: Transparent;
            background-repeat:no-repeat;
            border: none;
            cursor:pointer;
            overflow: hidden;
            outline:none;
            color: green;
            position: relative;
        }
        .grid-stack-item-content　.dropdown-submenu {
            position: relative;
            font-size: 10px;
            height: 15px;
        }
        .grid-stack-item-content .dropdown-submenu .dropdown-menu {
            top: 0;
            left: 100%;
            margin-top: -1px;
        }
        
    </style>
</head>
<body>
    <div class="container-fluid">
        <h1>Dashboard Demo</h1>

        <div>
            <button data-bind="click: addNewWidget">Add new widget</button>
            <button id="btn1" class="jscolor {onFineChange:'setTextColor(this)'}" data-bind="click: changeColor">Pick text color</button>
             <button id="btn2" class="jscolor {onFineChange:'setTextColor2(this)'}">Pick text color2</button>
	<script>
	function setTextColor(picker) {
		document.getElementById('btn1').style.color = '#' + picker.toString()
	}
        function setTextColor2(picker) {
		document.getElementById('btn2').style.color = '#' + picker.toString()
	}
	</script>

        </div>

        <br>

        <div data-bind="component: {name: 'dashboard-grid', params: $data}"></div>
    </div>

    <script type="text/javascript">
            ko.components.register('dashboard-grid', {
            viewModel: {
                createViewModel: function (controller, componentInfo) {
                    var ViewModel = function (controller, componentInfo) {
                        var grid = null;

                        this.widgets = controller.widgets;

                        this.afterAddWidget = function (items) {
                            if (grid == null) {
                                grid = $(componentInfo.element).find('.grid-stack').gridstack({
                                    auto: false
                                }).data('gridstack');
                            }

                            var item = _.find(items, function (i) { return i.nodeType == 1 });
                            grid.addWidget(item);
                            ko.utils.domNodeDisposal.addDisposeCallback(item, function () {
                                grid.removeWidget(item);
                            });
                        };
                    };

                    return new ViewModel(controller, componentInfo);
                }
            },
            template:
                [
                    '<div class="grid-stack" data-bind="foreach: {data: widgets, afterRender: afterAddWidget}">',
                    '   <div class="grid-stack-item" data-bind="attr: {\'data-gs-x\': $data.x, \'data-gs-y\': $data.y, \'data-gs-width\': $data.width, \'data-gs-height\': $data.height, \'data-gs-auto-position\': $data.auto_position}">',
                    '       <div class="grid-stack-item-content">',
                    //'       <button data-bind="click: $root.deleteWidget">Delete me</button>',
                    '    <div class="dropdown">',
                    '    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Click me',
                    '    <span class="caret"></span>',
                    '    </button>',
                    '    <ul class="dropdown-menu">',
                    '    <table> ',
                    '      <tr><th><button data-bind="click: $root.deleteWidget"><a tabindex="-1" href="#">Delete</a></button></th></tr>',
                    '       <tr><th><button id="bnt3"  class="jscolor {onFineChange:\'setTextColor3(this)\'}">Change color</button></th></tr>',
                    '    </table>',
                    //'      <li class="jscolor {valueElement:\'chosen-value\', onFineChange:\'setTextColor(this)\'}">Change Color</a></li>',
                    //'      <li data-bind="click: $root.changeColor">Change Color</a></li>',
                    '      <li><a tabindex="-1" href="#">Copy</a></li>',
                    '      <li><a tabindex="-1" href="#">Paste</a></li>',
                    '      <li><a tabindex="-1" href="#">Mark as Completed</a></li>',
                    '    </ul>',
                    '       </div>',
                    '   </div>',
                    '   </div>',
                    '</div> '
                ].join('')
        });

        $(function () {
            var Controller = function (widgets) {
                var self = this;

                this.widgets = ko.observableArray(widgets);

                this.addNewWidget = function (i) {
                    this.widgets.push({
                        x: 0,
                        y: 0,
                        id: 'widget'+i,
                        width: i== 0 ? 2 : 1, //Math.floor(1 + 3 * Math.random()),
                        height: i== 0 ? 2 : 1, //Math.floor(1 + 3 * Math.random()),
                        auto_position: true
                    });
                    return false;
                };

                this.deleteWidget = function (item) {
                    self.widgets.remove(item);
                    return false;
                };
                /**/
                this.changeColor = function(picker){ 
                        id="btn1";
                        picker.class="jscolor {onFineChange:'setTextColor(this)'}";
                        //document.getElementById('btn1').style.color = '#' + picker.toString();
                };
                /**/
               
            };            
            var widgets = [
                {id: 'widget0', x: 0, y: 0, width: 2, height: 2, staticGrid: true },                
                {id: 'widget1', x: 2, y: 0, width: 1, height: 1},
                {id: 'widget2', x: 3, y: 1, width: 2, height: 2},
                {id: 'widget3', x: 1, y: 2, width: 1, height: 1}
            ];

            var controller = new Controller(widgets);
            ko.applyBindings(controller);
        });
    </script>
</body>
</html>

Where can I set the first widget can be a static one.
Thank you in advance for any help!

**Comment by radiolips** [comment]
Hi, @sumikoabe ! Thanks for using gridstack :).

`staticGrid` is for setting the entire grid to static. In your case, I understand you'd like just one widget to be static.

You can call `grid.movable(el, false)` and `grid.resizable(el, false)`, where `el` is the element you want to be static. Here are the appropriate API calls:
https://github.com/troolee/gridstack.js/tree/master/doc#movableel-val
https://github.com/troolee/gridstack.js/tree/master/doc#resizableel-val

**Comment by nicolasecolman** [comment]
Hello @sumikoabe,  just set this in the options object:

`disableDrag: true,
disableResize: true`

It worked for me

**Comment by sumikoabe** [comment]
Hi Nicolas,

Thanks!

Sumiko

**Comment by radiolips** [comment]
@nicolasecolman  @sumikoabe It looks like this broke quite awhile ago. It also looks like I may have fixed it at one point, but it was definitely still broken this morning. I put in a fix - in the dev branch you can now find `staticGrid` will work and `disableDrag` and `disableResize` won't be necessary (unless desired separately).
