### ISSUE TITLE
Difference between drop events

### ISSUE THREAD

**Issue by Myrdivar** [troolee/gridstack.js#521]
Hi,

How can I tell in the 'dragstop' event if the widget has been removed from the grid? In this case the 'removed' event does not fire and the 'dragstop' event is the same as if I drop the widget inside the grid. Same problem with the 'dragstart' event because when I drop a new element inside the grid the 'added' event doesn't fire.

Thanks!

**Comment by radiolips** [comment]
`removed` will be triggered when dropping as of `v0.3.0`
