### ISSUE TITLE
Get the final resize value

### ISSUE THREAD

**Issue by TheCherry** [troolee/gridstack.js#526]
There are at the moment the event "resize", its give me the width and height in pixel, that's fine.
But the values aren't the "final" values, they say me only the point there the mouse did stop the click, not the true size of the widget.

The "change" event only works for the whole grid, so its give me all widgets. Even in this data, i can't find the final width and height in pixel.

**Comment by TheCherry** [comment]
Did try to find a workarround, but the final size isent set with the change event:

```javascript
$('.grid-stack').on('change', function(event, items) {
      console.log(items[0].el.css("width"));
});
```

**Comment by radiolips** [comment]
Fixed in `v0.3.0`.

**Comment by pootpootman** [comment]
This will get you the updated values.
`$(this).data('_gridstack_node');`

**Comment by radiolips** [comment]
https://github.com/troolee/gridstack.js/issues/577
