### ISSUE TITLE
Initialising a grid below minWidth disables resize and move

### ISSUE THREAD

**Issue by gavJackson** [troolee/gridstack.js#527]
I found some odd behaviour when i was refreshing my browser and found that when a grid initialises and has less space than the minWidth resize and move gets disabled.

At time of writing (Sep 2016) you can see this happening on the gridstack home page demo grid (https://troolee.github.io/gridstack.js/), just resize your browser to less than 770px wide (i think thats the default minWidth) and then hit refresh and you will see that the grid is disabled.

I found a workaround in my project by setting the `minWidth` to 0 which is fine for my project but might be problematic if people want to use the single column mode.

**Comment by DoctaWorm** [comment]
So the media query breaking point is 768 for mobile view. The grid is disabled on dragging items yes, but once you've resized the window above 768 the grid is active again and you're able to move the objects around.

**Comment by troolee** [comment]
`minWidth` indicates a bound after which gridstack changed to one-column mode (for mobile devices). In this mode drag/drop function is disabled.

**Comment by kylietmo** [comment]
I'm seeing a similar issue where I set the minWidth to be 1280, refresh the page, and the drag/drop functionality disables around 1100 and the column mode does not enable until a width of about 685. Overall inconsistent based on the minWidth value. Only seeing this issue when refreshing the browser - once the screen has been made wider and and brought back down, it disappears.
