### ISSUE TITLE
locked item can be overlayed by an other item

### ISSUE THREAD

**Issue by hipp1010** [troolee/gridstack.js#528]
Hi,

I do a test on float grid demo in firefox. Very nice. I locked an item by editing the html code. Locking an item was ok, but I could drag an drop an other item over the locked one. Is it possible to fix/change that, so a drop would only be aside this locked element?

Thanks

**Comment by troolee** [comment]
Please try to use API instead of editing attributes. https://github.com/troolee/gridstack.js/tree/master/doc#lockedel-val

// feel free to re-open the issue if it won't work
