### ISSUE TITLE
Can't unlock locked item

### ISSUE THREAD

**Issue by hipp1010** [troolee/gridstack.js#529]
Hi,

I do a test on float grid demo in firefox. I locked an item by editing the html code. Locking an item was ok, but removing the unlock attribute frmo code doen't give back the possibility to drag and drop / move this item. It still is locked. Or how is it possible to unlock that item correctly?

Thanks

**Comment by troolee** [comment]
You need to use API instead of editing attributes. Please refer to https://github.com/troolee/gridstack.js/tree/master/doc#lockedel-val
