### ISSUE TITLE
Nested gridstacks?

### ISSUE THREAD

**Issue by anddob** [troolee/gridstack.js#53]
I would like to group widgets to one panel, so I tried to insert a sub gridstack into a "grid-stack-item-content". But resizing or moving widgets leads to several effects...
The widgets of the nested gridstack will be moved to the root gridstack - I tried to fix this by changing the reassignment of widgets in the on_end_moving function (save the original parent of widget, detach and attach to original container instead of "self.container").
The result behaves better (the elements remain in their original container) - but it seems that positioning and sorting of the root-widgets does not only affect the root level widgets but includes nested widgets in some way. Just for fun I commented out the pack and fix-collisions routines - the result did not look so bad (I can move widgets around in the nested container and can move or resize the complete container without any problems - it seems to me that gridstack could basically support my requierement).
Do you know some way to handle multiple nested gridstack instances in one document?

**Comment by troolee** [comment]
Hi,

Thank you for feedback. I will try to fix this.

**Comment by anddob** [comment]
Thank you very much for fast response - looking forward to it.

**Comment by troolee** [comment]
Gridstack may be nested now. See https://github.com/troolee/gridstack.js#nested-grids
