### ISSUE TITLE
Selective dragging/Dragging by zones

### ISSUE THREAD

**Issue by GertVen** [troolee/gridstack.js#530]
A suggestion for a future development. Please note I am using gridstack v0.2.5 so I am not sure if such a feature has been implemented in the newest version.

In my scenario I populate the gridstack widgets with charts generated with the Highcharts API. For convenience the charts allow the user to zoom in on selected areas via a selection box but with the v0.2.5 gridstack implementation zooming in on a chart results in the gridstack widget being dragged as well. This leads to some rather creative results.

I have implemented a temporarily solution by modifying the following code in the  _GridStack.prototype._prepareElementsByNode_ function:

```
   el
        .draggable(_.extend(this.opts.draggable, {
            containment:  this.opts.isNested ? this.container.parent() : null,
            start: onStartMoving,
            stop: onEndMoving,
            drag: dragOrResize,
            handle: ".grid-stack-drag-container",
            cancel: "widgetcontent"
        }))
        .resizable(_.extend(this.opts.resizable, {
            start: onStartMoving,
            stop: onEndMoving,
            resize: dragOrResize
        }));
```

In my case _grid-stack-drag-container_ is a class given to any elements that will allow the widget to be dragged, in my case a title inside the widget, and _widgetcontent_ is a class allocated to any elements preventing the widget from being dragged, such as the div containing the chart. The modified code works well in my scenario but would be nice to have a "formal" implementation. I also haven't tested what would happen if either the handle or cancel classes are not present.

Thanks!

**Comment by radiolips** [comment]
@GertVen  Thanks for reaching out! This functionality already exists in `v0.2.5`. Have you tried passing in the option `handle` when initializing your gridstack? It ends up getting passed to `draggable` already. I'm closing this, as I personally use this feature, but please reopen if you're still having issue!

**Comment by baradhili** [comment]
@radiolips are you able to drop a small example here? Thanks
