### ISSUE TITLE
Convert width 12 to width 100 (.grid-stack-item)

### ISSUE THREAD

**Issue by jayesh14** [troolee/gridstack.js#533]
Can I use .grid-stack-item with 100 Part (current it is 12 part) ? I have tried with it is 100 part. In this case, I can't able to drag and drop.

Can you please provide example for 100 part like (start 1% to 100%) Or Is it possible or not?
Here link https://jsfiddle.net/jayesh14/qv523gkz/20/

**Comment by troolee** [comment]
Have you tried this https://github.com/troolee/gridstack.js#change-grid-width ?

// feel free to re-open the issue if it won't work for you

**Comment by jayesh14** [comment]
http://stackoverflow.com/
