### ISSUE TITLE
autoPositioning not working after dragging away a grid

### ISSUE THREAD

**Issue by Wombelle** [troolee/gridstack.js#536]
Hi,

what ist the difference in the code between these two examples? I also want the grids to auto position, for example if the box on the top ist dragged away, the next boxes above will take the place of this box.

autoPositioning working:
https://troolee.github.io/gridstack.js/

autoPositioning not working:
http://troolee.github.io/gridstack.js/demo/float.html

Thanks for your help / ideas!

**Comment by AntoineEsteve** [comment]
Hello, 

The difference is the option `float`: 

>  enable floating widgets (default: false)

**Comment by Wombelle** [comment]
Hello,

thanks for the answer. Concrete in this way:

"enableFloatingWidgets: true"

Is that right?

Thanks for helping me.

**Comment by kieronsutton00** [comment]
> "enableFloatingWidgets: true"

No, use:
`Float:`
