### ISSUE TITLE
Save layout data to local storage

### ISSUE THREAD

**Issue by doganmeh** [troolee/gridstack.js#538]
It would be nice if there was an option to have gridstack save grid layout info to the local storage, and restore items size and position upon successive visit to the page. Is this something in line with gridstack's vision?

**Comment by Mijago** [comment]
You can achieve this easily with your own code.

A small snippet:
`
        let isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);

        let options    = {
            cellHeight            : 90,
            verticalMargin        : 10,
            horizontalMargin      : 10,
            alwaysShowResizeHandle: isMobile,
            resizable             : {
                autoHide: !isMobile,
                handles : 'e, s, w, se',
            },
            float                 : false,
            width                 : 12,
            animate               : true
        };
        let grid_stack = $('.grid-stack');

        grid_stack.gridstack(options);
        let grid = grid_stack.data('gridstack');

        grid_stack.on('change', function (event, items) {
            // Save to localstorage
            let res = _.map($('.grid-stack .grid-stack-item:visible'), function (el) {
                el       = $(el);
                let node = el.data('_gridstack_node');
                return {
                    // save additional stuff here, but no pointers or circular stuff!
                    // You need to save every data that is needed to recreate the node
                    // If you get the data from the server, it might be only the id
                    // Sidenode: you also should save the min and max height/widht
                    id    : el.attr('data-custom-id'),
                    x     : node.x,
                    y     : node.y,
                    width : node.width,
                    height: node.height
                };
            });
            localStorage.setItem("grid-layout", JSON.stringify(res))
        });

        // Load from LocalStorage
        let serialization = null;
        if (serialization = localStorage.getItem("grid-layout")) {
            grid.removeAll();

            _.each(JSON.parse(serialization), function (node) {
                // Load additional stuff here
                // Remember: There MUST be a surrounding div around your element.
                // In this div the data (like width) gets saved
                grid.addWidget($('<div><div class="grid-stack-item-content"> </div></div>'),
                    node.x, node.y, node.width, node.height);
            });
        }
`

You might want to replace let with var.

**Comment by daya-s** [comment]
> You can achieve this easily with your own code.
> 
> A small (but working, i tested it!) snippet:
> 
> ```
>     let isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
>     let options    = {
>         cellHeight            : 90,
>         verticalMargin        : 10,
>         horizontalMargin      : 10,
>         alwaysShowResizeHandle: /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);,
>         resizable             : {
>             autoHide: !isMobile,
>             handles : 'e, s, w, se',
>         },
>         float                 : false,
>         width                 : 12,
>         animate               : true
>     };
>     let grid_stack = $('.grid-stack');
> 
>     grid_stack.gridstack(options);
>     let grid = grid_stack.data('gridstack');
> 
>     grid_stack.on('change', function (event, items) {
>         // Save to localstorage
>         let res = _.map($('.grid-stack .grid-stack-item:visible'), function (el) {
>             el       = $(el);
>             let node = el.data('_gridstack_node');
>             return {
>                 // save additional stuff here, but no pointers or circular stuff!
>                 // You need to save every data that is needed to recreate the node
>                 // If you get the data from the server, it might be only the id
>                 // Sidenode: you also should save the min and max height/widht
>                 id    : el.attr('data-custom-id'),
>                 x     : node.x,
>                 y     : node.y,
>                 width : node.width,
>                 height: node.height
>             };
>         });
>         localStorage.setItem("grid-layout", JSON.stringify(res))
>     });
> 
>     // Load from LocalStorage
>     let serialization = null;
>     if (serialization = localStorage.getItem("grid-layout")) {
>         grid.removeAll();
> 
>         _.each(JSON.parse(serialization), function (node) {
>             // Load additional stuff here
>             // Remember: There MUST be a surrounding div around your element.
>             // In this div the data (like width) gets saved
>             grid.addWidget($('<div><div class="grid-stack-item-content"> </div></div>'),
>                 node.x, node.y, node.width, node.height);
>         });
>     }
> ```
> You might want to replace let with var.

hi. Thanks for the help. but my content inside **<div class="grid-stack-item-content"> </div>** not rendering after Load from localStorage.
