### ISSUE TITLE
Disable collision and movement directions

### ISSUE THREAD

**Issue by einarsozols** [troolee/gridstack.js#539]
1. Is it possible to disable collision? So if I drag grid-stack-item and it collides with other item don't swap them just don't allow this move.
2. Is it possible to set movement direction? I want to set up directions - some items need to move only vertically, but some only horizontally. 

Thanks.

**Comment by Mijago** [comment]
1. You can try to set every other item to `data-gs-no-move`. This should stop them from moving.

**Comment by einarsozols** [comment]
@Mijago Thanks

**Comment by radiolips** [comment]
@einarsozols Unfortunately, 2 isn't possible right now. However, one way of achieving this would be to set certain widgets to `data-gs-no-move` on dragstart. For example, if you are moving a widget that should only move horizontally, set every widget above/below the selected widget to not move.

**Comment by radiolips** [comment]
Closing - problem appears resolved. Please let me know if this is not the case.
