### ISSUE TITLE
TypeError: $(...).gridstack is not a function

### ISSUE THREAD

**Issue by syshen** [troolee/gridstack.js#547]
Try to use gridstack in a Vue project. I am using NPM to install gridstack. 

gridstack: 0.2.6
JQuery: 3.1.1
JQuery ui: 1.12.1

But keep getting this error: "TypeError: $(...).gridstack is not a function"

**Comment by radiolips** [comment]
@syshen Make sure to load in jQuery before loading in gridstack. Let me know if that helps.

**Comment by SkoZombie** [comment]
@syshen I got this when I didn't reference lodash directly. Try adding:

`    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.5.0/lodash.min.js"></script>`

In your headers before gridstack.js and see if that fixes your issue

**Comment by JohnnyDeeee** [comment]
I got the exact same error and cant seem to fix it.. I tried @SkoZombie his method but it didnt solve it..

I lost 2 days of work because of this and i really want to get this to work because it looks like a really usefull plugin..

**Comment by Ruud-cb** [comment]
Solution, anyone?

**Comment by GeraintEdwards** [comment]
After some investigation is appears that version 0.3.0 of GridStack is not compatible with lodash 4.0+ .

Using version 3 (up to 3.10.1 is ok) e.g. ` <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.5.0/lodash.min.js"></script>`

Versions 4.0.0 onwards right up to 4.17.4 throws this error.  In my case I get

`TypeError: this.grid is undefined`

**Comment by radiolips** [comment]
I'm using lodash v > 4.0 without problem. Is anyone here still having an issue?

**Comment by radiolips** [comment]
Closing because the issue has hopefully resolved itself. Please reopen if this is not the case!

**Comment by chdeshpc** [comment]
Hi @troolee ,@radiolips,

I am facing the same issue. In our product we are using jquery-3.0.0.min.js version. And I get the following error.
 $(...).gridstack is not a function TypeError: $(...).gridstack is not a function.

Below is the order of my scripts:
    <link rel="stylesheet" href="../layoutScripts/bootstrap.min.css">         
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.0/jquery-ui.js"></script>
    <script src="../layoutScripts/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.5.0/lodash.min.js"></script>  
    <script src="../layoutScripts/gridstack.js"></script>
    <script src="../layoutScripts/gridstack.jQueryUI.js"></script>

I need a fix for this ASAP.
Can you please help me?

Thank you.
