### ISSUE TITLE
widget transfer from one grid to another

### ISSUE THREAD

**Issue by AurelDragut** [troolee/gridstack.js#548]
I am trying to create a page with two grids:
- the left grid is the destination,
- the right grid is the source grid

i didn't get how to move the widget in the left grid entirely (i added a 'src' attribute that contains an image path, but the widget added to the left is missing it). is there anything i did wrong or not at all? thank you!

also if the clone issue is not yet fixed, is there any way that i could reload the right div's content when i start to drag a widget from it?

here is what i did so far... https://github.com/AurelDragut/gridstack

**Comment by radiolips** [comment]
@AurelDragut Could you provide an update on this and a jsfiddle? The link your provided no longer works, but I'd like to try to offer you help.

**Comment by AurelDragut** [comment]
Thanks, but i had to giveup on that project and i don't know if i will try to do it again. I had to some sort of grid with photos that would have been dragged from right grid to the left one (some sort of a puzzle) and in the end integrate this into wordpress.

**Comment by radiolips** [comment]
That sounds really interesting! I'm going to close this ticket, but if you do have a chance to start the project again, let me know! I'd be happy to help.
