### ISSUE TITLE
remove_widget with problem when dragdrop after

### ISSUE THREAD

**Issue by Nankym** [troolee/gridstack.js#55]
Hello @troolee 

In my project, I use a grid.remove_widget(el). However, after of use this method, and move the widget(drag drop), the grid shows the widget again.

What can be done?

<code javascript>
if(checked) {
    if($("wdgWidgetID").length > 0) {
        grid.remove_widget($("#wdgWidgetID"));
    }
} else {
    if($("wdgWidgetID").length == 0) {
        grid.add_widget("< span id='wdgWidgetID' >Title< /span >", 0, 0, 1, 2, true);
    }
}
</code>

Obs.: The span no has space

![captura](https://cloud.githubusercontent.com/assets/3621189/6000687/02e790b8-aac8-11e4-98f9-757df17a36ed.png)

Att

**Comment by troolee** [comment]
Hi Nankym,

Can you provide code sample?

**Comment by troolee** [comment]
Please provide more info. For now I cannot reproduce the bug.
