### ISSUE TITLE
removing an element by dragging does not trigger the 'removed' event

### ISSUE THREAD

**Issue by sthuck** [troolee/gridstack.js#550]
Hi,

Not sure if this is a bug or intended behaviour, but dragging an element outside the grid to delete it using the 'removable: true' option, does not trigger 'removed' event. 
Relevant code seems to be [here](https://github.com/troolee/gridstack.js/blob/master/src/gridstack.js#L1156). 

If this is intended behaviour my two cents are that it should trigger an event :)

**Comment by radiolips** [comment]
@sthuck You're right. This will be resolved.

**Comment by jorsai** [comment]
Sorry I'm relative new at GitHub. 
How can we know if this bug is fixed?

**Comment by RodgerLai** [comment]
@jorsai you will know the bug fixed when the issue is closed

**Comment by radiolips** [comment]
@jorsai Fixed in develop branch. It'll be released later this evening.

**Comment by jordihuertas** [comment]
Thank you!
