### ISSUE TITLE
Unable to disable resizing for an element

### ISSUE THREAD

**Issue by PnkPriinx** [troolee/gridstack.js#554]
Hi,

I'm trying to disable the resizing function for an element in the grid with the data-gs-no-resize option but the same behavior is applied for all grid elements. 

There is any way to apply this only for an element?

**Comment by radiolips** [comment]
@PnkPriinx You can use `grid.resizable(el, false)`. - https://github.com/troolee/gridstack.js/tree/master/doc#resizableel-val
