### ISSUE TITLE
Unable to get reference to Widget added by dragging

### ISSUE THREAD

**Issue by abhinavsayan** [troolee/gridstack.js#556]
The added(event, items) event is not raised when a widget is added by dragging. How can I get a reference to the widget that was added by dragging from outside grid stack.

**Comment by KeithScheiwiller** [comment]
@abhinavsayan I hit the issue as well, but in case you haven't figured it out the `change` event still seems to pick up such widgets.

**Comment by vbinithyanandamv** [comment]
The possible solution would be adding _triggerAddevent on the container drop function.

Workaround might be creating your own  drop event listener. something like this

element.on('drop',function(e,item){
    });

element must be your grid container.

**Comment by radiolips** [comment]
This has been fixed in the develop branch and will be officially released in `v0.3.0` later today.
