### ISSUE TITLE
Dynamic widget add styling not working - Angular 2

### ISSUE THREAD

**Issue by nsatishnaidu** [troolee/gridstack.js#557]
We are using gridstack in an Angular 2 project by wrapping it inside of a component. 

The component is a board that contains various other child components that can be dragged around. For e.g. a Sticky note (custom component) or a note editor (custom component wrapping a froala editor). 

Here is our Board.component.ts and Board.component.html

[Board.component.ts.txt](https://github.com/troolee/gridstack.js/files/585393/Board.component.ts.txt)
[Board.component.html.txt](https://github.com/troolee/gridstack.js/files/585398/Board.component.html.txt)

We are using a model to load the controls and they work perfectly fine on start up. But if we were to add a new component by adding an item to the model (collection) the added item does not seem to be draggable. I have even tried to add the draggable classes to the item in HTML, but no luck. 

What am I missing here? The gridstack jquery looks at the classes right, so I am confused. Even adding a simple widget with no custom components is not draggable.

**Comment by SkoZombie** [comment]
I found I had to force it and I had to put an extra div around items when creating them:

```
var grid = $('.grid-stack').data('gridstack');
var el = $('<div class="grid-stack-item"><div class="grid-stack-item-content">New</div></div>');
grid.addWidget(el,0,0,1,1,true);
grid.movable(el,true);
```

**Comment by nsatishnaidu** [comment]
Adding a simple element works. The trouble we are facing is adding an angular component/template. Adding it this way just renders the HTML literal and does not compile it in any way.

**Comment by radiolips** [comment]
@nsatishnaidu I really don't know much about angular. You can use the angular version of gridstack, though: https://github.com/kdietrich/gridstack-angular

**Comment by Julienng** [comment]
I think it's a better approach to use `makeWidget` instead of `addWidget`when your ui framework modify the dom: 
- add you item with angular (use `data-ws-x` etc for position)
- use `makewidget` of `gridstack` to reference your item into gridstack (you can create a `directive` to handle that)
