### ISSUE TITLE
Creating Gridstack Custom Binding with Knockout JS

### ISSUE THREAD

**Issue by ascendantofrain** [troolee/gridstack.js#56]
Is it possible to push a new grid item to an array and then rebuild the gridstack grid after the update??  My view has a button that pushes 'default' grid item information to an array and then appends it to the grid in the view.  Any advice on how I can achieve my desired results??

    <div class="grid-stack" data-bind="foreach: tiles, gridstack: { tiles: tiles }">
        <div class="grid-stack-item" data-bind="attr: { 'data-gs-x': rect.x - 1, 'data-gs-y': rect.y - 1, 'data-gs-width': rect.width, 'data-gs-height': rect.height, 'data-gs-min-height': rect.minHeight, 'data-gs-max-height': rect.maxHeight, 'data-gs-min-width': rect.minWidth, 'data-gs-max-width': rect.maxWidth }">
            <div class="grid-stack-item-content">
                <h3 data-bind="text: title"></h3>
            </div>
        </div>
    </div>

    ko.bindingHandlers.gridstack = {
        buildGrid: function(element, valueAccessor) {
            var gridstackWidth = $('.grid-stack').width(),
                widgetWidth = (gridstackWidth / 5) - 23,
                widgetHeight = widgetWidth / 2.5,
                reflow = function () {
                    $.each(Highcharts.charts, function () {
                        this.reflow();
                    });
                },
                gsOptions = {
                    always_show_resize_hande: true,
                    cell_height: widgetHeight,
                    handle: '.editing-options .handle',
                    vertical_margin: 5
                },
                gridstack = function () {
                    $(element).gridstack(gsOptions);
                    $(element).on('change', function(event, ui) {
                        reflow();
                    });
                };

            gridstack();
        },
        init: function (element, valueAccessor) {
            var options = ko.unwrap(valueAccessor()); // create subscription?
            ko.bindingHandlers.gridstack.buildGrid(element);
        },
        update : function(element, valueAccessor) {
            var opts = ko.unwrap(valueAccessor()),
                tiles = ko.unwrap(opts.tiles);

            ko.bindingHandlers.gridstack.buildGrid(element);

        }
    };

**Comment by troolee** [comment]
Hi,

Doen't this [sample](https://github.com/troolee/gridstack.js#use-with-knockoutjs) work for you? Any reason you need custom binding instead of component?

**Comment by ascendantofrain** [comment]
Mostly unfamiliarity with using the components than anything else.  Not exactly sure how the component works but I can take a deeper look at it.

**Comment by troolee** [comment]
Here is a working sample of usage with knockout.js http://troolee.github.io/gridstack.js/demo/knockout.html

This is how I use it.

**Comment by ascendantofrain** [comment]
How would this work if you were dynamically added widgets to the array after initialization??  I have a view model object "tiles" already specified in another viewmodel file.  How can I incorporate that currently existing view model specs into this component??

**Comment by troolee** [comment]
I've updated the knockout sample page. Please take a look http://troolee.github.io/gridstack.js/demo/knockout.html
