### ISSUE TITLE
minWidth-minHeight for items

### ISSUE THREAD

**Issue by iinnaann** [troolee/gridstack.js#562]
It's possible to set for all items a minWidth?

In the documentation there is a option => minWidth but this is not working?

**Comment by AurelDragut** [comment]
where did you set that minWidth?

**Comment by iinnaann** [comment]
@AurelDragut 
$scope.options = {
        cellHeight: 5,
        acceptWidgets: '.grid-stack-item',
        disableResize: false,
        float: true,
        animate: true,
       minWidth: 5    => I tried here also in 300(px)
    };

**Comment by AurelDragut** [comment]
that minWidth has nothing to do with what you want 
```
minWidth - minimal width. If window width is less, grid will be shown in one-column mode (default: 768)
```
the minwidth that you specify in the widget definition is about the minimum number of columns that it gets on

**Comment by iinnaann** [comment]
Okay I understand now. Is there an option/setting for the items?
I want a min Width and also min Height for the Items (during resize)

**Comment by AurelDragut** [comment]
you can set min/max width/height in the addWidget parameters, or in the array of predefined widgets

**Comment by radiolips** [comment]
Thanks, @AurelDragut .
