### ISSUE TITLE
Detect oneColumnMode

### ISSUE THREAD

**Issue by sdesclaux** [troolee/gridstack.js#563]
On a window resize event, i want to resize my gridstack (cellHeight and vertical margin), it's working fine but in order to detect the oneColumnMode, i need to use a private function : _isOneColumnMode(). Is there a better way ti check the oneColumnMode ?

Here is my code (1080, 50 and 20 are parameters that I fixed) :

    `$(window).on('resize', function () {
            resizeGridStack();
        });

       function resizeGridStack() {
            var grid = $('.grid-stack').data('gridstack');
            var rapport = grid.container.width() / 1180;
            if (grid._isOneColumnMode())
                rapport = rapport * grid.opts.width;
            grid.cellHeight(50 * rapport);
            grid.verticalMargin(20 * rapport);
        }`

**Comment by radiolips** [comment]
@sdesclaux That's the best way! Though internal, it's a safe method to call, because it will always return the same boolean solution as gridstack will determine internally.
