### ISSUE TITLE
addWidget not working as expected with dynamic elements

### ISSUE THREAD

**Issue by mbajur** [troolee/gridstack.js#567]
I'm still not sure if i need to post it here or on vue forums so i decided to post it in both places,

Basically, i'm trying to add a Vue.js component as a gridstack item (using vue custom component syntax). For some reason, the element i'm adding can't be resized nor dragged.

Here is a working demo of this: http://codepen.io/anon/pen/QGxeJB?editors=1010

Please notice that vue elements created before gridstack initialization works fine. Just the ones added by a button click are broken.

Thanks in advance.

**Comment by Julienng** [comment]
You have to notify gridstack that you add by hand a new item. See [makeWidget](https://github.com/troolee/gridstack.js/tree/master/doc#makewidgetel) in the doc

**Comment by mbajur** [comment]
Yeah that was it. Thanks!

**Comment by ArtisanTinkerer** [comment]
Can you post your solution please?

**Comment by Tropicalista** [comment]
@ArtisanTinkerer  please check this: http://codepen.io/Tropicalista/pen/PmKajR
