### ISSUE TITLE
gridstack change event

### ISSUE THREAD

**Issue by crashnick16** [troolee/gridstack.js#57]
does the items object in the change event contain an array of all the items in the grid or only the ones that are changing position? 

$('.grid-stack').on('change', function (e, items) {
  
});

**Comment by ascendantofrain** [comment]
What does the browser's console outuput if you do a console log of the object?

**Comment by crashnick16** [comment]
i was just doing that and it seems that only the affected widgets show up. I think this is how it should be really as we can always write a serialisation function to save all of them. It might be nice to have this function included in the library though
