### ISSUE TITLE
Is lodash REALLY needed anymore?

### ISSUE THREAD

**Issue by tm1000** [troolee/gridstack.js#570]
Do you think lodash is really needed for this library anymore?

Take a peek at https://www.reindex.io/blog/you-might-not-need-underscore/

**Comment by radiolips** [comment]
We're getting rid of all dependencies at the same time - not just lodash :)

**Comment by tm1000** [comment]
Nice! I wasn't sure as it appears lodash is still required in 3.0-dev but if you are working through the dependencies then it makes sense.

**Comment by radiolips** [comment]
@tm1000 I'm closing this, but if you'd like to discuss it further, feel free to re-open.
For the record, I fully expect 3.0's release to remove some, if not all, of its dependencies.

**Comment by piernik** [comment]
0.3 is out but there is still lodash (with over 0.5MB). Is it necessarry?

**Comment by tm1000** [comment]
@piernik doesn't look like it's going to happen. See https://dylandreams.com/2017/04/26/gridstack-10-coming-soon/

@radiolips any major reason why?

**Comment by tm1000** [comment]
> Hey Andrew,
> 
> When we were considering which dependencies to remove, we factored in the quality of the library, the likelihood that it’d already be in a project, and the time it would take us to remove from gridstack. The problem with lodash is primarily that we have many references that would take time to rewrite. Eventually we will remove lodash, but we decided we wouldn’t have time before 1.0 is completed. If you’d like, we’d love to have a PR in to remove it.
> 
> Thanks for using gridstack! Let me know if you have any other questions.

**Comment by piernik** [comment]
@tm1000 thanks
