### ISSUE TITLE
Load a grid for already rendered markup

### ISSUE THREAD

**Issue by timrabbetts** [troolee/gridstack.js#575]
I have a html page of widgets already loaded, using the correct markup for grid stack.  Works great, resize move etc.  When I use the load grid code it removes all widgets, creates new empty widgets with the corect grid layout.  I want to load a grid that I saved, but for already rendered widgets, is this possible?  Great work by the way!

**Comment by radiolips** [comment]
@timrabbetts Happy to help! Could you provide a `jsfiddle` to help us get a better understanding of what you're trying to accomplish?

**Comment by timrabbetts** [comment]
Sure thing here it is, you can see my original markup which does work.  Then I used the save on change code to generate my saved grid positions.  But using the load grid positions code will wipe out and create new widgets in the correct location which is not what I want.  Ideally I want to be able to iterate over the current widgets and have them positioned as per save data?  Thanks for any help: https://jsfiddle.net/8sox79aL/1/

**Comment by qlerebours** [comment]
Hi @timrabbetts ! I had the same issue and i solved it with a simple code change: 

SaveGrid function is the same (I'm just saving the grid layout in a cookie)
```
var saveGrid = function () {
    var data = _.map($('.grid-stack > .grid-stack-item:visible'), function (el) {
        el = $(el);
        var node = el.data('_gridstack_node');
        return {
            x: node.x,
            y: node.y,
            width: node.width,
            height: node.height
        };
    }, this);
    $.cookie("grid-layout", JSON.stringify(data)); //Saving in a cookie
    return false;
};
```

LoadGrid function modified:
```
var loadGrid = function () {
    //I remove the "grid.removeAll"
    if(typeof $.cookie("grid-layout") !== 'undefined') { //I'm making sure a cookie has been saved
        var data = JSON.parse($.cookie("grid-layout")); //Getting the content
        var items = $('.grid-stack').find('.grid-stack-item'); //An item is now a grid-stack-item
        $.each(items, function (key, gridItem) { //Foreach item, i'll set the attributs as saved
            $(gridItem).attr('data-gs-x', data[key].x);
            $(gridItem).attr('data-gs-y', data[key].y);
            $(gridItem).attr('data-gs-width', data[key].width);
            $(gridItem).attr('data-gs-height', data[key].height);
        }, this);
    }
    return false;
};
```

Hope it will help !

**Comment by timrabbetts** [comment]
Great stuff, hook it up and now its working, thanks for the help, they should put this in the docs as well cool!

**Comment by timrabbetts** [comment]
This doesnt work, it works to init the grid but on resize the grid breaks, will try out some ideas.

**Comment by radiolips** [comment]
@timrabbetts Sorry, I'm still a little confused. Could you try again to clarify for me? If there's a bug, we need to fix it, and if it's just some documentation we need to update, we can do that, too. I know it's been a few months, but I hope you'll still be able to fill me in on the issue! Thanks!

**Comment by qlerebours** [comment]
@radiolips I had the same "issue" but I think what happens is what you wanted to design.
When we call the `loadGrid` function, it clears the grids (they are now empty) and reformat them as described in the `serializedData`. 
The problem we both encountered is that we had some content in our grids (that was cleared when we called the load function).
This is why I wrote a solution to this problem, with a new `loadGrid` function that rearrange the existing grids (and doesn't erase them).

**Comment by timrabbetts** [comment]
Hi, sorry I didnt end up fixing this, theres plenty of detail here, let me know whats not clear.  i ended using jquery ui instead.

**Comment by radiolips** [comment]
The example provided on the main gridstack page is only an example. It's missing several possible widget properties. It's also missing all of the content of the widget, which I think is what @timrabbetts is referring to.

The example is provided to avoid too many repeated questions about the topic of serialization. The example, however, does not cover all scenarios. In this situation, the developer needs to handle retaining this information.

I'm closing this ticket out, but if anyone is trying to serialize something and is having a problem, please include a jsfiddle and I'll do my best to help.

**Comment by timrabbetts** [comment]
So come back to this and the problem is the example for save and load wipes the current grid out, and if you just update the properties like data-gs-width, after the grid is loaded when you drag an item the entire grid resets.  Its a bit of a hack but I worked around this with the following code.  I think the confusion here is I am loading an html page with all the widgets and the content, then triggering some js to load the grid dimensions, not expecting that when that happens the grid content gets wiped, a simple update example could solve this but for now this works.
`this.loadGrid = function() {
        // Load grid positions
        $.ajax({
          url: '/load/grid',
          type: 'GET',
          dataType: 'json',
          error: function() {
            console.log('ajax error has occured');
          },
          success: function(data) {
            console.log(data);

            var markup = [];

            // Go through all widgets and store there content first.
            $('.grid-stack > .grid-stack-item:visible').each(function () {
              markup[$(this).attr('id')] = $('.grid-stack-item-content', this).html();
            });

            // As per demo load the grid, problem is it wipes previous grid contents.
            var grid = $('.grid-stack').data('gridstack');
            grid.removeAll();
            grid.batchUpdate();
            $.each(data, function( id, node ) {
              grid.addWidget($('<div><div id="' + id + '" class="grid-stack-item-content"></div></div>'), node);
            });
            grid.commit();

            // Load markup back.
            $('.grid-stack > .grid-stack-item:visible .grid-stack-item-content').each(function () {
              $(this).html(markup[$(this).attr('id')]);
            });

          }
        });
      }`

**Comment by timrabbetts** [comment]
`this.loadGrid = function() {
        // Load grid positions
        $.ajax({
          url: '/load/grid',
          type: 'GET',
          dataType: 'json',
          error: function() {
            console.log('ajax error has occured');
          },
          success: function(data) {
            console.log(data);

            var markup = [];

            // Go through all widgets and store there content first.
            $('.grid-stack > .grid-stack-item:visible').each(function () {
              markup[$(this).attr('id')] = $('.grid-stack-item-content', this).html();
            });

            // As per demo load the grid, problem is it wipes previous grid contents.
            var grid = $('.grid-stack').data('gridstack');
            grid.removeAll();
            grid.batchUpdate();
            $.each(data, function( id, node ) {
              grid.addWidget($('<div><div id="' + id + '" class="grid-stack-item-content"></div></div>'), node);
            });
            grid.commit();

            // Load markup back.
            $('.grid-stack > .grid-stack-item:visible .grid-stack-item-content').each(function () {
              $(this).html(markup[$(this).attr('id')]);
            });

          }
        });
      }`

**Comment by adumesny** [comment]
@timrabbetts, from a quick read, have you tried using `update()` with your new dimension and the latest code (make sure to batch/commit) using the latest code ?  (see https://jsfiddle.net/adumesny/jqhkry7g)
It should work, if not re-open this bug with an updated jsfiddle. thanks.
