### ISSUE TITLE
is it possible to customize the sort functionality as per width value

### ISSUE THREAD

**Issue by VivekMJadhav** [troolee/gridstack.js#578]
I used the sort functionality but it sort/move by width 1, is it customize by any function to change it to as per width value

**Comment by radiolips** [comment]
@VivekMJadhav What are you trying to accomplish?

**Comment by VivekMJadhav** [comment]
@radiolips  
i split div's in 3 columns
have 1 widget with width 4 
but while sorting this widget it will move with width 1 
i want to it will move with full width 4 only at a time with in the columns only

**Comment by radiolips** [comment]
@VivekMJadhav Could you provide a jsfiddle? It'll help me understand.

**Comment by tonywr71** [comment]
You would be better off using a standard javascript array sort if you want a custom sort.

e.g. (note, this is my own custom object type, but you should be able to get the idea. blocks is an array)
```
var sortedBlocks = blocks.sort((a: any, b: any) => {
            if (a.block.y < b.block.y) return -1;
            if (a.block.y === b.block.y && a.block.x < b.block.x) return -1;
            return 1;
        });

```
