### ISSUE TITLE
Option to Have Resizable Widgets Snap to Grid

### ISSUE THREAD

**Issue by ascendantofrain** [troolee/gridstack.js#58]
Using the jQuery UI Resizable widget...is it possible to gather the available width/heights that the gridstack_items can resize to and pass that through to the 'grid' option of the resizable UI widget??

**Comment by troolee** [comment]
Hi,

What do you mean? Can you describe a use case?

**Comment by ascendantofrain** [comment]
My personal use case is more of a UX/UI preference.  I would like for the widget being resized to be able to snap automatically, like Gridster does, to the next available spot while still in resizing mode.

![screenshot 2015-02-03 16 16 12](https://cloud.githubusercontent.com/assets/781671/6029704/69f32710-abc0-11e4-95b5-1490b247bb69.png)
![screenshot 2015-02-03 16 18 29](https://cloud.githubusercontent.com/assets/781671/6029705/6b7a23d6-abc0-11e4-9afa-acf0c25b4882.png)


In the image above, it just seems strange that the placeholder can be resized to below or above the min/max values and would be nice if the  placeholder 'image' doesn't resize past the min/max values.

If any of that makes sense...apologies if it doesn't.

**Comment by troolee** [comment]
It is fixed now. Min/max constrains are respected during resizing.
