### ISSUE TITLE
Can I get more fine tuned with size

### ISSUE THREAD

**Issue by edlisten** [troolee/gridstack.js#581]
Basically I am wondering if I can have more width blocks to choose from than the twelve?  Also the same for the height too.   For example it looks like each box increments both height and width at about 50px, I would like to change it so that it increments at 10px or so.

**Comment by radiolips** [comment]
@edlisten You can certainly do a different number of columns! https://github.com/troolee/gridstack.js#different-grid-widths

You can also change cellHeight by passing in a parameter when you initialize the grid:

https://github.com/troolee/gridstack.js#basic-usage

Let me know if you have any other issues!
