### ISSUE TITLE
Change grid width problem

### ISSUE THREAD

**Issue by serkanr** [troolee/gridstack.js#583]
First I apologize for my bad english,

I am trying to change the size of the grids, but when I make 100 instead of 12 , the shifts become corrupted how can I fix it?

I get wrong results when I increase the width or move it to the left or right

**Comment by troolee** [comment]
How are you trying to do this? Have you checked this https://github.com/troolee/gridstack.js#change-grid-width ?

Please feel free to re-open the ticket if the issue is still exist.
