### ISSUE TITLE
Width cannot exceed 12 columns

### ISSUE THREAD

**Issue by gokhancs** [troolee/gridstack.js#584]
Hi, 

I would like to use gridstack on my high-resolution large display system. The display of my workspace consists of ~16K pixels horizontally. It is a display wall of around 8 meters wide. Therefore I need many columns for my use case. When I change the width property, it is fine until 12 columns, but it is not still not sufficient. When I exceed 12, there are problems in the layout, and it doesn't really display more than 12 columns. How can I change the number of columns correctly? Thank you.

**Comment by serkanr** [comment]
var styles = "";
var gridw = 200;
    for(var i = 0; i <= gridw; i++){
        styles += ".grid-stack-item[data-gs-width='"+i+"'] {width: "+((i*100)/gridw)+"%;}" ;
        styles += ".grid-stack-item[data-gs-x='"+i+"'] {left: "+((i*100)/gridw)+"%;}" ;
        styles += ".grid-stack-item.grid-stack-item[data-gs-min-width='"+i+"'] {min-width: "+((i*100)/gridw)+"%;}" ;
        styles += ".grid-stack-item.grid-stack-item[data-gs-max-width='"+i+"'] {max-width: "+((i*100)/gridw)+"%;}" ;
    }
    $('<style>'+ styles +'</style>').appendTo(document.head);

**I use this code, But this is wrong maybe it will work properly for you**

**Comment by gokhancs** [comment]
where should we use that code?

**Comment by serkanr** [comment]
Kardeşim türkmüşsün ya sende :D bana mail adresini yazar mısın ben sorunu biraz çözdüm yardımcı olayım

**Comment by gokhancs** [comment]
evet haha. cs.gokhancetin@gmail.com

cok tesekkurler simdiden

**Comment by randellhodges** [comment]
I am having a problem using more than 12 columns. I added my comments to a closed issue. I see this one is open.

I used sass to define 24 columns and I also added 24 as width option inside the javascript. The problem is when I move things around, they resize funny and when I drag them, I have to drag beyond where I want to get it to stick in the correct spot.

**Comment by serkanr** [comment]
$('.grid-stack').gridstack({
        width: 24,
        height: 10,
        cellHeight: 20
 });

Did you change the width here?

**Comment by randellhodges** [comment]
I did. I still had issues until I changed the sass.

**Comment by troolee** [comment]
Yes, you need to generate a css for non-12-columns grids

Please check this https://github.com/troolee/gridstack.js#change-grid-width

**Comment by rami-alloush** [comment]
I know this might not be the cleanest snippet! but this is what finally worked for me. using v0.3.0 (I had to use this version due to the overlap problem in v0.4.0
`$gridstack-columns: 24;

@for $i from 1 through $gridstack-columns {
    &.grid-stack>.grid-stack-item[data-gs-width='#{$i}'] { width: (100% / $gridstack-columns) * $i;  min-width: (100% / $gridstack-columns) * $i;}
    &.grid-stack>.grid-stack-item[data-gs-x='#{$i}'] { left: (100% / $gridstack-columns) * $i; }
    &.grid-stack>.grid-stack-item[data-gs-min-width='#{$i}'] { min-width: (100% / $gridstack-columns) * $i; }
    &.grid-stack>.grid-stack-item[data-gs-max-width='#{$i}'] { max-width: (100% / $gridstack-columns) * $i; }
}`
Note: no need to load `gridstack-extra.min.css`
