### ISSUE TITLE
Widgets with a height larger than 1 do not return to their original position

### ISSUE THREAD

**Issue by JustusLauten** [troolee/gridstack.js#586]
When I drag widget A to the position of widget B (height > 1), widget B moves aside as expected. But when I decide to put widget A to a different position (while I am still dragging it), widget B will not return to its original position.

You can find a small example of my problem here: https://justuslauten.github.io/gridstack

Drag one of the grey widgets to the position of the red widget, and back. The red widget will not return to its original position.

**Comment by radiolips** [comment]
Note to self / anyone looking at this in the future: This only happens when you push widget B down one spot. If you more it down multiple spots, it'll return to its correct location.

**Comment by adumesny** [comment]
you can use https://github.com/troolee/gridstack.js/blob/develop/demo/two.html to test your fix using grey box (float grid) and it fixes the issue. Even dragging green 'Drag me" onto float grid shows the issue.
![twogrid](https://user-images.githubusercontent.com/3496166/30294183-175bec52-96f1-11e7-93a7-8aab1723fbae.png)
