### ISSUE TITLE
dragstop event

### ISSUE THREAD

**Issue by SergeyPiskov** [troolee/gridstack.js#59]
if attached to dragstop event using following code
$('.grid-stack').on('dragstop', function (event, ui) {
    var grid = this;
    var element = event.target;
});
event will occur before move to new position and can not get real X and Y.

**Comment by juchi** [comment]
I am using the dragstop event to get the new position of an element and it's working fine in my app.
Maybe you did declare your listener before the grid is being initialized (event handlers are executed in the same order they were declared according to jquery documentation) ? In this case moving it after the grid init should solve your issue.

**Comment by troolee** [comment]
What is your use case? You probably need to wait until animation finished. 

If you need to save widget position to db you need to use `onchange` event.

**Comment by troolee** [comment]
Please try this:

```javascript
$('.grid-stack').on('dragstop', function (event, ui) {
    var element = $(event.target);
    var node = element.data('_gridstack_node');
    console.log(node);
});
```

`node` object will contain new `x`, `y`, `width`, `height`.

**Comment by BeamsHakeem** [comment]
use on.change event
