### ISSUE TITLE
Possible to not show the diagonal resize handle on hover

### ISSUE THREAD

**Issue by tanyona** [troolee/gridstack.js#590]
Is it possible not to show the diagonal resize handle on the lower corner(s) of a cell when one hovers over with the mouse.

**Comment by radiolips** [comment]
Yep! They're done in the CSS. You can override the CSS as mentioned here - 
http://stackoverflow.com/questions/10801676/removing-handle-image-from-jquery-ui-resizable-element

Let me know if you need any more assistance!

**Comment by tanyona** [comment]
Thanks. I think I'm OK for now..
