### ISSUE TITLE
Using data-gs-min-width="0" and resizing from left border causes item to move

### ISSUE THREAD

**Issue by tanyona** [troolee/gridstack.js#591]
If you have an item with **data-gs-min-width="0"** and you resize it by dragging the left border, after it reaches the minimum width (1 column I believe) it starts to move the item towards the right. With the same setting, if you resize by dragging the right border, it stops when it reaches the minimum width and the item doesn't move. If you completely omit this attribute and drag from the left, it doesn't move after reaching the minimum width.

**Comment by radiolips** [comment]
@tanyona Interesting! While this is sort of a bug, it doesn't happen with `data-gs-min-width="1"`, and a value of 0 isn't actually valid. It's an interesting find, but it's a scenario that shouldn't actually happen in reality.
