### ISSUE TITLE
Resizing window below minWidth doesn't prevent dragging and resizing

### ISSUE THREAD

**Issue by graemechapman** [troolee/gridstack.js#593]
When gridstack is initialised below the minWidth value, the grid items have classes `ui-draggable-disabled ui-resizable-disabled` and cannot be dragged or resized. If the window is resized to above the min width, these classes are removed and the drag and resize functionality is restored. 

But, when the window is resized from a larger size to below the minWidth, these classes are not re-applied, and so resizing and dragging is not prevented. Although dragging has no visible effect, changes are still made to the attributes, which  can be seen in dev tools or by enlarging the window, and the change event is triggered. 

This issue can be replicated by resizing the browser window on the demo page http://troolee.github.io/gridstack.js/

**Comment by radiolips** [comment]
@graemechapman This is an awesome bug. brb, got some code to examine.

**Comment by radiolips** [comment]
@graemechapman Looks like this was something I broke some time ago. I've run a test with the change and it works for me. Check out the `develop` branch and let me know if you're still seeing a problem.

**Comment by graemechapman** [comment]
@radiolips thanks, looks good to me!
