### ISSUE TITLE
v0.3.0

### ISSUE THREAD

**Issue by jpotth** [troolee/gridstack.js#594]
I'm assuming some of the issues in ^0.2.0 have been fixed in the latest version, specifically dragging and dropping between grids. As of now, 0.3.0 is only in development? When can we expect this to be officially released?

**Comment by dmitriyzhuk** [comment]
Really looking forward to it. waiting for that "moving between grids" feature)

**Comment by tipa** [comment]
*push*

**Comment by radiolips** [comment]
@jpotth @dmitriyzhuk @tipa Thank you all so much for the ask and push! We've been working on a plan, which will certainly include locking down `v.0.3.0` and scheduling `v.1.0.0`. I'll do my best to get on the same page with @troolee today, but if I'm unable to get in touch with him, I still plan on sharing these dates *today*. Start your timers - I'm giving myself the next 13 hours and 26 minutes to prepare something to share.

**Comment by radiolips** [comment]
I'm going to write up a longer message in a blog post tomorrow, but here's the plan:
`v.0.3.0` is going to go live tomorrow, April 21.
`v.1.0.0` is going to go into the `develop` branch on April 28. We're going to run it on the develop branch for a bit to make sure that there are no major bugs. 1.0 will have bugfixes from 0.3, will remove jQuery and jQueryUI dependencies, and will have at least one non-jqui draggable library working with `gridstack`.
