### ISSUE TITLE
How to detect whether User  resize on widget  width or height or cross section. 

### ISSUE THREAD

**Issue by zohokumaresan** [troolee/gridstack.js#597]
I have a requirement. Initially, All widgets are set to full height with respect to widget content height.
case 1.
when the user resizes his widget (resizes more height but widget has no content ) is shrinks to default.
case 2.
If the widget has more content but he can wish to shrink height as his desires.
case 3.
if the user resizes width, the content like the chart , table data is aligned with grid width.

I have done case 1, case 3. To do the case 2  in need to detect whether the user resizes widget on width or height. Thanks

**Comment by radiolips** [comment]
@zohokumaresan By comparing the width and height prior to resize with the width and height post-resize, you're able to determine this. I'm closing this ticket because it's not functionality for us to add to the library, but if you'd like to post a jsfiddle I can try to offer some help.
