### ISSUE TITLE
Grid maximum row & column

### ISSUE THREAD

**Issue by aureo91** [troolee/gridstack.js#606]
Hello,
I'am trying GridStack for a project, but I didn't find a way to locked the grid with a number of row and column. For exemple, I need a grid with 4 rows and 3 column (so 12 possible items of size 1).
The problem when I moved an  item below the item pos {4,1} (row,col), it creates new line where the item moves...
Thanks for your help,
Aureo.

**Comment by troolee** [comment]
Please check docs. You can setup grid with and height https://github.com/troolee/gridstack.js/tree/master/doc#options

**Comment by VladasC** [comment]
Same here. I create a grid of one single row, using "height" option (I tried data-gs-height="1" too). But it ignores it and still places widgets onto second row if doesn't fit (creates a second row). Thanks.

**Comment by Antimated** [comment]
Same issue here when I set my column width it doesn't work (properly)
