### ISSUE TITLE
Reload Gridstack with different widgets.

### ISSUE THREAD

**Issue by ArtisanTinkerer** [troolee/gridstack.js#609]
Hi,

I am trying to reload my Gridstack with a different set of components.

I am using Gridstack to create a dashboard application. I have a navigation sidebar which is used to navigate between the dashboards.

How should I load a new set of widgets (new dashboard)?

Destroy the Gridstack? or remove all the widgets?

I am using Vue.js to load/sync the widgets (via AJAX).

Details are here:

[http://stackoverflow.com/questions/42575346/gridstack-how-to-load-new-grid](url)

**Comment by JorgenSolli** [comment]
Might not be the best solution, but what I did was iterating through all the gridstack elements, putting the values in an array, and then storing this in my DB for safe keeping :)

`
var layout = {
	x: 0,
	y: 0,
	width: 5,
	height: 5
};
$('.grid-stack').children('.grid-stack-item').each(function (key, value) {
    if (layout[key]) {
        $(this)
    	    .attr('data-gs-x', layout[key].x)
    	    .attr('data-gs-y', layout[key].y)
    	    .attr('data-gs-width', layout[key].width)
    	    .attr('data-gs-height', layout[key].height)
	}
});`

Hopefully this helps.

**Comment by troolee** [comment]
Please check this example http://troolee.github.io/gridstack.js/demo/serialization.html

**Comment by ArtisanTinkerer** [comment]
Updated my original post, so that the link works. You can see the detail in there.

Looks like you do it like this;

```

this.loadGrid = function () {
                    this.grid.removeAll();
                    var items = GridStackUI.Utils.sort(this.serializedData);
                    _.each(items, function (node) {
                        this.grid.addWidget($('<div><div class="grid-stack-item-content" /><div/>'),
                            node.x, node.y, node.width, node.height);
                    }, this);
                    return false;
                }.bind(this);


```

I will try doing it like that.

Mick

**Comment by dshastry** [comment]
Struggling with this as well. @ArtisanTinkerer, would love your help to figure this out.

I have my data object set as such:

gridStack:{
originalLayout:[],
currentLayout:[],
hasChanged:null
}

The originalLayout is pulled in via ajax on mounted. Currentlayout is the array that i'm storing data in so i can save to db via a save method.

I have a <grid-item> component that goes into the main grid via a slot so i'm not sure how to use the add widget method to pass in slot data. It seems to be drawing fine on initial load and as long as items don't get added or removed. If I add an item I'm confused on how to go about getting gridstack to "see" it. I push into the currentLayout array via click event. My thought is to destroy gridstack and reload it but i'm not really sure how to do it.

I can destroy via jQuery(gridID).data('gridstack').removeAll(), but can't get it to reload with jQuery(gridID).gridstack(this.gridoptions).

Haven't found too much about Vue + Gridstack, so any help would be appreciated!

**Comment by dshastry** [comment]
Forgot to mention, I have an array of objects in those layout arrays that look like this:

{height: 1, positionx: 2, positiony: 0, width: 5}

and it's bound like this:
<cr-grid :data="gridStack">
		<cr-griditem  v-for="(item,index) in gridStack.originalLayout" :width="item.width" :height="item.height" :positionx="item.positionx" :positiony="item.positiony" :key="index">

(cr-grid is my custom Vue component)
