### ISSUE TITLE
Undefined '_' error when trying to build on asp.net

### ISSUE THREAD

**Issue by mattmanp** [troolee/gridstack.js#61]
It throws an error in:
    if (typeof define === 'function' && define.amd) {
        define(['jquery', 'underscore'], factory);
    }
    else {
        factory(jQuery, _);
    }
It always throws an exception on "factory(jQuery, _);" because it says '_' is undefined.
If I am doing something wrong, please let me know!

**Comment by ascendantofrain** [comment]
You need to have underscore loaded before the gridstack.js file.
 
I had the same issue myself and thats how I fixed it.

**Comment by troolee** [comment]
Hi,

gridstack depends on underscore.js so you need to load it first.
