### ISSUE TITLE
Hook in to droppable options

### ISSUE THREAD

**Issue by frankadrian** [troolee/gridstack.js#611]
Hey, thanks for this great library!

Is it possible to add my own configuration to the droppable plugin? I would like to specify my own callback to the `drop` options for example to handle some transformations to my data model. (Im using Angular) I saw in 3.0 there is a possibility to exchange the dnd library used, does this also provide custom callbacks?

Kind Regards Frank

**Comment by radiolips** [comment]
Hey Frank! Are you just looking to pass in certain options, or are you also trying to use a different plugin? There's options for both, but let me know and I will do my best to assist you.

**Comment by frankadrian** [comment]
Hey, im looking to pass in my own callbacks for `over` and `drop`! Really appreciate your help!

**Comment by radiolips** [comment]
@frankadrian I think we could consider triggering events that you could hook into. I'll keep you posted.

**Comment by radiolips** [comment]
@frankadrian Now that `added` is emitted when a widget is moved from one grid to another, is your problem solved?

**Comment by radiolips** [comment]
Closing because the enhancement added hopefully voids this request. Please reopen if I'm incorrect. Thanks!
