### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by alissondiel** [troolee/gridstack.js#615]
It's GridStack receiving updates? the version 0.3.0 releases 6 months ago

**Comment by jgrenat** [comment]
Wondering the same here, is this project still maintained?

**Comment by ZoolWay** [comment]
0.3.0? Latest according to NPM or GitHub releases is 0.2.6 I think.

**Comment by radiolips** [comment]
Hey all! Good questions here.

We have definitely faltered in our support for gridstack. @troolee and I plan to speak soon about the future of gridstack. We will keep everyone informed!

Stay tuned.

**Comment by alissondiel** [comment]
Thank you very much for giving us an answer!
We are all waiting for new news, 
This plugin is very useful for various web applications.

**Comment by tipa** [comment]
Any updates to this? I'd really like to use the grid-to-grid-dragging, may it be possible to publish the current dev status 0.3.0 as new update on npm?

**Comment by radiolips** [comment]
As I mentioned in the other ticket, we'll flag `v0.3.0` for release tomorrow!
