### ISSUE TITLE
gridstack horizontal spacing between dynamically loaded pivotwidgets is too high

### ISSUE THREAD

**Issue by Sreelakshmigc** [troolee/gridstack.js#616]
I am using pivottable interface to plot the widgets and have used gridstack to place them in grids. I am using grid-stack-item, ui-draggable, ui-resizable classes. When I try to resize the widget, the horizontal spacing between the widget is very large :

![gridstackexample](https://cloud.githubusercontent.com/assets/6168602/24030986/e928d722-0b05-11e7-8137-a8c3deef6457.png)

but I see that data-gs-x, data-gs-y, data-gs-width and data-gs-height are getting incremented by 1 when I drag or resize the widgets.

Please provide me a solution to decrease this horizontal spacing between the items.

I want it to look like the gridstack demo grids https://troolee.github.io/gridstack.js/

**Comment by Mickel97** [comment]
Hello Sreelakshmigc!

what i did do was to add this to the gridstack.css

.grid-stack .grid-stack-item .grid-stack-item-content,
.grid-stack .grid-stack-item .placeholder-content {
    left: 2px;
    right: 2px;
    bottom: -4px;
    top: -6px;
}

you can choose the spacement you want by changing the px, that was the spacement that i wanted.
i hope it helped you

**Comment by radiolips** [comment]
@Sreelakshmigc I don't understand why you're seeing a gutter that large. It looks like you have two touching to the right?

After re-reading, I think I understand what you're saying. You are moving one space, and it's jumping that far. Here's why: gridstack assumes 12 columns. It's taking your space and dividing it by 12. By modifying the CSS and passing in an option, you can make it fewer columns. Let me know if this doesn't help.

**Comment by Sreelakshmigc** [comment]
Hi @radiolips Thank you for your response. Can you please elaborate on how this can be done ? I am loading gridstack.min.css from the cdnjs. I am not able to find exactly which classes to be used in my local css file to overwrite the default values. Or do I need to save the gridstack.min.css file in my code and make changes there. Thanks again in advance. Hoping to get a quick response.
