### ISSUE TITLE
Knockout Component Two Way Binding Update Help

### ISSUE THREAD

**Issue by ascendantofrain** [troolee/gridstack.js#62]
Ive got my dashboard application wired up using the knockout component code snippet; however, when I drag or resize a widget in the grid, the viewmodel is not being notified of the updated values for each tile.  Any thoughts and help would be greatly appreciate.

**Component**

    (function() {
    'use strict';

    ko.components.register('dashboards-tiles', {
        viewModel: {
            createViewModel: function(controller, componentInfo) {
                var ViewModel = function(controller, componentInfo) {
                    var grid = null,
                        gridstack = $('.grid-stack'),
                        gridstackWidth = gridstack.width(),
                        widgetHeight = (gridstackWidth / 12) - 5;

                    this.widgets = controller.widgets;

                    this.afterAddWidget = function(items) {
                        _.each(items, function(item) {
                            item = $(item);

                            if (item.data('_gridstack_node') || item[0].nodeType !== 1) {
                                return;
                            }

                            if (grid == null) {
                                grid = $(componentInfo.element).find('.grid-stack').gridstack({
                                    auto: false,
                                    animate: true,
                                    always_show_resize_hande: true,
                                    cell_height: widgetHeight,
                                    handle: '.editing-options .handle',
                                    vertical_margin: 10
                                }).data('gridstack');
                            }

                            grid.add_widget(item);
                            ko.utils.domNodeDisposal.addDisposeCallback(item[0], function() {
                                grid.remove_widget(item);
                            });
                        }, this);
                    };

                    $(componentInfo.element).find('.grid-stack').on('resizestop', function(event, ui) {
                        setTimeout(function() { // necessary as resizestop fires slightly too early
                            _.each(Highcharts.charts, function(chart) {
                                if (chart) {
                                    chart.reflow();
                                }
                            });
                        }, 10);

                        // TODO: update viewmodel rect values after resizestop
                    });

                    $(componentInfo.element).find('.grid-stack').on('dragstop', function(event, ui) {
                        // TODO: update viewmodel rect values after dragstop
                    });
                };

                return new ViewModel(controller, componentInfo);
            }
        },
        template:
        [
            '<div class="grid-stack" data-bind="foreach: {data: widgets, afterRender: afterAddWidget}">' +
                '<div class="grid-stack-item" data-bind="attr: { \'data-gs-x\': x, \'data-gs-y\': y, \'data-gs-width\': width, \'data-gs-height\': height, \'data-gs-min-height\': rect.minHeight, \'data-gs-max-height\': rect.maxHeight, \'data-gs-min-width\': rect.minWidth, \'data-gs-max-width\': rect.maxWidth }">' +
                    '<div class="grid-stack-item-content">' +
                        '<h3>' +
                            '<span data-bind="text: title"></span>' +
                            '<span class="link float--right" data-bind="click: $root.removeTile">x</span>' +
                        '</h3>' +
                        '<img src="Content/images/loading.gif" data-bind="visible: isLoading()" class="loading" />' +
                        '' +
                        '<div class="tile-options">' +
                            '<div class="row">' +
                                '<label>Title <input type="text" class="text-input" data-bind="value: title" /></label>' +
                            '</div>' +
                            '<div class="row">' +
                                '<label>View <select data-bind="options: $root.views, optionsText: \'ViewName\', optionsCaption: \'Choose a view\', value: selectedView" class="text-input"></select>' +
                                '</label>' +
                            '</div>' +
                            '<div class="row">' +
                                '<label>Table/Chart <select class="text-input" data-bind="options: (selectedView() || {}).Charts, optionsText: \'ChartName\', value: selectedChart"></select>' +
                                '</label>' +
                            '</div>' +
                            '<div class="row">' +
                                '<button type="button" class="btn btn--small" data-bind="click: $root.saveTile">Save Tile</button> or <span class="link" data-bind="click: $root.cancelTile">Cancel</span>' +
                            '</div>' +
                        '</div>' +
                        '' +
                        '<div data-bind="chart: chart" class="fill"></div>' +
                        '<div class="editing-options">' +
                            '<span class="handle"><i class="icon icon-drag"></i> Drag to Move </span>' +
                            '<span data-bind="click: $root.editTile, visible: !editMode()" class="link">Edit </span>' +
                        '</div>' +
                    '</div>' +
                '</div>' +
            '</div>'
        ].join('\n')
    });
    })();

**View Model**

    var pfp = pfp || {};
    pfp.models = pfp.models || {};
    pfp.models.dashboards = pfp.models.dashboards || {};

      (function() {
    'use strict';

    this.sizes = {
        small: { width: 1, height: 1 },
        medium: { width: 2, height: 2 },
        large: { width: 3, height: 3 }
    };

    this.Dashboard = function(d) {
        var self = this,
            defaults = {id: 0, name: '', tiles: []},
            config = _.extend(defaults, d);

    this.Tile = function(t) {
        var self = this,
            sz = pfp.models.dashboards.sizes;

        t = t || {};

        self.title = ko.observable(t.title);
        self.size = ko.observable(t.size);
        self.viewId = ko.observable(t.viewId);
        self.chartId = ko.observable(t.chartId);
        self.isWalk = t.isWalk;
        self.showChart = ko.observable(true); //for custom binding
        self.chart = ko.observable();
        self.selectedView = ko.observable();
        self.selectedChart = ko.observable();
        self.editMode = ko.observable(false);
        self.isLoading = ko.observable(false);

        self.x = ko.observable(t.column);
        self.y = ko.observable(t.row);
        self.width = ko.observable(t.width === 0 ? 2 : t.width);
        self.height = ko.observable(t.height === 0 ? 3 : t.height);

        self.rect = {
            minWidth: 4,
            minHeight: 3,
            maxWidth: 12,
            maxHeight: 6
        };

        self.clearChart = function() {
            pfp.core.charts.clearChart(self);
        };
    };
    }).call(pfp.models.dashboards);

**Markup**

    <dashboards-tiles params="widgets: tiles, nextRow: nextAvailableRor"></dashboards-tiles>

**Comment by crashnick16** [comment]
I noticed this issue too.

Since the widgets are bonded in a for each with the attribute binding knockout will not know about the move events as these are only triggering a jquery change event.

**Comment by ascendantofrain** [comment]
I actually came across a solution hut it's not exactly native knockout but
it works. I can post later.

**Comment by ascendantofrain** [comment]
I basically had to manually serialize the widgets and then send those values back to the viewmodel.

                            _.each(self.widgets(), function (tile) {
                                var id = tile.htmlId();
                                if (id in updatedTiles) {
                                    tile.rect.x = updatedTiles[id].x;
                                    tile.rect.y = updatedTiles[id].y;
                                    tile.rect.width = updatedTiles[id].width;
                                    tile.rect.height = updatedTiles[id].height;
                                }
                            });
