### ISSUE TITLE
gridstack.jQueryUI.js not included in npm module?

### ISSUE THREAD

**Issue by Tinoooo** [troolee/gridstack.js#624]
Hi there,

I cant find the file gridstack.jQueryUI.js after installing gridstack via npm. Any reason, the file is not included?

**Comment by frankadrian** [comment]
That file is only available on the dev version. In v0.2.6 it does not exists yet! :)

**Comment by Tinoooo** [comment]
Thank you @frankadrian . Any idea when it will find its way in v0.2.7? I would really like to use the dragging feature, while using the npm package.

**Comment by frankadrian** [comment]
Not sure @Tinoooo, sorry!

**Comment by Tinoooo** [comment]
@frankadrian Thank you anyway!
