### ISSUE TITLE
How to disable grid-stack, set limit grid-item in grid-stack?

### ISSUE THREAD

**Issue by tanobi92** [troolee/gridstack.js#627]
- I want to fix height, width of grid-stack (not grid-item), grid-stack not resize.
- And no move/resize grid-item go out grid-stack.
- Set limit grid-item in grid-stack.
Thank you!

**Comment by radiolips** [comment]
@tanobi92 You can set a `height` when you initialize the grid. The remaining things you'd like to do will all need to be custom Javascript that you write and are not features of the library directly.

**Comment by tanobi92** [comment]
Thank @radiolips i was worked :).
