### ISSUE TITLE
Setting min-height for gridstack container makes the grid stack item not resizable

### ISSUE THREAD

**Issue by vbinithyanandamv** [troolee/gridstack.js#628]
I have tried setting the min-height for my grid container. Once i set up a min-height, i can't able to shrink/resize the grid stack item properly. Can be reproduced simply in all demo examples by giving a grid-stack min-height.

**Comment by radiolips** [comment]
@vbinithyanandamv I'm surprised this is the case. Could you please put together a jsfiddle to look at?

**Comment by vbinithyanandamv** [comment]
Yes sure.Let me add a fiddle.

**Comment by vbinithyanandamv** [comment]
Hi i have recreated the fiddle here

https://jsfiddle.net/divakarvenu/5ux1y3dr/2/

 but there seems to be a problem with resizable and draggable in this any idea why? I have checked out the resources all seems fine. I have gone through all other fiddles too, none seems to be having resizable. Any thoughts?

**Comment by radiolips** [comment]
Interesting! Thanks, I'll look into it.

**Comment by radiolips** [comment]
Hey @vbinithyanandamv ! I believe I've fixed the issue with the latest `develop` commit. Could you pull in the latest code and test it? It was a very little thing but gave me hours of grief. Let me know if it's fixed now, please! And, please, if you find any more issues, make sure to log them!

Thanks,
[dylan](https://dylandreams.com)

**Comment by vbinithyanandamv** [comment]
Cool sure :)
