### ISSUE TITLE
Different grid-stack-item width css for same data-gs-width

### ISSUE THREAD

**Issue by chdeshpc** [troolee/gridstack.js#631]
Hi @troolee ,

I am using the demo example with gridstack.js. But one of my requirements as below:
I want to create 2 columns using width:2 in options with cells in column1 should have width:60%
and cells in column2 should have width:40%.
We have few more requirements like:
Two_Column_60_40, Three_Column_30_40_30 

Below is my JSON:
 var widgets = [{ x: 0, y: 0, width: 1, height: 0, name: 'Item1' },
                         { x: 0, y: 1, width: 1, height: 1, name: 'Item3' }
                         { x: 2, y: 0, width: 2, height: 1, name: 'Item2' } ]
In the above JSON,I would want to see 'Item1' with width:60% and 'Item2' with width:40%.

Currently what is happening with .grid-stack-item[data-gs-width="1"]  { width: 50% !important;} this css is that, both 'Item1', 'Item2' are occupying width:50%.
How can I dynamically apply css classes to this based on some conditions?

I tried using column:3 and made it look like columns2. But with this, it drops the widget wherever I leave the mouse. I would need it to be dropped in their respective columns only and not just anywhere.

Can you please help me?

**Comment by radiolips** [comment]
Hey, @chdeshpc ! I can help you out.

Gridstack is based on the common bootstrap 12-column system. Each column is 1/12 of the width, so a widget of width 3 will have a width of 25%. Unfortunately, you cannot create columns of different widths - they always need to be evenly distributed.

Could you explain what you're trying to accomplish? There may be another way to solve your problem, but if you do need two columns of different widths, gridstack might not work perfectly. You may also be able to use two gridstacks, each with one column - this may solve your problem.

**Comment by chdeshpc** [comment]
Hey radiolips,

I figured out a way to do this. I am creating different css classes for every width I need and assigning it based on the condition.

Thank you.

**Comment by radiolips** [comment]
Glad you could get it figured out!
