### ISSUE TITLE
How to Make grid stack item Header Fixed

### ISSUE THREAD

**Issue by yellareddy-allcloud** [troolee/gridstack.js#637]
Hello Developers, I designed my dashboards using gridstack plugin for widget layout. In my widget i am unable to fix my Header.If i am scrolling down automatically Header also moving.

**Comment by radiolips** [comment]
This isn't something handled by gridstack, but is something that you should be able to do yourself. If you provide a jsfiddle I can try to help out.

**Comment by yellareddy-allcloud** [comment]
hi sir [radiolips], thank you for you reply, i sorted out my problem with json data, actually this is not the issue of grid stack item.

**Comment by PokeRwOw** [comment]
Hey @radiolips, I restart this topic because i'm interested to have a fixed header in widgets. How do you think achieve a simple header fixed ? I tried some things but it was unsuccessful (css position fixed....)

**Comment by radiolips** [comment]
@PokeRwOw I don't understand the question. What exactly are you trying to do, and how does gridstack impact what you're trying to do?

**Comment by PokeRwOw** [comment]
Sorry, I will reformulate. So I just want to add a fixed header in all of my widgets. 
Firstly I tried to add a fixed header between the class `grid-stack-item` and `grid-stack-item-content` but it failed, gridstack didn't recognize the widget anymore (can't resize or move). 
Next I tried to add a fixed header in the `grid-stack-item-content` with css property `position: fixed` and `width: 100%`, but I got unexpected result with gridstack.

Hope you understand what i'm saying now :)

**Comment by radiolips** [comment]
Could you put together a jsfiddle? I think we'll be able to figure this out but it's hard without actually seeing it.

**Comment by PokeRwOw** [comment]
Here we are : https://jsfiddle.net/Lqv19pw7/6/
As you can see I fixed every headers of widgets, but now, the header don't take 100% of the width. If I add `width: 100%` it will take more than the widget.
So, I just want the header fixed at the top of her widget, and when I'm scrolling down the header stop moving with.

**Comment by radiolips** [comment]
@PokeRwOw That's happening because the content section needs a specified height. Add `.panel-body: { height: 200px; overflow: scroll; }` and you'll see it working the way you want. The tricky part is that the `panel-body` section needs a height of the height of the widget minus the height of the panel.
