### ISSUE TITLE
Set custom id for nodes

### ISSUE THREAD

**Issue by weinhorn** [troolee/gridstack.js#64]
Hi Guys!
How can I set custom ID for each element? I want to download all the items from my database with ID. After sorting, I want to save the new positions in the DB. So I can save the positions, I need the IDs.
Sorry for my English, I'm German!

**Comment by ascendantofrain** [comment]
Are you using any kind of view model or model between the front-end and the server side code??

**Comment by weinhorn** [comment]
Thanks for the feedback!
Yes, I am planning to get the data from ASP.net with SQL database and provide a JSON object to the client. This JSON object containing all the parameters, including the ID it should contain.

**Comment by ascendantofrain** [comment]
How are you parsing through the JSON to display the gridstack widgets??

**Comment by weinhorn** [comment]
With JavaScriptSerializer i create the object. On the client I get the object with $ .getJSON.

**Comment by ascendantofrain** [comment]
Couldnt you just make the ID from the database as part of the JSON object and render that with the gridstack component??

**Comment by weinhorn** [comment]
That's not a problem. But how can I serialize my IDs after sorting ? The plugin automatically assigns each element an id attribute with this " _id " . Thanks for your help! :)

**Comment by weinhorn** [comment]
What's with the modification that line in gridstack.js?
line 204:    node._id = ++id_seq;

**Comment by weinhorn** [comment]
It can be closed. 
I can serialize my id using this code.

$('.grid-stack-item.ui-draggable').each(function () {
              var $this = $(this);
              items.push({
                  id: $this.attr('id'),
                  x: $this.attr('data-gs-x'),
                  y: $this.attr('data-gs-y'),
                  w: $this.attr('data-gs-width'),
                  h: $this.attr('data-gs-height'),
                  content: $('.grid-stack-item-content', $this).html()
              });
          });

**Comment by troolee** [comment]
Hi,

The method `grid.add_widget` returns an DOM node so you can assign your custom `id` to its attribute during deserialization like:

```javascript
var el = grid.add_widget('<div />');
el.attr('data-custom-id', my_id);
```

**Comment by weinhorn** [comment]
Thanks!!
