### ISSUE TITLE
Understand this plugin

### ISSUE THREAD

**Issue by saurabhsbhatt** [troolee/gridstack.js#645]
Hi,

This is a great plugin and as mentioned before on "https://github.com/troolee/gridstack.js/issues/568" I need to understand this to then try to customize this according to my requirement. Is there any documentation available that I could refer? If not, can someone please guide me about the basics here and some introduction to the existing architecture and what file does what? I am referring to the bootstrap JS version.

As for my requirements, I want to be able to add grid sections by button (this is already present) and drag and drop from side panel to exact position amongst the list of grids. Then also would like the grid's to be editable by double clicking it OR by dragNdrop image on it. Also add text, links inside the grids while formatting it.

**Comment by radiolips** [comment]
@saurabhsbhatt If your questions are specifically about the plugin, please keep the conversation to #568 , where you'll be able to get the most assistance.

**Comment by saurabhsbhatt** [comment]
Actually I was asking in general as to what topics should I acquire the knowledge for to be able to make changes to this Gridstack plugin.

**Comment by radiolips** [comment]
https://github.com/troolee/gridstack.js/tree/develop/doc
