### ISSUE TITLE
disableResize doesn't seem to be working

### ISSUE THREAD

**Issue by JonathanBristow** [troolee/gridstack.js#646]
Hi,

I'm setting disableResize to be true in my options hash but it doesn't disable the resize functionality. 
I've also tried setting data-gs-no-resize on the grid items themselves.

Is this is a known bug or do I need to set another property?

Thanks

**Comment by radiolips** [comment]
@JonathanBristow Could you provide a jsfiddle, please? If you're seeing that, that's a bug.

**Comment by JonathanBristow** [comment]
False alarm 👍
