### ISSUE TITLE
Cannot float a dropdown menu over a widget

### ISSUE THREAD

**Issue by sophanox** [troolee/gridstack.js#649]
Hey there,

I have a dropdown menu in one of my widgets. When it's clicked, however, the menu doesn't appear over the widget, and so is clipped inside it. I've tried increasing the z-index of the menu, but this doesn't seem to work at all.

I've adapted someone else's codepen here: http://codepen.io/anon/pen/jmBozq. Here's an image from it: 

![image](https://cloud.githubusercontent.com/assets/19409202/25555421/4ac2b31e-2cde-11e7-94f5-bc56ff988789.png)

As you can see, if you click the dropdown menu, the menu doesn't appear over the widget at all.

Any ideas?

Thanks!

**Comment by radiolips** [comment]
Hey, @sophanox ! You might end up with some strange effects, but you're going to need to add `overflow: visible` to the gridstack item with the class `grid-stack-item-content` that contains your drop down. I tested this with your codepen and it works :) I'm closing this one out, but please reopen if you're still having an issue!

**Comment by damianofalcioni** [comment]
Hi,
the code work but it fail again if the drop down have more items and another box is below that one. In such a case the drop down is covered by the second box (I've used the same codepen to test it).

Any idea?
Thanks

**Comment by sophanox** [comment]
Hey radiolips,

Thanks a lot for your first reply and apologies for reopening this; however, I've just noticed that the menu won't hover over other widgets. I think this is what damianofalcioni is trying to get across too.

I've updated the codepen with your fix, but note the behaviour below:

![image](https://cloud.githubusercontent.com/assets/19409202/25875858/a071576c-3511-11e7-8e38-f12fad7b302e.png)

The updated codepen is: http://codepen.io/anon/pen/jmBozq

Any ideas again?

Cheers

**Comment by radiolips** [comment]
I'll take a look at this when I have a chance and provide an update.

**Comment by radiolips** [comment]
I've got an update/fix (idea). It works.

The problem is that the containing `grid-stack-item-content` has a `z-index` of `0!important`. If you only have one widget with the dropdown, simply make the grid-stack-item-content element like this:
```
<div class="grid-stack-item-content" style="z-index:1 !important">
```
If you have multiple widgets with the dropdowns, you'll need to tap into the Javascript for opening a dropdown - when a dropdown gets opened, you'd want to set z-index:1 on its parents grid-stack-item-content, and when it's closed, reset it back to 0.

**Comment by damianofalcioni** [comment]
Hi
I've tested the solution proposed for multiple widget with dropdowns and it works perfectly.
Thank you very much :D ,
Damiano

**Comment by sophanox** [comment]
It's working for me too. Only thing extra I had to do was to set overflow:hidden to any content in the widget that I didn't want to be displayed.

Thanks a lot radiolips!
