### ISSUE TITLE
Dragging widget to new row inconsistant

### ISSUE THREAD

**Issue by PhilipAnthonyMurray** [troolee/gridstack.js#65]
In your demo when you drag one of the bottom widgets straight down they are not droppable on a new row. For instance, drag box number 11 below its original position and you are not able to drop it on a newly created row. If you move one column to either side it will allow you to drop.

**Comment by PhilipAnthonyMurray** [comment]
With the standard implementation the above is accurate but if you add the data-gs-locked attribute the widgets have the behavior required.

**Comment by troolee** [comment]
Do you mean to move widget like this http://take.ms/DBsA6 ?

By default widgets go up until it's possible. You can disable this behaviour by enabling [`float`](https://github.com/troolee/gridstack.js#options) option.
