### ISSUE TITLE
$(...).gridstack is not a function TypeError: $(...).gridstack -- JQUERY:Gridstack version issue?

### ISSUE THREAD

**Issue by chdeshpc** [troolee/gridstack.js#652]
Hi @troolee ,@radiolips,

I am facing the same issue. In our product we are using jquery-3.0.0.min.js version. And I get the following error.
$(...).gridstack is not a function TypeError: $(...).gridstack is not a function.

Below is the order of my scripts:

<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.0/jquery-ui.js"></script>
<script src="../layoutScripts/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.5.0/lodash.min.js"></script>
<script src="../layoutScripts/gridstack.js"></script>
<script src="../layoutScripts/gridstack.jQueryUI.js"></script>

I need a fix for this ASAP.
Can you please help me?

Thank you.

**Comment by radiolips** [comment]
Do you have other scripts? You don't have jQuery listed.

**Comment by chdeshpc** [comment]
Hey @radiolips,

It actually worked. jquery-3.0.0.min.js and gristack works :).

I have another quick question. I have animate: true config in options.
In IE the drag-drop doesnt work properly. The widget stays wherever it is.  But everything works in Firefox and Chrome.
Do you mind guiding me here?

Thank you.

**Comment by radiolips** [comment]
This may be an issue with jquery or jquery-ui? Have you verified that your version of IE works with those?

**Comment by chdeshpc** [comment]
Yes.. I checked it. JQuery UI 1.12 supports IE11. I downloaded it and replaced jquery-ui.js file with this new code version. The drag-drop doesnt work.
What might be the issue?

**Comment by chdeshpc** [comment]
My Jquery version is 3.0.

**Comment by radiolips** [comment]
You should have no problem with IE11. Can you put together a jsfiddle and we can take a look?

**Comment by chdeshpc** [comment]
Hi @radiolips, @troolee  ,

Below is the JSFiddle. It is not 100% in working state. 
But definitely the drag-drop issue is reproducible. If you compare the behavior in Chrome and IE11, you can make out the difference. The behavior is not same as Chrome in IE11. 
Also, I am not getting the placeholder div here.

I will be waiting for any help from you.

https://jsfiddle.net/chdeshpc/a8djywrj/12/

**Note:** The item should be dragged from left-top corner when you get a 4-arrow pointer.

**Comment by chdeshpc** [comment]
Hi @radiolips, @troolee ,

I was able to fix the IE issue. There was an error from my side. 
This issue can be closed.

**Comment by radiolips** [comment]
Great, glad you were able to get it working!
