### ISSUE TITLE
Problem with Internet Explorer (widget with scroll)

### ISSUE THREAD

**Issue by dani80vdt** [troolee/gridstack.js#66]
Hello I've a problem with Internet Explorer.
When panel have got an internal scroll, I can't drop panel if I click on scroll
Thanks for all 
Daniele

**Comment by crashnick16** [comment]
Just tried this and looks like I have the same issue in IE...

**Comment by troolee** [comment]
Can you provide a sample?

**Comment by dani80vdt** [comment]
![dragproblem](https://cloud.githubusercontent.com/assets/5031586/6466401/a038b8c2-c1c7-11e4-87b1-194213cc918f.png)
If appear a scroll, I can't drop the widget (only in internet explorer)

**Comment by ascendantofrain** [comment]
If you are certain that the scroll bar is the cause of the issue then you could leverage the '.ui-draggable-dragging' class name and set the overflow: hidden; property to hide the scroll bar while dragging.

**Comment by troolee** [comment]
Ok. This is a known issue with jQuery UI http://stackoverflow.com/questions/8793236/using-jquery-ui-draggable-how-to-avoid-drag-when-using-scrollbar

to avoid this bug you can do like so:

```html
<div id="test" style="width: 200px; height: 100px; overflow: auto; 
        background: lightgoldenrodyellow">
    <div class="content">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
        Dolorem ea labore porro qui quibusdam voluptates. Atque 
        nulla odit placeat quidem recusandae repudiandae sed sint 
        soluta! Accusamus eaque est fugiat officiis?
    </div>
</div>
```
and
```javascript
$('#test').draggable({
    handle: '.content'
});
```

To override draggable settings please check out gridstack options.

**Comment by dani80vdt** [comment]
It works!!!! Thanks a lot
