### ISSUE TITLE
Gridstack requirements

### ISSUE THREAD

**Issue by Hardcorewithin** [troolee/gridstack.js#668]
Hi,
I am not raising an issue but just a clarification on the jQuery\jQuery-ui versions required by gridstack.
In the Requirements paragraph it says that the jQuery versions required are:
- jQuery (>= 3.1.0)
- jQuery UI (>= 1.12.0). Minimum required components: Core, Widget, Mouse, Draggable, Resizable

but the jQuery\jQuery-UI versions used in all of the examples [here](http://troolee.github.io/gridstack.js/demo/) are:
- jQuery 1.11.1
- jQuery-ui 1.11.0

So what are the minimum jQuery\jQuery-UI versions required?

Thanks and keep doing the good work!

**Comment by radiolips** [comment]
Earlier versions of both jQuery and jQuery UI will not break. We don't use advanced features, but we have verified that it works with the newer versions of both.

**Comment by radiolips** [comment]
I want to also add that we plan on removing the jQuery UI dependency in version 1, which will hopefully hit beta next month. You can read more about version 1 at 

[https://dylandreams.com/2017/04/26/gridstack-10-coming-soon/](https://dylandreams.com/2017/04/26/gridstack-10-coming-soon/).

There will be some additional changes, so be sure to subscribe to/follow the blog. I'll post another update when version 1 is more finalized.

Thanks for using gridstack.js!
