### ISSUE TITLE
How can I add gridstack widget by injecting html markup to view?

### ISSUE THREAD

**Issue by Ruchir-zealous** [troolee/gridstack.js#671]
I know there is ```addWidget``` method but here I want to add HTML markup to view and make it gridstack widget @troolee

**Comment by radiolips** [comment]
@Ruchir-zealous You can use the `makeWidget` to convert existing HTML to a gridstack widget.

https://github.com/troolee/gridstack.js/tree/develop/doc#makewidgetel
