### ISSUE TITLE
Feedback for new features

### ISSUE THREAD

**Issue by zhaoyoubing** [troolee/gridstack.js#68]
Hi, Thank you for your wonderful gridstack. I am currently using it for a user customizable webpage.

Several questions:
1. Can you add functions for resetting the layout without removing all the components.
I just want to use several default layouts for the widgets and switch between those layouts.
Removal will destroy all the components.
2. Do you think it is good to add a default title bar which can be used for a dragging handle ?
Currently I need to manually add the titlebars as handles.
3. Do you imagine to develop it into a full-featured Javascript-based window management system?

Thank you very much.

**Comment by troolee** [comment]
Hi,

Thank you for feedback.

1. I can do this.
2. Gridstack doesn't care about what your widgets are. You have to add all titles by yourself and setup `handle` option during gridstack initialization.
3. No. I'm not going to develop window management system based on gridstack. I don't see any reason for this. At least for now. The closest goal is to fix current bugs and to improve performance.

**Comment by zhaoyoubing** [comment]
Thank you very much for your reply.

I also suggest to add a "hide" or "minimize" function.
With the "hide" function, the re-layout without deletion from DOM can also be implemented.

Best Regards!

**Comment by troolee** [comment]
Please check `batch_update`/`commit` API methods. You can do:

```javascript
grid.batch_update();
// update widgets position/size
grid.commit();
```

P.S. I've created #89
