### ISSUE TITLE
addWidget creating widget always with max height (when auto-position is off).

### ISSUE THREAD

**Issue by alexiade** [troolee/gridstack.js#680]
I'm not very good at JS so I failed making a JSFiddle but I have really odd problem with trying to serialize/deseralize the gridstack setup. The code is the example with a custom service for storing the config in the database. It sort of works, except that the height of the widgets that I pass on load with addWidget is ignored and max height always appiled. The boxes on the screenshot are all height 4, they should be as the code on the right indicates 3, 2 and 3... They become right sized if I load their sizes in min/max positions but that makes them un-resizable and that's not what Id like... They snap to correct height when I even slightly drag them.

![screenshot_20170603_231110](https://cloud.githubusercontent.com/assets/1458504/26756730/03ed7498-48b2-11e7-8763-f2e0f676bd9a.png)

**Comment by radiolips** [comment]
I got an email notification from "Alexia Death," so I'm inclined to help ASAP.

What's the code you're using to add the widgets? Have you tried hardcoding the height to see if it works?

**Comment by alexiade** [comment]
How nice :) This is the code. The non-js bits in the middle are python. this lives in the view template of web2py. From JS prespective height is hardcoded... I can also paste the code that reaches the browser, if that' s more helpful.

```
function build_grid(data) {
                this.grid = $('.grid-stack').data('gridstack');
                this.grid.batchUpdate();
                var items = GridStackUI.Utils.sort(data);
                var saved_pos;
                this.grid.removeAll();
               {{i=0}}
                {{for switch in response._vars:}}
                saved_pos = {
                        x: 0,
                        y: {{=i}}{{i=i+4}},
                        width: 3,
                        height: 2,
                        id: '{{=response._vars[switch]['hardware'].identifier}}'
                   };
                 for(var i = 0;i < items.length; i++){
                   if(items[i].id=='{{=response._vars[switch]['hardware'].identifier}}'){
                      saved_pos = items[i];
                      break;
                   };
                 }
                 this.grid.addWidget($(`{{include "_partial/switch_control_card.html"}}`), saved_pos.x, saved_pos.y, saved_pos.width, saved_pos.height,
                                                                                    false, 2, 6, 2, 4, '{{=response._vars[switch]['hardware'].identifier}}');
                {{pass}}
                this.grid.batchUpdate();
                this.grid.commit();
                return false;
         }
```

**Comment by alexiade** [comment]
hardcoding has no effect...

![screenshot_20170604_124643](https://cloud.githubusercontent.com/assets/1458504/26760539/e8e64086-4923-11e7-8ce3-9e42e521d041.png)

**Comment by alexiade** [comment]
This partial fiddle contains most of it: https://jsfiddle.net/L6y28qzf/ I just failed to find a way to debug it. It probably contains some obvious mistake somewhere.

**Comment by alexiade** [comment]
Messing with the fiddle I figured out that this happens if the widget declares height:100% in it's style. then this anomaly appears :) Thanks. I think I've figured out what's up :)

**Comment by alexiade** [comment]
https://jsfiddle.net/L6y28qzf/6/  final fiddle :)

**Comment by radiolips** [comment]
Glad you got it working! Let me know if you need anything else.
