### ISSUE TITLE
Question: Does the grid have overlapping option ? 

### ISSUE THREAD

**Issue by ahmedfekry** [troolee/gridstack.js#683]
I want to know if it is possible to make the items to overlap each other ?

**Comment by radiolips** [comment]
The widgets cannot overlap, but if you only want overlapping widgets, you can likely achieve your goal using just jQueryUI or another dragging/resizing library.

**Comment by markarupert** [comment]
> I want to know if it is possible to make the items to overlap each other ?

@ahmedfekry Were you able to find a girdstack solution for overlapping? I am trying to do something similar. I have stack widgets and I want to dynamic ones around that could overlap.

**Comment by adumesny** [comment]
gridstack is designed explicitly to NOT overlap items so you will have to look elsewhere...

**Comment by markarupert** [comment]
I figured out a solution. I stacked 2 grids on top of each other and made sure the top background was transparent. Worked perfectly.

**Comment by adumesny** [comment]
hummm. that means you can't interact between layers (well you can drag between grids but one overlapping will win other than non overlap region) and have say a 3 stacked item. Anyway, glad you found something that worked for you! If you find lib useful, don't forget to contribute.

**Comment by markarupert** [comment]
Yes, that is exactly what I needed. I did not want to interact with the bottom layer. Thanks!

 

Mark A. Rupert

The Rupert Group, Inc – CEO

mark.rupert@rupertgroup.com

**Comment by adumesny** [comment]
make the bottom layer static grid option then - it will save on not setting drag&drop.
