### ISSUE TITLE
Resizing all widgets

### ISSUE THREAD

**Issue by billkim84** [troolee/gridstack.js#687]
Is there any way to resize all widgets on the grid??

**Comment by radiolips** [comment]
@billkim84 You can loop through each widget and call `resize` - https://github.com/troolee/gridstack.js/tree/develop/doc#resizeel-width-height

**Comment by billkim84** [comment]
Thanks for replay. I wonder is there any way user can do it not by programmatically

**Comment by profesDevelopment** [comment]
@billkim84 You mean something like selecting multiple (or all) widgets and resize all selected widgets?

**Comment by billkim84** [comment]
@profesDevelopment yes

**Comment by troolee** [comment]
@billkim84 No, there is no way to do this
