### ISSUE TITLE
Dragging into a grid stack from a sidebar

### ISSUE THREAD

**Issue by Petah** [troolee/gridstack.js#69]
Is there any way to drag an item into a grid stack from a sidebar?

**Comment by ascendantofrain** [comment]
Try using jquery ui droppable.

**Comment by Petah** [comment]
But can it use the placeholder in this case?

**Comment by troolee** [comment]
Hi,

gridstack doesn't have such functionality but I think I can implement it.

**Comment by dani80vdt** [comment]
Would be very useful :+1:

**Comment by AndreCrujo** [comment]
+1, this would definitely make me use it over gridster.

**Comment by ascendantofrain** [comment]
+1

**Comment by crashnick16** [comment]
+1

**Comment by jahy** [comment]
important feature, серьезно

**Comment by troolee** [comment]
Will be сделано самой первой in 0.2.4


//wbr Pavel Reznikov <pashka.reznikov@gmail.com>

**Comment by KrishnaPG** [comment]
I am not expert in jQuery or JS, but just thinking: if the `grid-stack-item-content` is made to hold an internal `jquery ui droppable` element it may just start working and accepting the drops (Not sure, but should be close to the solution).

Also, on a side note, came across this very nice drag -drop effects design, and just thought of sharing, for inspiration: http://tympanus.net/Development/DragDropInteractions/sidebar.html

**Comment by KrishnaPG** [comment]
I tried as below and am able to make drag-drop work within a widget - but dropping from outside/side-bar looks like need some expert.
````
	<div class="grid-stack-item"
			 data-gs-x={{x}} data-gs-y={{y}}
			 data-gs-width={{width}} data-gs-height={{height}}
			 data-panel-id={{_id}} data-content-id={{contentId}}>
	<div class="grid-stack-item-content panel panel-default">
	<div class="panel-body ">
		<div>
			<ul id ="droppable" class="ui-widget-header columnsContainer2" style="height:100%;">
				<li>item1 </li>
				<li>item2</li>
				<li>item3</li>
			</ul>
			<p>Drop here</p>
		</div>
	</div>
	</div>
	</div>
````
JS code
````
$("#droppable").sortable({
        revert: true,
        distance: 8,
        connectWith: $('.columnsContainer2'),
        receive: function (ev, ui) {
            console.log("received");
        }
    });
````

**Comment by mirata** [comment]
+1 for this. 
Awesome plugin by the way

**Comment by alangunning** [comment]
+1 important feature. Any update on this enhancement?

**Comment by piwi91** [comment]
+1

**Comment by getrupendra** [comment]
+1

**Comment by pySilver** [comment]
+1 thats would be nice to have this feature while building UI

**Comment by pofider** [comment]
+1 or at least a guidance

**Comment by albulushi** [comment]
+1

**Comment by Furburger** [comment]
+1 Would be an awesome feature

**Comment by troolee** [comment]
We're working on it. I'm closing the issue because we have another same issues #133 just to clean a mess in issues
