### ISSUE TITLE
staticGrid option no longer enough to disable drag/resize

### ISSUE THREAD

**Issue by ianformanek** [troolee/gridstack.js#699]
After upgrading from 0.2.5 to 0.3.0 we got a regression in the behavior of grids with isStatic: true as these became draggable/resizable.

Whereas in 0.2.5 (and also according to the [docs](https://github.com/troolee/gridstack.js/blob/develop/doc/README.md#options) ) this should be enough

```
$('.grid-stack').gridstack({
        staticGrid: true
});
```

It seems that in 0.3.0 it is now necessary to specify the options as
```
$('.grid-stack').gridstack({
        staticGrid: true,
        disableDrag: true,
        disableResize: true
});
```

Note that this is also a workaround for the problem in 0.3.0
(or alternatively the setStatic() function seems to do all of these)

**Comment by radiolips** [comment]
Thanks, @ianformanek . There's an issue posted more recently (apologies, I know I'm going through these in reverse order) that I've commented on. Thanks for letting us know - this will be resolved in version 1.0, and will be in the 1.0 dev branch soon.

**Comment by radiolips** [comment]
@ianformanek This has now been merged into the dev branch. Let me know if you still have any issues.

**Comment by ianformanek** [comment]
Great, thanks, will give it a try
