### ISSUE TITLE
Totally disable gridstack

### ISSUE THREAD

**Issue by Petah** [troolee/gridstack.js#70]
Is there a way to totally disable gridstack, so I can toggle it on and off with a button?

**Comment by troolee** [comment]
What do you expect from disabling gridstack?

**Comment by Petah** [comment]
Basically I want a switch to turn on and off edit mode. 

I have it working now by doing something like:

```
grid.resizable('#grid .grid-item', false/true);
grid.draggable('#grid .grid-item', false/true);
```

But was just wondering if that was the best way.

**Comment by troolee** [comment]
You're doing all right. But for more convention I've added `disable`/`enable` methods which are shortcuts for that you does.

**Comment by Petah** [comment]
Awesomesauce! :cookie:

**Comment by MrCF** [comment]
I'm trying to do the same but without luck.
I disable the dragging and resizing this way:
`grid = $('.grid-stack').data('gridstack');
grid.disable();`

This works fine as expected, but when I re-enable the grid in the following way:
`grid.enable();`

I can resize widgets but I cannot move them any more.
Any suggestion?
