### ISSUE TITLE
New widgets are added at the beginning with autoPosition = true

### ISSUE THREAD

**Issue by adamlytics** [troolee/gridstack.js#705]
When adding a new widget with autoPosition = true, it adds it at the very beginning of the items from a display standpoint, at x=0 and y=0.  This messes up the entire format of what has already been done.  I can fix this by looking at everything before I add a new item, however, I'd really like to be able to have an option that has it add items to the end so it does not mess up any current formatting and positioning.

**Comment by andelizondo** [comment]
I use it like this and works fine:

`$('.grid-stack').data('gridstack').addWidget($('<div><div class="grid-stack-item-content"></div></div>'), null, null, null, null, true);`

**Comment by radiolips** [comment]
@adamlytics There's an open issue about this. It's a bug that will be resolved for version 1. Sorry for the inconvenience.
