### ISSUE TITLE
TypeError: $(...).gridstack is not a function

### ISSUE THREAD

**Issue by aviralgarg0996** [troolee/gridstack.js#709]
This is my sequence of scripts>please suggest a solution as soon as possible.

<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.1/underscore-min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.5.0/lodash.min.js"></script>
<script src="../dist/gridstack.js"></script>
<script src="../dist/gridstack.min.js"></script>
 <link rel="stylesheet" href="../dist/gridstack.css"/>
<link rel="stylesheet" href="../dist/gridstack.min.css"/>

**Comment by vigor-vlad** [comment]
1. You include both "underscore" and "lodash". You should probably include only one of these libraries...
2. "gridstack.min.js" is a minified version of "gridstack.js". There is no need to include both of them, just select the one that you need.
3. make sure that the location "../dist/gridstack.js" is correct. The relative path is used here, and it depends on the url (unless the <base ...> is defined). For example, if the url is "http://test.com/foo/" the browser will try to download the file from "http://test.com/dist/gridstack.js", if the url is "http://test.com/foo/bar" the location will be "http://test.com/foo/dist/gridstack.js"
