### ISSUE TITLE
sort items in 1 column mode vertical

### ISSUE THREAD

**Issue by perea1** [troolee/gridstack.js#710]
Hi,

how can i make the sorting of items vertically (in 1 column . responsive mode)?

Example: vpos/hpos
box1 1/1-  box2 1/6 - box3 1/9
Box4 5/1 - box5 5/3 - box6 5/9
box7 9/1 - box8 9/6 - box9 9/9

Sort in 1 Column Mode:
box1
box5
box9
box5
box2
box8
box3
box6
box9

Thx

**Comment by radiolips** [comment]
Hey, @perea1 ! If I'm understanding you correctly, the way to achieve that is to manually reorder them when you get into one column mode. You can check for one column mode, or you can add a listener that will check for the same condition the one column mode does (`return (window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth) <=
            this.opts.minWidth;`)
