### ISSUE TITLE
What's your algorithm for auto layout? It seems very random

### ISSUE THREAD

**Issue by juminoz** [troolee/gridstack.js#712]
I was trying out the auto layout option and it seems completely random. Is it not best-fit? The first 2 pods I tried with both have with of 12 (100%), but the last 4 pods with width/height 4/3, 4/2, 4/1, 4/3 ended up on top. Then the rest of the page are all jumbled up. Is there an option to also honor the order of the elements?

I used version 0.3.0 when I ran the test. I was hoping the library that I wrote and use an open source version instead and this one is the closest to what I have. Another feature I would suggest is auto expanding pod based on the content when you write version 1.0 of this library. Otherwise, there will always be cases where the content doesn't fit.

Anyway, looking forward to the next release.

**Comment by radiolips** [comment]
@juminoz Thanks for logging this! There's actually another ticket that mentions this as a problem. It'll be fixed, I promise. It's certainly a weird thing.
