### ISSUE TITLE
'acceptWidgets: true' generates duplicate 'ui-resizable-handle' element and breaks resize.

### ISSUE THREAD

**Issue by andelizondo** [troolee/gridstack.js#718]
Hello, I've been trying to use the option **'acceptWidgets: true'** but as soon as I move a 'grid-stack-item' to another grid, the item **gets a second 'ui-resizable-handle' div element** that breaks the resizability of the item. After deleting the duplicated div, the item becomes resizeable again.

Reproducible on **two.html** demo.

Thanks.

**Comment by jeffbeagley** [comment]
When I delete the second one, the item becomes re-sizable, but it doesn't keep its new size and just reverts right back to what it was before

**Comment by jeffbeagley** [comment]
I wrote a function that is called via the change event.

`			$( "#grid-home > .grid-stack-item" ).each(function() {
					$( ".ui-resizable-handle", this).each(function(index) {

						if (index > 0) {
							$( this ).remove();
							
						}
						
					});			
				
			});`

**Comment by adumesny** [comment]
@jeffbeagley thanks for the heads up workaround!
would be great to get an actual fix submitted for review though.

**Comment by radiolips** [comment]
Fixed! Thanks to @adumesny and everyone who participated in getting the fix tested!

**Comment by adumesny** [comment]
fix in https://github.com/troolee/gridstack.js/pull/769
