### ISSUE TITLE
i use vue&&element-ui，how can I use gridstack.js

### ISSUE THREAD

**Issue by kindLee-alasikoo** [troolee/gridstack.js#722]
i had jquery already.
```
import jQueryUI from "jquery-ui"
import lodash from 'lodash'
`import` gridstack from 'gridstack'
```
```
created() {		
             $(function () {
            var options = {
            };
            $('.grid-stack').gridstack(options);
        });
        }
```
       
	```
alias: {
			'jquery-ui': path.resolve('./node_modules/jquery-ui/ui'),
			'vue$': 'vue/dist/vue.esm.js',
			'@': resolve('src')
		}``
```
```
new webpack.ProvidePlugin({
				$: "jquery",
				jQuery: "jquery",
				"windows.jQuery": "jquery"
			})
```
gridstack doesn't work ....what shoud i do?

**Comment by jeoy** [comment]
which version of gridstack.js do you use?

if it‘s higher than 0.2.6 (like 0.3.0),

you should include  ```gridstack.jQueryUI.js``` as well or just  include ```gridstack.all.js```.



ref:    https://github.com/troolee/gridstack.js :  Migrating to v0.3.0

**Comment by radiolips** [comment]
Thanks, @jeoy ! 

@kindLee-alasikoo if you're still having problems, I know that you can find a ticket or two (maybe closed) in here where this has been discussed. I'm closing this issue, but let me know if you are unable to find what needs to be done.
