### ISSUE TITLE
Logic for vertical (y-axis) positioning differs to horizontal 

### ISSUE THREAD

**Issue by kool-kat** [troolee/gridstack.js#731]
There are more creative possibilities available for positioning grid elements on the x-axis (horizontal) than on the y-axis.

The logic used for down/up row movement doesn't match that used with left/right grid element placement.

Vertical positioning appears to be restricted and dictated by the bottom/top positions of positioned grid pieces NOT by whether there is room for the piece to fit in the vertical space available.

So effectively a 12 grid is an across measure not the same in Y-positioning points.

**What I wanted to create:**

![5](https://user-images.githubusercontent.com/30038525/28740441-04ec6022-7448-11e7-8072-e1dc557ca9eb.png)

**What I ended up with** 
![image](https://user-images.githubusercontent.com/30038525/28740504-d9d94408-7448-11e7-9d8b-5b2ba6017f9d.png)

**Piece 4** couldn't be moved down to touch the top of piece 5. Which was my desired design.

Yes, I could add a spacer grid element to make it work but that seems silly. Would be great to have more flexibility in vertical spacing in a future revision. Such that it will drop into place **if/when space permits** using increments of **cellHeight** parameter, as Y-position points.

You will see in my coloured grid the outline as I tried to move object but although space available it would not lock into position as it did not consider the 'cellHeight' increment valid.

Thanks for considering this suggestion.

**Comment by adumesny** [comment]
@kool-kat try using float: true when creatign the grid (see official http://troolee.github.io/gridstack.js/demo/two.html)

**Comment by radiolips** [comment]
Thanks, @adumesny . That's right on both counts - `float: true` will enable 4 to touch 5, and version 1.0 will add gravity.

**Comment by kool-kat** [comment]
@adumesny Could have sworn I had tried that option too, but so long ago will have to go back to it. Thanks for suggestion though. To be honest I found the impact of some API options unclear, even when looking at example files. Maybe us users of Grid can help with writing docs?

**Comment by radiolips** [comment]
Yeah, I think the docs could use a rewrite.
