### ISSUE TITLE
Question: Can the widgets overlap each others while dragging ?

### ISSUE THREAD

**Issue by jeoy** [troolee/gridstack.js#734]
I know the widgets cannot overlap from this issue : https://github.com/troolee/gridstack.js/issues/683

but can they overlap while dragging (before mouse up)?

**Comment by radiolips** [comment]
@jeoy Thanks for the question - Unfortunately, no, they can't overlap while dragging. The way the core functionality of gridstack works, the space is taken when it's available. I believe you'd run into some strange interface issues if this was not the case, but, either way, it's not possible to overlap while dragging.
