### ISSUE TITLE
memory management on widgets change seems to build up

### ISSUE THREAD

**Issue by crashnick16** [troolee/gridstack.js#74]
I am trying to create a website that can support multiple gridstacks and change the widgets when moving from one gridstack to another. This seems to create a lot memory issues and by running the below test you will notice that the memory is building up continuously and is not released resulting in slow performance after some use. 

Any advice on why this is happening and if there is a way to fix it would be very much appreciated.

replace the script in your knockout example with the below:
  $(function () {
            var Controller = function (widgets) {
                this.widgets = ko.observableArray(widgets);
                
                this.widgets.subscribe(function(){
                     var grid = $('.grid-stack').data('gridstack');
						grid.remove_all();
                })
            };

            var widgets = [
                {x: 0, y: 0, width: 2, height: 2},
                {x: 2, y: 0, width: 4, height: 2},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 1, y: 2, width: 4, height: 2}
            ];
            
            var widgets2 = [
                {x: 1, y: 0, width: 2, height: 2},
                {x: 3, y: 0, width: 4, height: 2},
                {x: 4, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
                {x: 6, y: 0, width: 2, height: 4},
           
                {x: 6, y: 0, width: 2, height: 4}
            ];
	var test = new Controller(widgets)
            ko.applyBindings(test);
            var a = true
            setInterval(function () {
            if (a){
            	test.widgets(widgets2)
                a=false;
            }else {
            	test.widgets(widgets);
            	a = true;
            }
            	
            	}, 10);
            
        });

**Comment by troolee** [comment]
Hi,

Please check the latest version out. It should be fine now.
