### ISSUE TITLE
Persistence support?

### ISSUE THREAD

**Issue by justintoth** [troolee/gridstack.js#740]
Does this library allow persisting the state of the widgets, e.g. in a cookie? If so, is there an example of that somewhere? Moving the widgets around isn't very useful if it doesn't persist across page loads.

**Comment by tonywr71** [comment]
Repeating a reply I made elsewhere:

You should be able to use the "change" event to detect changes:

```
$('#grid-stack').on('change', (event, items) => { 
    var gridStackData = $("#grid-stack").data('gridstack');
    console.log(gridStackData);
});

```
The example for serializing is [here.](http://troolee.github.io/gridstack.js/demo/serialization.html)

It's save grid function looks at the node list. So my variation of this which returns json string data, which can then be stored in a cookie, is:

```
saveGrid(){
		this.serializedData = _.map($('.grid-stack > .grid-stack-item:visible'), function (el) {
			el = $(el);
			var node = el.data('_gridstack_node');
			return {
				x: node.x,
				y: node.y,
				width: node.width,
				height: node.height
			};
		}, this);
		return JSON.stringify(this.serializedData, null, '    '));
}
```

BUT be warned. I am investigating an issue at the moment where it appears to be returning the coordinates wrong for one of the items. If I can reproduce it in a plunker, I will be raising an issue shortly.

**Comment by radiolips** [comment]
I'm closing this issue, as it's been brought up before and will not be part of the `gridstack` library. It's very easy to persist data in a file, in a database, in application cache, or wherever else data could be stored.

You can use the serialization function, such as @tonywr71 provided (again, thanks!) and simply store it wherever you'd like.

@justintoth if you make a pass and are having problems proceeding, please post a link to a jsfiddle and I'll be happy to help assist you. Hopefully the above comment provides you with enough information to proceed.

**Comment by justintoth** [comment]
Yes I was able to get it working, thanks!
