### ISSUE TITLE
gsresizestop event never triggers

### ISSUE THREAD

**Issue by ingale88s** [troolee/gridstack.js#745]
I am trying to get height of updated div using following event but this event never triggers after resize stop.    

```
 $('.grid-stack').on('gsresizestop', function (event, elem) {
         var newHeight = $(elem).attr('data-gs-height');
     });
```

**Comment by ingale88s** [comment]
This is not a issue. I didn't realize that this event is added in v0.3.0.

**Comment by joemorcullo8** [comment]
Hi I'm having an issue regarding this gsresizestop.

#818
