### ISSUE TITLE
knockout / delete widgets

### ISSUE THREAD

**Issue by anddob** [troolee/gridstack.js#75]
Hello, sorry for this new issue, seems you are very busy at the moment - I tried to solve it myself without any result. I used your sample code to create a grid-stack knockout component. Works like expected, when calling  a viewModel-function for adding new items to the widgets array:
        this.addItem = function() {
        	this.widgets.push({x: 0, y: 0, width: 2, height: 2});
        }

But when I try to remove an item from the list like calling my viewModel's function
        this.deleteItem = function() {
        	this.widgets.pop();
        }

... it seems like knockout deletes the original grid-stack-item - so far so good - but I don't know why, the callback added via "addDisposeCallback" to remove the widget from gridstack is never called (that means that the widget is not removed from grid-stack).
Do you have any idea, what to do? If it would be helpful for you, I could send you my sample code (using Knockout 3.3 - I also tried with 3.2).

Thank you very much for any help!

**Comment by troolee** [comment]
Hi,

I've found the problem. Please check out the updated sample https://github.com/troolee/gridstack.js#use-with-knockoutjs

**Comment by anddob** [comment]
Seems to work!
The complete gridstack project including support = high quality
Thank you very much!
