### ISSUE TITLE
Gridstack slow rendering in Internet Explorer. 

### ISSUE THREAD

**Issue by kamran924** [troolee/gridstack.js#751]
First of all congratulations and thanks for the authors of GridStack plugin, its awesome!! 

I am using nested grids to make a form and I noticed quiet slow performance in IE ( I am using Ver. 11).

I have added the  [jsFiddle](http://jsfiddle.net/Kami924/4sqLx31f/7/). 

The page loads relatively fast in FireFox and Chrome as compared to IE.

**Comment by ZoolWay** [comment]
IMHO we should not put much effort in improving performance on absolutely outdated browsers. Even MS discontinued it. It works but for full performance go to Chrome, Firefox or Edge.

**Comment by radiolips** [comment]
@kamran924 In the upcoming version 1, there will be better performance when dragging widgets. _However_, we have some limitations. For now, the full widget, including its contents, is rendered when dragging. If you have many widgets or nests, that can put a strain on the browser. Even on a great laptop running Chrome, you'll likely experience slowness in those situations.

I'd recommend breaking up the form into more sections and only display some sections at one time. As much as I hate to say this, @ZoolWay is right - I'll work on overall efficiencies, but it's difficult to apply performance boosts to get IE's rendering up to snuff with the rest of the gang.
