### ISSUE TITLE
Need Callback function

### ISSUE THREAD

**Issue by jishanshaikh** [troolee/gridstack.js#753]
It will be great if we can have callback functions facilities after updating/resizing/adding new widget/deleting widget etc.

I am trying to get the latest height and width of widget after resizing it with update function but i cant get correct height and width unless i use setTimeout.

**Comment by tonywr71** [comment]
You should be able to use the "change" event to detect changes:
```
$('#grid-stack').on('change', (event, items) => { 
    var gridStackData = $("#grid-stack").data('gridstack');
    console.log(gridStackData);
});

```

The example for serializing is [here.](http://troolee.github.io/gridstack.js/demo/serialization.html)

It's save grid function looks at the node list. So my variation of this which returns json string data, which can then be stored in a cookie, is:
```
saveGrid(){
		this.serializedData = _.map($('.grid-stack > .grid-stack-item:visible'), function (el) {
			el = $(el);
			var node = el.data('_gridstack_node');
			return {
				x: node.x,
				y: node.y,
				width: node.width,
				height: node.height
			};
		}, this);
		return JSON.stringify(this.serializedData, null, '    '));
}

```

BUT be warned. I am investigating an issue at the moment where it appears to be returning the coordinates wrong for one of the items. If I can reproduce it in a plunker, I will be raising an issue shortly.

**Comment by radiolips** [comment]
Thanks, @tonywr71 ! I'm double-investigating.

@jishanshaikh If you want the coordinates of the particular widget you're changing, use `gsresizestop` rather than `resizestop` - `jqueryui` likes to steal our functions and report wrong (well, in our case wrong) coordinates.

**Comment by radiolips** [comment]
I assume that this question has been answered conclusively. @jishanshaikh Let me know if you're still having an issue.
