### ISSUE TITLE
Front Page issue

### ISSUE THREAD

**Issue by savannahchoy** [troolee/gridstack.js#758]
There's a Blog Page which is set up on the FrontPage when I click it to my portfolio. Anyone knows how to set it as a work page (my graphic work ) instead of the blog page?
![screen shot 2017-09-05 at 2 43 58 pm](https://user-images.githubusercontent.com/31672741/30084844-ef42d80e-9248-11e7-9ff0-e66b5568fd77.png)
please help :( Thanks everyone

Savannah

**Comment by radiolips** [comment]
Hey @savannahchoy - I'm not sure what you're asking. Could you clarify for me?

**Comment by radiolips** [comment]
I'm going to close this because I'm pretty sure it belongs in another repository. Feel free to reopen if I'm mistaken.
