### ISSUE TITLE
Dropout handler error after simple steps

### ISSUE THREAD

**Issue by creage** [troolee/gridstack.js#768]
1. Go to [Two grids demo](http://troolee.github.io/gridstack.js/demo/two.html)
2. Drag the **Drag me** box within its **green** container. 
3. Reposition any widget within any of two available grids.
4. Try to drag the **Drag me** box again

```
Cannot set property 'el' of undefined
```

For some reason the *dropout* event gets fired on the container, while it has nothing to do with it.

**Comment by adumesny** [comment]
good news is that it's fixed in the latest code (including my soon to be taken PR). I was able to repro in the link above, but no error in my local copy.

**Comment by radiolips** [comment]
Thanks @adumesny ! It's actually already merged. @creage I'm going to close this ticket, but if you pull the latest from the `develop` branch and you still have an issue, please reopen and let us know.
