### ISSUE TITLE
Knockout Component Issue

### ISSUE THREAD

**Issue by ascendantofrain** [troolee/gridstack.js#78]
Is it not possible to specify a template id instead of creating a js string for the template??  

It seems that if I use a component template id to reference an html dom element the addDisposeCallback for removing widgets doesn't work.  I have a very complicated UI being rendered by this component and turning that into a JS string is VERY tedious and hopefully unnecessary.

**Comment by troolee** [comment]
Hi,

Please check [this example](http://troolee.github.io/gridstack.js/demo/knockout2.html) out. The problem is because of space between the last closing tag of the widget and outer DOM node (`foreach` container). The workaround is to remove it. For now I don't know the better solution to fix this.
