### ISSUE TITLE
Elaborate on differences with gridster.js?

### ISSUE THREAD

**Issue by bbirand** [troolee/gridstack.js#79]
I am trying to decide on a grid library, and the last two contenders are gridstack and gridster. Out of these two, gridster clearly is the more popular one, with 4700+ stars, but it also hasn't been updated since September. On the other hand, this project is pretty active, and the author seems very responsive.

I think what would be a great boost would be to add a section to the documentation as to how this library is different (superior?) to gridster. It would certainly make things easier for people like me that are trying to decide between them. What do you think?

**Comment by troolee** [comment]
The main reason why I've started gridstack lib was bootstrap responsive layout support. gridstack doesn't care about widget width at all (widths, horizontal margins, etc). 

Another reason was 'dead' support of gridster.

**Comment by troolee** [comment]
... and, of course, kncockout.js support.

**Comment by bbirand** [comment]
That does make it a little clearer. Perhaps a quick paragraph on the top part of the homepage to this effect would help with your conversion. Also if you have any public projects that use it.

(I'm already sold, but I think these points will make it easier for others to adopt this library.)

**Comment by ishandutta2007** [comment]
Hey I have a couple quick questions before I can explore and compare the two further,
Firstly I need my grid contents to be collapsable panes. So if neither of these plugins provide me that out of the box, I may have to consider intergrating Bootstrap Accordion and also make grids auto resizable based on Accordion's behaviour, not sure which of the two integrates better ?
Secondly I need to know is does gridstack provide customizable drag handle as I can see in one of the gridster demos ?
