### ISSUE TITLE
Min/Max Restraints

### ISSUE THREAD

**Issue by ascendantofrain** [troolee/gridstack.js#80]
I really like the update for the widgets to respect the min and max widget sizes but they are still able to be resized outside of the boundary of the main container.  It's not a huge issue or anything but it is a minor visual nuisance.

![screenshot-2015-03-02-08 27 11](https://cloud.githubusercontent.com/assets/781671/6442038/b6e7d8cc-c0ba-11e4-86da-10f006de8982.png)

**Comment by troolee** [comment]
Please check new `draggable` option. It allows to override jQuery UI draggable setup (by default it uses `body`). You need to do something like:

```javascript
$('.grid-stack').gridstack({
    draggable: {
        appendTo: 'YOUR CONTAINER SELECTOR'
    }
});
```
