### ISSUE TITLE
Full SCSS File

### ISSUE THREAD

**Issue by ascendantofrain** [troolee/gridstack.js#82]
I have updated your base css file to an scss file that includes my for loop snippet for anybody who would prefer to use SCSS instead.  How is the best way to get you this file if you one day to decide to add it to the project??

**Comment by troolee** [comment]
Hi, it should be separate scss file inside the src directory. Go to https://github.com/troolee/gridstack.js/tree/master/src and click `+` http://monosnap.com/image/oCTrEzUQhm9O1UB9iUHZ4SxvvwPgPz

**Comment by ascendantofrain** [comment]
Thanks...I've added the file to that folder.  If you use it, cool, if not, that's okay.  =)

**Comment by troolee** [comment]
Hm.. I don't see any pull requests from you.

**Comment by ascendantofrain** [comment]
I think I've got it correctly sent this time.  I'm not used to contributing
to others' projects so this was new to me.

**Comment by troolee** [comment]
You did it for your repo. That's why I don't see it. You need to do this in my repo here https://github.com/troolee/gridstack.js/tree/master/src

**Comment by ascendantofrain** [comment]
How about now?  =)

**Comment by troolee** [comment]
Now it's fine. Thank you.
