### ISSUE TITLE
Updating seperate Elements

### ISSUE THREAD

**Issue by renebrain** [troolee/gridstack.js#84]
Hi,

is it somehow possible to update one element in the grid? what i am doing now is to remove the object i want to change and add the new one to the gridstack, but than my gridstack gets larger in height.  Is there a way to add edit element dynamically?

Thanks in advance ;)

**Comment by troolee** [comment]
Are you trying to change width/height of a widget or its content?

**Comment by renebrain** [comment]
I try to change the content. But i already have another idea to change the content without touching the gridstack itself. I think i just went in a wrong direction and tried to change the gridstack at a point where it is not needed.

**Comment by troolee** [comment]
gridstack doesn't care about the content of a widget. It's just an HTML DOM node for it. So to update the content you need to use jQuery for instance.
