### ISSUE TITLE
Getting all changed Elements in the Onchange event

### ISSUE THREAD

**Issue by renebrain** [troolee/gridstack.js#86]
Hi,

I am wondering if there ia a possibility to get all the elements that have changed(position or size) when the onchange event is called?

Or do I have to check it myself in my application?

Thank you ;)

**Comment by ascendantofrain** [comment]
This is how I handle change events within my knockout.js component.

    $(componentInfo.element).on('change', function (event, ui) {
        // do your stuff here
    });

**Comment by troolee** [comment]
If you bind to gridstack onchange the handler receives a list with changed items https://github.com/troolee/gridstack.js#onchangeitems

**Comment by renebrain** [comment]
So in this list will be only the changed items after a drag or resize event?

**Comment by troolee** [comment]
Right. All affected items.

**Comment by renebrain** [comment]
Awesome, that i will test tommorow...how can i access the items from the list can i just go over it with an $.each loop? I haven't checked how the properties look like, and i have no computer nearby to try it out.

**Comment by troolee** [comment]
It is an array of nodes. Each node is an object which contains `x`, `y`, `width`, `height`, `el` properties.
