### ISSUE TITLE
switch widget

### ISSUE THREAD

**Issue by lorenzopub** [troolee/gridstack.js#88]
hi troolee,

currently i'm using gridstack to build a dashboard. i will be interested to have an optional drag&drop functionnality  for the entire grid to be able to switch 2 widgets , each one taking the size and positionning of the other one like this :

initial state of the grid :
[1] [2] [..3..] [4]
[...5..] [6] [..7..]

i would like to switch [..3..] and  [6]

as a result of the drag and drop :+1: 

[1] [2] [..6..] [4]
[...5..] [3] [..7..]

cheers
lorenzo

**Comment by troolee** [comment]
Hi Lorenzo, I think I can do this.

**Comment by lorenzopub** [comment]
great !

**Comment by troolee** [comment]
I cannot promise it will be done right now, but it in 0.2.4 it will.

Right now I'm improving performance and stability of the library.

**Comment by lorenzopub** [comment]
no problem.

i'm thinking that with this optional functionnality for the drag & drop, the behavior of the widget resizing should be also a little bit different. 

the resizing of a widget should alterate the size of the widget close to it instead of moving it accordingly.

initial state of the grid :
[1] [2] [..3..] [4]
[...5..] [6] [..7..]

if i you would like to reduce widget [3] on the left & on the right,
grid should be in that state :
[1] [2..] [3] [..4]
[...5..] [6] [..7..]

**Comment by KrishnaPG** [comment]
+1 Switching positions would be a great feature (especially when the widgets are of different size and placed apart)

**Comment by radiolips** [comment]
#149 has more information and also covers this topic. Closing, but will leave 149 open.
