### ISSUE TITLE
checking empty spece on grid

### ISSUE THREAD

**Issue by kozilla** [troolee/gridstack.js#91]
Hi,

Is it any easy way to check if cell on greed is empty or occupied by grid element ?
For example if I have 

[    x=0  y=0  occupied  ][   x=4 y=0  empty  ][  x=5 y=0  empty  ][   occupied ]
[         occupied            ] [         occupied     ][        empty          ][   occupied ]
[         occupied            ] [         occupied     ][        empty          ][   occupied ]

how I can find out that 4,0 is empty  and  from 5-0 to 5-2 is also empty space ?

Thanks,

**Comment by troolee** [comment]
Hi,

I've added `is_area_empty` API method https://github.com/troolee/gridstack.js#is_area_emptyx-y-width-height
