### ISSUE TITLE
memory mamagement - gridstack memory release

### ISSUE THREAD

**Issue by kozilla** [troolee/gridstack.js#92]
Hi, 

I am having a issue with memory management (dupe of #74 ? ) . I am building grid dynamically and very often i have to destroy and rebuild whole grid (doing it by saving data to json and create new gridstack with new layout as shown in your example) how ever it looks like memory is not released . 

I am destroying gridstack by :

$(".grid-stack").draggable().draggable("destroy");
$(".grid-stack").removeData();

Could you advise please how correctly should I destroy whole instance of gridstack ( I mean undo $('.grid-stack').gridstack()  and release all memory taken by this action)

Thanks,

**Comment by troolee** [comment]
Please check the latest version. I've profiled with Google Chrome this sample http://troolee.github.io/gridstack.js/demo/serialization.html and didn't see any leaks now.
