### ISSUE TITLE
add_widget() change position of existing widgets

### ISSUE THREAD

**Issue by iorom** [troolee/gridstack.js#93]
I have noticed a strange behaviour, in my opinion.

I work with a grid with this options { float: true, height: 9, width: 6}. Initial, I have 14 completely locked widgets (locked, no-move, no-resize) on the full first row and full first column. The rest of the grid is empty.

I am adding manually widgets by clicking on a button:
```javascript
grid.add_widget('<div class="grid-stack-item" data-gs-x="1" data-gs-y="1" data-gs-width="1" data-gs-height="1" data-gs-max-width="1" data-gs-max-height="6">......</div>', 1, 1, 1, 1, true);
```

If I add a widget (y=1,x=1) and then move it (drag&drop) to y=4,x=3, when I add another one the first one added will be moved to y=1,x=3.

I have deducted that when adding a widget, the last one moved by user before adding will not maintain its position and will pe moved on the same column to initial y or the next available.

Is this behaviour normal or intented?

**Comment by iorom** [comment]
I removed this line "n._orig_y = n.y;" and now works the way I expected.

GridStackEngine.prototype.begin_update = function (node) {
        _.each(this.nodes, function (n) {
  //          n._orig_y = n.y;
        });
        node._updating = true;
    };

**Comment by kozilla** [comment]
Hi,

I experience similar issue.

My scenario : 

Creating grid with option float  : true , 

adding dynamically 1st tile on random position (in my case 2,2), move created tile to any new position with y change (2,3). By creating new  tile first one is moved back to previous y position (2,2) regardless if we lock whole grid or just lock implicitly"unstable"  tile.

Any thoughts on that ?

Thanks,

**Comment by troolee** [comment]
Fixed. Thanks for feedback.
