### ISSUE TITLE
Autoscroll not possible on Gridstack?

### ISSUE THREAD

**Issue by renebrain** [troolee/gridstack.js#94]
I have a rather strange behaviour on my Gridstack. As long the mouse is over the gridstack and i do a middle click with the mouse then the autoscroll function of the mouse is not fired. Everywhere else in the application it works. We tested it on Ubuntu v.14.04 x64 Firefox - 36.0.1 and on Windows 8.1 x64 Firefox 36.0.1. On all other Browsers it actually works. So is that a Firefox-only problem? Autoscroll was enabled in the Firefox settings, of course ;)

**Comment by troolee** [comment]
What is autoscroll? 

Unfortunately (or fortunately) I don't use mouse and don't have one. But I think the problem could be with jQuery Draggable. Could you please check this sample http://jqueryui.com/draggable/ ?
