### ISSUE TITLE
Nested grid not retaining the relative position in vertical mode

### ISSUE THREAD

**Issue by KrishnaPG** [troolee/gridstack.js#98]
Thank you for sharing this good work - it is very helpful. The bootstrap style of responsiveness is very useful and the nested grids help implement very useful functions such as row or inner columns etc. (like col-xs inside col-md etc..). However, there seems to slight problem with it in the present state. 

For example, for the demo at http://troolee.github.io/gridstack.js/demo/nested.html when the outer grid is resized with mouse, it works great (and the inner grid items retains their relative positions and sizes). But when the *browser* is resized to be small, all widgets (including those inside at the inner levels) collapse to single vertical line (thus no more respecting the inner-outer hierarchy).

In the vertical mode, only the outer widget should become part of vertical line of widgets, while the "inner widgets still keep their relative positions and size" inside it. I believe the purpose of outer widget is to protect the inner levels from loosing their relative positions. 

If the present behavior (of making all equal width irrespective of inner-outer) is intention and by design, then at least there should be an *option* (something like, "retain inner structure" or "protect inner grid") which when set to true, the inner grids will retain their relative position and size irrespective of their parents.

**Comment by troolee** [comment]
You can achieve that behaviour by disabling one-column mode for nested grids.
